### ISSUE TITLE
Support for file upload

### ISSUE THREAD

**Issue by YashC** [graphql-dotnet/graphql-client#101]
Does graphql-client c# support file upload? If yes, is there an example for reference? otherwise, any pointers or best approaches to handle this scenario? 

Here is a spec for file upload(multipart-formdata)
[https://github.com/jaydenseric/graphql-multipart-request-spec](https://github.com/jaydenseric/graphql-multipart-request-spec)

Thanks.

**Comment by deinok** [comment]
Actually, It just support what is defined in the official spec. We are also working on subscriptions (the underlaying protocol is not defined already)

So, for now we will not implement this :(

About the best aproach to actualy implement this is hardcoding the queries that require this file uploads.

**Comment by hupo376787** [comment]
This is a really needed function...
