### ISSUE TITLE
Hi, I am using the graphql client  in my app for query and mutation. Is this client allow me to upload file ? 

### ISSUE THREAD

**Issue by TohWei** [graphql-dotnet/graphql-client#102]
Hi, I would like to upload file and post something through graphql client. Is this possible over this component?   if yes, could you please provide sample or any references on how to use it? 

Thanks.

**Comment by Sorix** [comment]
It is not possible through GraphQL ideology, GraphQL is used with strings, not binary data. You could encode files as string, but it is not good approach. In most ways you need to upload file via different API and post unique file identifier through GraphQL request.

**Comment by deinok** [comment]
As @Sorix pointed, no, actualy any part of the RFC faces how to upload files

**Comment by hupo376787** [comment]
This is a really needed function...

Any progress or plans now?

Thx

**Comment by sungam3r** [comment]
Relates to graphql-dotnet/graphql-dotnet#511

**Comment by jfm007** [comment]
guys, who ever needs this, created an inheritated class from GraphQLHttpRequest and overrid the ToHttpRequestMessage
Mutate the request satisfies the multipart request requirement and you are good to go. At least I got it working with one of our graphql api. Still better than raw http request or rest request, eventhough still better the official library suports it.

**Comment by Eweol** [comment]
Hi @jfm007 ,
do you have an example which can be used?
