### ISSUE TITLE
crash on xamarin.forms 4.0.0.346134-pre9

### ISSUE THREAD

**Issue by xxyuze** [graphql-dotnet/graphql-client#105]
crash on xamarin.forms 4.0.0.346134-pre8 and pre0

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Basic Fault Adddress Reporting
=================================================================
Memory around native instruction pointer (0x10ec84657):0x10ec84647  17 49 89 f3 45 23 5a 18 49 c1 e3 04 4d 03 5a 10  .
I..E#Z.I...M.Z.
0x10ec84657  49 3b 33 75 04 41 ff 63 08 49 83 3b 01 76 0d 49  I;3u.A.c.I.;.v.I
0x10ec84667  83 c3 10 49 3b 33 75 f1 41 ff 63 08 72 64 4d 8b  ...I;3u.A.c.rdM.
0x10ec84677  5b 08 eb 0a 49 83 3b 01 76 0d 49 83 c3 10 49 3b  [...I.;.v.I...I;

=================================================================

**Comment by deinok** [comment]
Not related to this repo

**Comment by xxyuze** [comment]
It is indeed a bug caused by this library. The program crashed while sending a Graphql request. It works fine in pre7. I hope to support pre8 as soon as possible.

**Comment by xxyuze** [comment]
> Not related to this repo

It is indeed a bug caused by this library. The program crashed while sending a Graphql request. It works fine in pre7. I hope to support pre8 as soon as possible.

**Comment by rose-a** [comment]
> This usually indicates a fatal error in the mono runtime or one of the native libraries used by your application.

*GraphQL.Client* is neither a part of mono runtime nor a native library...
