### ISSUE TITLE
.NET Core / VS

### ISSUE THREAD

**Issue by chelliwell** [graphql-dotnet/graphql-client#106]
Hi. I've just downloaded this project to be examining/evaluating, and I think (?) some or all of the projects are targeting .NET Core 3.0 - which seems to be still in pre-release state?
So I was wondering what version of Visual Studio people are using - is 2019 needed (in order to be able to use Core 3.0)?

**Comment by deinok** [comment]
@chelliwell Yes, you need the dotnet-sdk_3.0 and the recomended IDE is VS2019 or Rider
Version 2.0.0 will be released some days after dotnet_3.0
