### ISSUE TITLE
GetDataFieldAs doesn't use JsonSerializationSettings

### ISSUE THREAD

**Issue by ullmark** [graphql-dotnet/graphql-client#107]
I encountered this issue while using the graphql-client. I (wrongfully?) assumed that assigning a `JsonSerializerSettings` to the `GraphQLHttpClientOptions` would affect how `GetDataFieldAs` worked but it only seemed to affect how the request was serialized. 

If that's infact an issue, I could attempt writing a pull request to fix it.

**Comment by pikax** [comment]
Can you provide an sample? 

I think where the problem is an I can create a PR

**Comment by ullmark** [comment]
@pikax Yes, well.. the issue is that this line; https://github.com/graphql-dotnet/graphql-client/blob/master/src/GraphQL.Common/Response/GraphQLResponse.cs#L34 doesn't pass the serializer to the `ToObject<Type>()` call. 

I'll submit a PR.

**Comment by deinok** [comment]
As GetDataFieldAs will be deleted from the API i'm going to close this
