### ISSUE TITLE
Any ETA for V2?

### ISSUE THREAD

**Issue by SimonCropp** [graphql-dotnet/graphql-client#108]
Any list of outstanding issues i can help with?

**Comment by ViableClanMember** [comment]
Bump. Latest vs2019 is saying `Unable to parse version value '2.0.0-alpha.3' from 'packages.config'`

**Comment by SimonCropp** [comment]
@ViableClanMember move over to `PackageReference` instead of 'packages.config'.

**Comment by rose-a** [comment]
@deinok Would you mind creating a list of issues people can work on to get V2 ready for release? I suppose there is a lot of interest in getting V2 out and some people would gladly help out if you're busy...

**Comment by alexgit** [comment]
@deinok My team and I are also interested in helping to get 2.0 released. Our employer actively encourages OSS contributions. We can contribute code, reviews, tests - whatever is needed. Please get in touch if you're interested.

**Comment by deinok** [comment]
Hi all, sorry for delays.
The intention is to release v2.0.0 will a really stable API aprox the same days netcoreapp3.0 is released.

Now, with netcore-preview7 the API is considerated  like a RC.

The general intention from now to the release day is to stabilize the API.

Also, from my enterprise, I have green light to merge our own GraphQL client with this one. So some advanced features will be added.

PD: the Licence will be the same. MIT ;)

**Comment by rolfwessels** [comment]
Can we get another beta release ? There have been a lot of changes since 2.0.0-alpha.3

**Comment by alexgit** [comment]
@deinok do you plan to release v2.0.0 soon?

**Comment by plemanach** [comment]
@deinok  any help with the release ?

**Comment by rose-a** [comment]
Hi all,

I have finally finished the restructure and API changes started by @deinok.

The one single blocking point from releasing v2.0.0 is that someone has already uploaded a alpha version of *GraphQL.Client* under the package id *GraphQL.Client.Http*, which now prevents me from uploading the newly split-off library containing the http client.

I've asked the owner to transfer this package id to me and now hope for a quick response...

Meanwhile you can try out the pre-release packages available in this repo: https://github.com/graphql-dotnet/graphql-client/packages

**Comment by sidhants** [comment]
> Hi all,
> 
> I have finally finished the restructure and API changes started by @deinok.
> 
> The one single blocking point from releasing v2.0.0 is that someone has already uploaded a alpha version of _GraphQL.Client_ under the package id _GraphQL.Client.Http_, which now prevents me from uploading the newly split-off library containing the http client.
> 
> I've asked the owner to transfer this package id to me and now hope for a quick response...
> 
> Meanwhile you can try out the pre-release packages available in this repo: https://github.com/graphql-dotnet/graphql-client/packages

@rose-a Thanks for the awesome work and getting things back up and running. We all appreciate your time and effort on prioritizing this and working on the new release.

**Comment by rose-a** [comment]
There it is: https://github.com/graphql-dotnet/graphql-client/releases/tag/v2.0.0

I renamed the packages again (*GraphQL.Client* is now still the http client package)...
