### ISSUE TITLE
Increasing the timeout limit?

### ISSUE THREAD

**Issue by arnioo** [graphql-dotnet/graphql-client#113]
Hi, am I somehow able to increase the timeout limit by the HttpClient implemented in GraphQLClient? 
Passing an cancellation token I am able to cancel the request before the timeout but if the request takes longer than 100 seconds the default timeout limit will cancel the request.

**Comment by rose-a** [comment]
Wouldn't it be better to not have a request take more than 100 s? Maybe use pagination... or a trigger-mutation and a corresponding subscription for notifying the completion of a long-running async task?

Don't know your server counterpart and application though...

**Comment by arnioo** [comment]
> Wouldn't it be better to not have a request take more than 100 s? Maybe use pagination... or a trigger-mutation and a corresponding subscription for notifying the completion of a long-running async task?
> 
> Don't know your server counterpart and application though...

That's a valid point, unfortunately I don't control the server and sometimes under load he will take over 100s to answer the request.

**Comment by deinok** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout?view=netcore-2.2
