### ISSUE TITLE
Including Fragments

### ISSUE THREAD

**Issue by gnmithun** [graphql-dotnet/graphql-client#115]
Hello. I am using this library for a UWP app and it's extremely useful. I apologize if this question has already been asked and answered, but how do I use a Fragment with this library?
Thanks

**Comment by gnmithun** [comment]
Figured it out. Closing the issue. Thanks

**Comment by wmarfil** [comment]
Thank you for providing the solution

**Comment by dojo90** [comment]
@gnmithun can you please provide your solution?

**Comment by wmarfil** [comment]
Figured it out, your fragment should be in the Query property of the GraphQLRequest object, your string in Query should look like this:

`
query{
  yourQuery{
    ...YourFragments
  }
}
fragment YourFragment on YourType{
  someField
}
`

did it from me. Was a bit confusing since your could think Query is just use as the body of a query but its not, also you can do a mutation instead.

**Comment by dojo90** [comment]
Actually I have the following `query`

Similar to this example https://www.apollographql.com/docs/react/data/fragments/#fragments-on-unions-and-interfaces

```qml
query{
  options{
	 optionsClasses{
	  properties{
		name
		... on BooleanProperty{
		  value
		}
		... on StringProperty{
		  value
		}
		... on IntegerProperty{
		  value
		}
	  }
	}
  }
}
```

With `Insomnia` I'm able to fetch all data without problems. Do I have to refactor my `query` to get it compatible with this library? Or are we talking about two different problems here?

**Comment by wmarfil** [comment]
Your case if Inline-Fragment which is quite different than the standard Fragment.

I tested Inline-Fragment queries without problems on my side, with the multiples Graphql object implementing one Interface (did not try out Union though).

 As long as your graph ql schema is valid that should work. Put your whole query as a string in a new GraphQLRequest Query property send it and thats it.

**Comment by dojo90** [comment]
Problem solved. During my unitTest the server was not properly setup. So my `query` is working as expected.
