### ISSUE TITLE
CreateSubscriptionStream doesn't send 'connection_init'

### ISSUE THREAD

**Issue by chelliwell** [graphql-dotnet/graphql-client#116]
[Ref subscriptions-api branch]
Whilst there is a definition of this message (GQL_CONNECTION_INIT), it doesn't seem to be used at all. Shouldn't this be being sent by GraphQLHttpSubscriptionHelpers.CreateSubscriptionStream prior to the subscription request?

I think the omission of this is why Apollo server is not seeing its subscriptions 'onConnect' event (it does if subscribing with Playground instead).
In fact, the code doesn't seem to [yet? work-in-progress?] make use of _any_ of the GQL_CONNECTION_ strings

**Comment by rose-a** [comment]
fixed in #152
