### ISSUE TITLE
OnReceive Event Never Triggered

### ISSUE THREAD

**Issue by halitizgin** [graphql-dotnet/graphql-client#117]
Everything okay, Graphql server is working properly. But, OnReceive event never triggered.

Code:

`
GraphQLHttpClient ws = new GraphQLHttpClient("http://localhost:4000/graphql");
IGraphQLSubscriptionResult result = ws.SendSubscribeAsync(@"
                subscription {
                  tableAdded {
                    id
                    no
                    state
                  }
                }
            ").Result;
result.OnReceive += (res) => { MessageBox.Show(res.Data); };
`
I tried connecting to "ws://localhost:4000/graphql". But, still have the same problem

**Comment by rose-a** [comment]
I recommend using the `CreateSubscriptionStream` method on `GraphQLHttpClient` to create a subscription. You have to subscribe to the created stream to actually initiate the subscription...

**Comment by halitizgin** [comment]
Sorry But, i could not find that method

**Comment by rose-a** [comment]
obsolete API
