### ISSUE TITLE
Version 2 roadmap

### ISSUE THREAD

**Issue by chelliwell** [graphql-dotnet/graphql-client#123]
Hi folks,
I was wondering what is the roadmap/timeline for v2. Do you have a date when you expect to finalise a 2.0.0 (ideally with Nuget package)? Will it incorporate the subscriptions branch?
The subscriptions support is vital for me, and I see some people like Alexander doing to work in this area. Would be great if all the enhancements could make it into master.
I can fork my own repo if necessary, but obviously I'd rather stay aligned with the real thing.

**Comment by SKGGitHub** [comment]
Can someone respond to this as we are also waiting to use it for Subscription.

**Comment by kryptonianson** [comment]
I too would like an answer to this question. thank you everyone.

**Comment by graphdb2** [comment]
Any news on version 2 with subscription ?

**Comment by graphdb2** [comment]
Any help required ?

**Comment by deinok** [comment]
v2.0.0 will be released some days after .NET Core 3.0 release. So probably it will be on 1 of October

**Comment by SKGGitHub** [comment]
Hi Team, .NET Core 3.0 version is release now. There was information somewhere that GraphQL.Clinet stable version Subscription Code would be released in align with .NET Core 3.0.

Do we have any update on that please?
