### ISSUE TITLE
DefaultRequestHeaders / Authorization header not added with SendSubscribeAsync call  

### ISSUE THREAD

**Issue by Ramesh-V-Nova** [graphql-dotnet/graphql-client#127]
Hi,

I am trying to use recent release v2.0.0-alpha.3, for subscriptions feature in my UWP app, I knew it is experimental API. I found authentication header is not passing with SendSubscribeAsync call.

I added authentication header in two ways 
 
**graphQLHttpClient.DefaultRequestHeaders.Add("Authorization", $"{authResponse.AuthenticationResult.AccessToken}");**

**graphQLHttpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Authorization", $"{authResponse.AuthenticationResult.AccessToken}");**

I checked the request using Fiddler app, no authentication header found. Please check following screen shot. Because of this I am getting Unauthorized exception and app crash.

Same I am doing for SendQueryAsync, It is sending authentication header with request and i got expected response from server.

<img width="960" alt="SubcriptionRequest" src="https://user-images.githubusercontent.com/50568017/62694880-cd5a9280-b9f2-11e9-954f-8dd67ab43825.PNG">

Thanks

**Comment by deinok** [comment]
Thanks @Ramesh-V-Nova this will be fixed for v2.0.0

**Comment by rose-a** [comment]
obsolete api
