### ISSUE TITLE
Is it possible to do .GetDataFieldAs<someObject>("main.targetFieldToBeMapped")?

### ISSUE THREAD

**Issue by frostshoxx** [graphql-dotnet/graphql-client#130]
Right now I can do `.GetDataFieldAs<someMainClass>("main")` to get the mapped object similar to the example Person object.

What am I wondering is whether we should be able to do `.GetDataFieldAs<someClassForField>("main.fieldThatIWanToMapToObject")`?

**Comment by sungam3r** [comment]
It is reasonable and not difficult.

**Comment by wolfpackt99** [comment]
also interested in this. please advise.

**Comment by sungam3r** [comment]
Well, this is implementation:
```c#
        public TOut? GetDataFieldAs<TOut>(string fieldName) where TOut : class {
            if (this.Data is JObject jObjectData) {
                return jObjectData.GetValue(fieldName).ToObject<TOut>();
            }
            return (TOut)this.Data!.GetType()
                .GetProperty(fieldName)
                .GetValue(this.Data!, null);
        }
```
Actually `this.Data` is `JObject`. This code takes first level property from this object and converts it to return type. So if you want nesting then split `fieldName` by dot sign and repeat `GetValue` call. Something like this:
```c#
  public static JToken GetByPath(this JToken token, string path)
        {
            var current = token;

            foreach (var name in path.Split('.'))
            {
                switch (current)
                {
                    case JObject obj:
                        current = obj.GetValue(name);
                        break;
                    default:
                        return null;
                }
            }

            return current;
        }

...
            JObject f = JObject.Parse("{ prop1: { prop2: { prop3: 1}}}");
            var t= f.GetByPath("prop1.prop2.prop3");
```


By the way @deinok removed `GetDataFieldAs` API some time ago :). I think he started the refactoring process.

**Comment by deinok** [comment]
Yep, in the future you will need to define the schema. Mostly to ensure type safety. But without scheme it will work with dynamic aka JSONObject.

So, when you send a GraphQLResponse you will need to define the schema you expect, so based on that schema I can parse it deleting the serialization information, and in theory it should be easier.

Last preview is expected to be launched before NETCore 3.0. and the release after the NETCore 3.0 release

**Comment by sungam3r** [comment]
> in the future you will need to define the schema. Mostly to ensure type safety.

Will it be optional?

**Comment by deinok** [comment]
Yes, something like GraphQLResponse will extend GraphQLResponse<dynamic>

But that wont be the recomended way as it depends on the underlaying deserialization way

**Comment by wolfpackt99** [comment]
Ok. Will look out for the release. I just grabbed the latest alpha-3 today and the `getdatafieldsas` was still there

**Comment by deinok** [comment]
@wolfpackt99 I recommend that in production code use v1.0.3 as works pretty well

So, as GetDataFieldAs will be destroyed I will close this issue. In the future the recommended way will be use a Schema.cs like that match the Server Schema in order to ensure type safety
