### ISSUE TITLE
How to set UseDefaultCredentials?

### ISSUE THREAD

**Issue by Heroloop** [graphql-dotnet/graphql-client#131]
Hi everyone,

Is there any way to set UseDefaultCredentials = true to allow the client can pass the windows authentication web server?

https://stackoverflow.com/questions/12212116/how-to-get-httpclient-to-pass-credentials-along-with-the-request

Thank u!

**Comment by marciordonez** [comment]
webClient.Credentials = CredentialCache.DefaultNetworkCredentials;
