### ISSUE TITLE
how do you get the fully rendered query?

### ISSUE THREAD

**Issue by josher565** [graphql-dotnet/graphql-client#132]
Hi folks, I'm debugging a feature and I'd like to be able to grab the query as it's been rendered by this line of code
`response = client.Execute(query, operationName, variables);`
Having a query with the data all filled out by the code removes guess work in case of error. Is there a way to do this? It would be ideal to be able to see the query before it's sent in a debugging context. Thanks folks :)

**Comment by deinok** [comment]
This is not related to the client library
