### ISSUE TITLE
PostAsync method does not work in WebGL due to System.Reflection.Emit reference

### ISSUE THREAD

**Issue by ondrej-mikulas** [graphql-dotnet/graphql-client#133]
I am trying to use graphql-client to build WebGL Client which communicates with graphql server.

Currently WebGL in Unity does not support  System.Reflection.Emit.

Call from line https://github.com/graphql-dotnet/graphql-client/blob/9511133bc922af7ef0cb1f760b7885a9243275e2/src/GraphQL.Client.Http/Internal/GraphQLHttpHandler.cs#L65 is using Newtonsoft.Json which internally use not supported functionality from System.Reflection.Emit. 

Here is Stack trace:
```
System.NotSupportedException: System.Reflection.Emit.DynamicMethod::.ctor
UnityLoader.js:1043   at System.Reflection.Emit.DynamicMethod..ctor (System.String name, System.Type returnType, System.Type[] parameterTypes, System.Type owner, System.Boolean skipVisibility) [0x00000] in <00000000000000000000000000000000>:0 
UnityLoader.js:1043   at Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.CreateDynamicMethod (System.String name, System.Type returnType, System.Type[] parameterTypes, System.Type owner) [0x00000] in <00000000000000000000000000000000>:0 
UnityLoader.js:1043   at Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.CreateDefaultConstructor[T] (System.Type type) [0x00000] in <00000000000000000000000000000000>:0 
UnityLoader.js:1043   at Newtonsoft.Json.Serialization.DefaultContractResolver.GetDefaultCreator (System.Type createdType) [0x00000] in <00000000000000000000000000000000>:0 
UnityLoader.js:1043   at Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract (Newtonsoft.Json.Serialization.JsonContract contract) [0x00000] in <00000000000000000000000000000000>:0 
UnityLoader.js:1043   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract (System.Type objectType) [0x00000] in <00000000000000000000000000000000>:0 
UnityLoader.js:1043   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract (System.Type objectType) [0x00000] in <00000000000000000000000000000000>:0 
UnityLoader.js:1043   at Newtonsoft.Json.Serialization.CamelCasePropertyNamesContractResolver.ResolveContract (System.Type type) [0x00000] in <00000000000000000000000000000000>:0 
UnityLoader.js:1043   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContractSafe (System.Object value) [0x00000] in <00000000000000000000000000000000>:0 
UnityLoader.js:1043   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <00000000000000000000000000000000>:0 
UnityLoader.js:1043   at Newtonsoft.Json.JsonSerializer.SerializeInternal (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <00000000000000000000000000000000>:0 
UnityLoader.js:1043   at Newtonsoft.Json.JsonSerializer.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <00000000000000000000000000000000>:0 
UnityLoader.js:1043   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializer jsonSerializer) [0x00000] in <00000000000000000000000000000000>:0 
UnityLoader.js:1043   at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <00000000000000000000000000000000>:0 
UnityLoader.js:1043   at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <00000000000000000000000000000000>:0 
UnityLoader.js:1043   at GraphQL.Client.GraphQLClient+<PostAsync>d__22.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
UnityLoader.js:1043   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].Start[TStateMachine] (TStateMachine& stateMachine) [0x00000] in <00000000000000000000000000000000>:0 
UnityLoader.js:1043   at GraphQL.Client.GraphQLClient.PostAsync (GraphQL.Common.Request.GraphQLRequest request, System.Threading.CancellationToken cancellationToken) [0x00000] in <00000000000000000000000000000000>:0 
UnityLoader.js:1043   at GraphQL.Client.GraphQLClient.PostAsync (GraphQL.Common.Request.GraphQLRequest request) [0x00000] in <00000000000000000000000000000000>:0 
```

Would it be possible to use another serialization/deserialization package, which would replace Newtonsoft.Json, which functionality is not supported in WebGL? (Going to try other one)

Maybe in the future there could be option to replace hardcoded Newtonsoft.json

**Comment by sungam3r** [comment]
Newtonsoft.Json has `DynamicCodeGeneration` [setting](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/JsonTypeReflector.cs#L453) which was evaluated as `true` (perhaps by mistake, but nevertheless it is clear that the author of the package provided for several modes of operation and tried to provide an optimized default path).

You can use custom contract resolver and override `DefaultContractResolver`:

```c#
public class MyResolver : DefaultContractResolver
{
  protected override IValueProvider CreateMemberValueProvider(MemberInfo member)
  {
    return new ReflectionValueProvider(member);
  }
}
```

Then set this resolver to json serializer settings into graphql client options.

> Maybe in the future there could be option to replace hardcoded Newtonsoft.json

It is a long way, but many follow it include ASP.NET Core Team.

@deinok, please, consider to move Newtonsoft.Json dependency out of core graphql client code.

**Comment by sungam3r** [comment]
>  which functionality is not supported in WebGL

Also if you are sure about it, then you may post issue to Newtonsoft.Json repo.

**Comment by deinok** [comment]
Could also be related to use `dynamic` as the default value of `Data`.
Also, the idea is to use System.Text.Json as the default

**Comment by sidhants** [comment]
@ondrej-mikulas  @sungam3r I have the same issue in trying to build for the Lumin platform (il2cpp) in Unity where dynamics is not supported and i get the same errors. 

What is the workaround for this, that would be extremely helpful? I dont exactly understand the DefaultContractResolver solution above or if there is a way to use another parser. instead of newton json.  Any help would be appreciated!
Thanks,
Sidhant

**Comment by sidhants** [comment]
> Could also be related to use `dynamic` as the default value of `Data`.
> Also, the idea is to use System.Text.Json as the default

Can you elaborate on this please in terms of how i can use it instead of dynamics?

**Comment by sungam3r** [comment]
> I dont exactly understand the DefaultContractResolver solution above

@sidhants  Set aforementioned settings [here](https://github.com/graphql-dotnet/graphql-client/blob/master/src/GraphQL.Client.Http/GraphQLHttpClientOptions.cs#L25).

**Comment by sidhants** [comment]
> > I dont exactly understand the DefaultContractResolver solution above
> 
> @sidhants Set aforementioned settings [here](https://github.com/graphql-dotnet/graphql-client/blob/master/src/GraphQL.Client.Http/GraphQLHttpClientOptions.cs#L25).

Thanks for the pointer. The GraphQLResponse class has a dynamic Data field to access the response. That is still an issue on il2cpp. What is the best way to access data from a request?

**Comment by sidhants** [comment]
> > I dont exactly understand the DefaultContractResolver solution above
> 
> @sidhants Set aforementioned settings [here](https://github.com/graphql-dotnet/graphql-client/blob/master/src/GraphQL.Client.Http/GraphQLHttpClientOptions.cs#L25).

@sungam3r Thanks for the pointer. I tried setting the 'Options' field as below

`    private GraphQLHttpClient graphQLHttpClient;
    public Text errorText;

    private void Start()
    {
        GraphQLHttpClientOptions options = new GraphQLHttpClientOptions();
        options.JsonSerializerSettings = new JsonSerializerSettings
        {
            ContractResolver = new CamelCasePropertyNamesContractResolver(),
            Converters = new List<JsonConverter>
            {
                new StringEnumConverter()
            }
        };
        options.EndPoint = new Uri("https://api.graph.cool/simple/v1/ciyz901en4j590185wkmexyex");
        graphQLHttpClient = new GraphQLHttpClient(options);

        TestRequest();
    }

    private async void TestRequest()
    {
        string query = @"
	        query allUsers {
                allUsers {
		            id
                    name
                }
	        }";

        try
        {
            Debug.Log("try send req");
            GraphQLResponse graphQLResponse = await graphQLHttpClient.SendQueryAsync(query);

            Debug.Log("after await");
            if (graphQLResponse.Errors != null && graphQLResponse.Errors.Length > 0)
            {
                errorText.text = graphQLResponse.Errors[0].Message;
                Debug.Log("Error: " + graphQLResponse.Errors[0].Message);
            }
            else
            {
                Debug.Log("success");
            }
        }
        catch (Exception e)
        {
            Debug.Log("exception" + e.Message);
            errorText.text = e.Message;
        }
    }`

However i get this error on an il2cpp based build. Any idea how i can get past this?

`UnityEngine.Logger:Log(LogType, Object)
    Main:.ctor()
    System.Net.Http.Headers.HttpHeaders:SetValue(String, T, Func`2)
    Main:TestRequest()
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)
11-02 18:53:19.505 14289-14305/? I/Unity: exceptionError getting value from 'Query' on 'GraphQL.Common.Request.GraphQLRequest'.
    UnityEngine.Logger:Log(LogType, Object)
    Main:.ctor()
    System.Net.Http.Headers.HttpHeaders:SetValue(String, T, Func`2)
    Main:TestRequest()`

**Comment by sungam3r** [comment]
This is some other error related to reading / writing the http header from UnityEngine. I can’t say anything about It and I did not understand the stacktrace you quoted.

**Comment by sidhants** [comment]
> This is some other error related to reading / writing the http header from UnityEngine. I can’t say anything about It and I did not understand the stacktrace you quoted.

@sungam3r Please see if this helps. Below is the stack trace from the line:

GraphQLResponse graphQLResponse = await graphQLHttpClient.SendQueryAsync(query);

`11-03 14:28:23.411 27896-27912/? E/Unity: NullReferenceException: Object reference not set to an instance of an object.
      at System.Linq.Expressions.Interpreter.LightLambda.MakeRunDelegateCtor (System.Type delegateType) [0x00000] in <00000000000000000000000000000000>:0 
      at System.Linq.Expressions.Interpreter.LightLambda.GetRunDelegateCtor (System.Type delegateType) [0x00000] in <00000000000000000000000000000000>:0 
      at System.Linq.Expressions.Interpreter.LightLambda.MakeDelegate (System.Type delegateType) [0x00000] in <00000000000000000000000000000000>:0 
      at Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateGet[T] (System.Reflection.PropertyInfo propertyInfo) [0x00000] in <00000000000000000000000000000000>:0 
      at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue (System.Object target) [0x00000] in <00000000000000000000000000000000>:0 
      at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonCo
`

**Comment by sidhants** [comment]
@sungam3r I'm still relatively new so thanks for the help. I'm wondering if I am setting the custom contract resolver correctly for this to work. I am using the nuget package dll's directly in Unity. I hope I don't have to recompile the client. Doing the below gives me a unable to find contructor error.

`GraphQLHttpClientOptions options = new GraphQLHttpClientOptions();

        options.JsonSerializerSettings.ContractResolver = new MyResolver();
        
        options.EndPoint = new Uri("https://api.graph.cool/simple/v1/ciyz901en4j590185wkmexyex");
        graphQLHttpClient = new GraphQLHttpClient(options);`


Error trace:
`11-03 14:57:42.641 29465-29478/? E/Unity: Unable to find libc
11-03 14:57:44.548 29465-29478/? E/Unity: JsonSerializationException: Unable to find a constructor to use for type GraphQL.Common.Response.GraphQLResponse. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'error', line 1, position 9.
      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract objectContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, Newtonsoft.Json.Serialization.JsonProperty containerProperty, System.String id, System.Boolean& createdFromNonDefaultCreator) [0x00000] in <00000000000000000000000000000000>:0 
      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newt`

**Comment by sungam3r** [comment]
What version of graphql-client do you use?

**Comment by ssharma001** [comment]
> What version of graphql-client do you use?

It is v2.0.0-alpha.3 downloaded from nuget packages in VS2019.

**Comment by sungam3r** [comment]
On the one hand, this is good, since an error now occurs when a response is received. Previously, it happened even upon request. You were able to serialize the request. Now deserialization of the response does not work. This is bad. The error message is strange because `GraphQLResponse` **has** a default constructor.

> I am using the nuget package dll's directly in Unity.

Can you send me a graphql-client dll file?

And what version of Newtonsoft.Json do you use?

**Comment by sidhants** [comment]
[GraphQL.Client.2.0.0-alpha.3.zip](https://github.com/graphql-dotnet/graphql-client/files/3802881/GraphQL.Client.2.0.0-alpha.3.zip)
[Main.zip](https://github.com/graphql-dotnet/graphql-client/files/3802883/Main.zip)
 
Attached the dll's i am using in Unity (.NET 2 std) and also my main.cs file for the tests.

**Comment by sungam3r** [comment]
Then let's first make sure that the problem is really specific to the Unity. Try executing your current code (with `ReflectionValueProvider`) from a simple console application.

**Comment by sungam3r** [comment]
I don’t know, but maybe some permissions are required for reflection in the Unity.

**Comment by sidhants** [comment]
> Then let's first make sure that the problem is really specific to the Unity. Try executing your current code (with `ReflectionValueProvider`) from a simple console application.

Also, it only happens with il2cpp option and not on mono in Unity. Mono works fine without any issues. But the devices I am working with only support il2cpp so i am stuck with that and finding the solution.

**Comment by sungam3r** [comment]
By the way, if in the end nothing helps and it will be a pity to waste time, then maybe you should try this - https://assetstore.unity.com/packages/tools/input-management/json-net-for-unity-11347

**Comment by sungam3r** [comment]
And of course you have to recompile the graphql-client to target it to differenct serializer, but it's simple, it's a pretty small package.

**Comment by sungam3r** [comment]
Also, I would still recommend you to post an issue for this problem in NewtonSoft.Json repo. The type has a constructor, but the serializer for some reason does not find it.

**Comment by sidhants** [comment]
> And of course you have to recompile the graphql-client to target it to differenct serializer, but it's simple, it's a pretty small package.

This is sounding promising. So i can basically try to use this client with the unity json dll. I remember last time I tried using the unity dll, the client complained of a different version that it targeted and  wanted 11.0. Any pointers to how i can recompile with VS?

**Comment by sidhants** [comment]
> Also, I would still recommend you to post an issue for this problem in NewtonSoft.Json repo. The type has a constructor, but the serializer for some reason does not find it.

I will definitely post there as well. Really appreciate your help on this :)

**Comment by sungam3r** [comment]
> Any pointers to how i can recompile with VS?

Just git checkout and build with required package https://www.nuget.org/packages/Json.Net.Unity3D/

[Recompiled.zip](https://github.com/graphql-dotnet/graphql-client/files/3803056/Recompiled.zip)

**Comment by sungam3r** [comment]
I did not test anything, just rebuilt the package with another dependency.

**Comment by sidhants** [comment]
> > Any pointers to how i can recompile with VS?
> 
> Just git checkout and build with required package https://www.nuget.org/packages/Json.Net.Unity3D/
> 
> [Recompiled.zip](https://github.com/graphql-dotnet/graphql-client/files/3803056/Recompiled.zip)

Thanks for your effort. I tried it out but still get the same 'no constructor error'. Either the custom contract resolver setting is not being applied properly from my end. Can you verify that the Main.cs script I attached is the right way to do the setting? 

In the meantime i will post on newtonjson repo for any ideas.

**Comment by sidhants** [comment]
Also found a similar issue on newton json unity repo https://github.com/SaladLab/Json.Net.Unity3D/issues/35

**Comment by sungam3r** [comment]
> Can you verify that the Main.cs script I attached is the right way to do the setting?

You say that in other cases everything works. Once everything works, the configuration is correct.

**Comment by sungam3r** [comment]
Also Json.Net.Unity3D is abandoned project. The last commit there was over 3 years ago. I don’t think there is a chance to get any kind of answer there.

**Comment by sidhants** [comment]
> > Can you verify that the Main.cs script I attached is the right way to do the setting?
> 
> You say that in other cases everything works. Once everything works, the configuration is correct.

Correct. In the sense that "mono" already supports dynamics as well as reflection so no issues there. But for il2cpp this setting is crucial so that newton json does not use any dynamics internally. But no luck so far getting it working. I'll keep trying.

**Comment by sidhants** [comment]
@sungam3r I got things to work with some modification/addition to the source code and debugging through. The request always gives a 200 ok. The constructor error is more to do with how the graphqlresponse class is set up with a dynamic data field which fails to deserialize under il2cpp, particularly this method fails at "jsonSerializer.Deserialize<GraphQLResponse>(jsonTextReader)" -

`public async Task<GraphQLResponse> ReadHttpResponseMessageAsync(HttpResponseMessage httpResponseMessage) {
			using (var stream = await httpResponseMessage.Content.ReadAsStreamAsync().ConfigureAwait(false))
			using (var streamReader = new StreamReader(stream))
			using (var jsonTextReader = new JsonTextReader(streamReader)) {
				var jsonSerializer = new JsonSerializer {
					//ContractResolver = this.Options.JsonSerializerSettings.ContractResolver
					ContractResolver = new CamelCasePropertyNamesContractResolver()
				};
				try {
					return jsonSerializer.Deserialize<GraphQLResponse>(jsonTextReader);
				}
				catch (JsonReaderException exception) {
					if (httpResponseMessage.IsSuccessStatusCode) {
						throw exception;
					}
					throw new GraphQLHttpException(httpResponseMessage);
				}
			}
		}`

Ultimate fix is more flexibility and i suggested adding an additional API to simply return string/error to the consumer. Or some modification in the setup of graphqlresponse class.

**Comment by sungam3r** [comment]
I am following the changes in this project. I see that it is in a lengthy refactoring process. In fact, there is not much code and it is not complicated to be afraid to just take and play the same code in your project without the need to use this package with all problems described above.

**Comment by rose-a** [comment]
should be solved through using * System.Text.Json* for deserialization...
