### ISSUE TITLE
Socket Exception when network is not connected. How to configure time outs or get network error message?

### ISSUE THREAD

**Issue by sidhants** [graphql-dotnet/graphql-client#134]
How can I configure the request to either time out (after a set timer if no response) or provide a network error in case there is no connection?

This is the request:
 var graphQLResponse = await graphQLClient.PostAsync(deviceTokenAuthRequest)

This is the exception I currently get after about ~20 seconds inside Unity. What is the best approach to handle in this situation. Try Catch? Any advice will be helpful.

EXCEPTION:
SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) (at <c9226b2f33b7421e85bb391f94075e49>:0)
System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) (at <c9226b2f33b7421e85bb391f94075e49>:0)
Rethrow as WebException: Error: ConnectFailure (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
)
System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) (at <c9226b2f33b7421e85bb391f94075e49>:0)
System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () (at <5e8fe0473ffc45969fdba20b48820489>:0)
Rethrow as HttpRequestException: An error occurred while sending the request
System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () (at <5e8fe0473ffc45969fdba20b48820489>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Net.Http.HttpClient+<SendAsyncWorker>d__47.MoveNext () (at <5e8fe0473ffc45969fdba20b48820489>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
GraphQL.Client.GraphQLClient+<PostAsync>d__22.MoveNext () (at <2ded8f85f6c84cefa0c1b3543135b506>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
Main+<SendDeviceTokenAuthRequest>d__5.MoveNext () (at Assets/Main.cs:42)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at C:/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:115)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

**Comment by deinok** [comment]
In v2.0.0 you will be able to feed the GraphQL with your own HttpClient. (An the timeout for that HttpClient using HttpClient.SetTimeout)

My recommendation, using HttpClient you can have 3 kind of errors related to timeout. (Timeout itself, loosing IP(unplug ethernet cable) and loosing connection but having IP (no signal) )
Try Catch SocketException and HttpException

**Comment by sidhants** [comment]
@deinok  For now, I have used the CancellationTokenSource to handle timeouts for responses taking longer but a valid connection. 
Try Catch works well for the socket exception with a broken connection. Tried it.
**Will the unplug ethernet cable give the httpException for the third case?**

I will be upgrading soon to 2.0.0. Currently I'm on 1.0.3.
