### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by valbers** [graphql-dotnet/graphql-client#135]
I just wanted to take a look in the implementation of GraphQLResponse.GetDataFieldAs<T>(), but I can't seem to find this method in the definiton of class [`GraphQLResponse`]( https://github.com/graphql-dotnet/graphql-client/blob/master/src/GraphQL.Client/GraphQLResponse.cs ). Where is it?

**Comment by sungam3r** [comment]
It was removed not so long ago.
![изображение](https://user-images.githubusercontent.com/21261007/65812140-9a02db80-e1cb-11e9-826d-176e31d7f9b5.png)

**Comment by valbers** [comment]
Oh ok, thank you.
