### ISSUE TITLE
Example doesn't work on Blazor

### ISSUE THREAD

**Issue by OscarCanek** [graphql-dotnet/graphql-client#141]
I'm using Blazor with the following versions:

<img width="488" alt="image" src="https://user-images.githubusercontent.com/3521524/69401783-96676e80-0cbb-11ea-94f5-dc1a6e5c575c.png">

But when I try to execute the example of the readme I got the following error:

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/3521524/69401710-6324df80-0cbb-11ea-87a9-f1cd94b99d0e.png">

Could you help me?

**Comment by sungam3r** [comment]
See this - https://github.com/aspnet/AspNetCore/issues/9125

**Comment by OscarCanek** [comment]
Thank you @sungam3r, the link help me and I was able to resolve the problem, this is what I did:

```
services.AddScoped(opt => new GraphQLClient("https://localhost:5001/graphql",
                new GraphQLClientOptions {HttpMessageHandler = new WebAssemblyHttpMessageHandler()}));
```
