### ISSUE TITLE
Passing Object as Variables to Query

### ISSUE THREAD

**Issue by Dmo16** [graphql-dotnet/graphql-client#142]
Hello, 

I have a mutation that requires a variable structure such as this: 

`{"owner": {"connect" : {"id": "ck3f6u9t9002d07335hj6ya6z"}}, "message":  "The query is working" }`

Whenever I try to structure that in my C# code everything fails.

How do we pass nested variables like this to the server?

Forgive me for my poor terminology.

**Comment by rose-a** [comment]
Passing variables like this is entirely possible, just make sure the object you are putting in there is correctly serialized by `Newtonsoft.Json`.

What the exact failure?

**Comment by Dmo16** [comment]
@rose-a Everything I try pass in there gets converted to pure string and not interpreted.

I've tried a few things to serialize the object, do you have an example I can check out?

Thanks.

**Comment by rose-a** [comment]
You should be able to define the aforementioned variables like this:

```c#
var graphQLRequest = new GraphQLRequest(yourQueryString) 
{ 
    Variables = new {
        owner = new {
            connect = new {
                id = "ck3f6u9t9002d07335hj6ya6z"
            }
        },
        message = "The query is working"
    }
};
```

Variables is a dynamic object which is then serialized using the `Newtonsoft.Json` library. 

Which version of the library are you using?

**Comment by Dmo16** [comment]
@rose-a *face palm* 

I forgot the "new" in my serialization attempts.

It works now, structured just as you laid out. 

Thank you for pointing out the obvious! 

As far as version, I'm using: 2.0.0-alpha.3

**Comment by Bakaji** [comment]
is there a way to pass object as input without using new {  }  because I have so much fields inside input (about 12 field! ) so it be clean if I can just do

```C#
variables=new {
   input= objectOfFields
}
```

**Comment by rose-a** [comment]
if you have a single input variable of a type matching your `objectOfFields` object then you can do that.

If you have many input variables with matching properties in `objectOfFields` then do `Variables = objectOfFields`. Be aware that you have to name your query variables so that they match the serialized name of the respective property...

**Comment by enkodellc** [comment]
Not sure if this will help anyone but I needed to have optional variables / variables with custom logic so I did something like this:

```
        public dynamic GetGraphQLVariables()
        {
            dynamic variables = new ExpandoObject();
            if (!String.IsNullOrEmpty(PostalCode)) variables.zip = PostalCode;
            if ((Bedrooms ?? 0) > 0) variables.bed_count = Bedrooms;
            if ((Bathrooms ?? 0) > 0) variables.bath_count = Bathrooms;
            if ((Price ?? 0) > 0) variables.market_value_total =  Price;
            if (!String.IsNullOrEmpty(City)) variables.city = City;
            if (!String.IsNullOrEmpty(County)) variables.mailing_county = County;

            return variables;
        }
Then to retrieve the optional / logic coded variables
      Variables = GetGraphQLVariables()
```
I also built custom methods to build the where filter and the variable names. I am not a fan of graphql, at least for what I am working on the dev should have just used SQL. So much overhead with the JSON object.
