### ISSUE TITLE
Help Wanted: Dynamically Check the "Data" Query Field Returned

### ISSUE THREAD

**Issue by Dmo16** [graphql-dotnet/graphql-client#143]
Forgive my terminology, still pretty new at all this stuff.

Consider the following: 
`...
var queryName = "userCheck"
var apiResponse = await gqlClient.SendQueryAsync(gqlQueryString);

if (apiResponse.Data.queryName == null) 
{
    ...Code to run
}`

I am attempting to use the variable: queryName to dynamically pass the name of the graphql Query to the method so that I can make my gql method generic.
I'm having an issue though with my if statement, because I can't use `Data.queryName` as the variable name gets interpreted as the literal query name at compile time, instead of whatever the string is that is stored in the variable.

My goal: I have several objects that have to run queries and so instead of duplicating code in each, I'm trying to write a method that takes all the parameters, does the query and returns the instantiated object.

Right now I have the method returning the `GraphQLResponse` object, but that means I have to do error checking and data manipulation individually in each class, which is leading to a lot of duplicated code with only a few tweaks here and there.

Is there a way I can use that variable containing the query names and check the Data object dynamically with the queryName variable?

**Comment by sungam3r** [comment]
Data contains response object, there is no query name. GraphQL server does not return query name and it does not return variables - all this is a client stuff. Or I did not understand the question.

**Comment by Dmo16** [comment]
@sungam3r 

With the code above, the return that comes back from the server, in the data object is a JObject, and Data returns: 

`
{
  "userCheck": null
}
`
If nothing is found from the server.

So, if I don't use this format: 

`apiResponse.Data.queryName`

My if statement will always return true because even with a "null" graphQL return, the Data object still "HasValues".

Running a check on just: `apiResponse.Data` isn't specific enough to determine whether my query found results.

I think it works similar to this example from the home page of this repo: 

`var dynamicHeroName = graphQLResponse.Data.hero.name.Value; //Value of data->hero->name`

If I'm not explaining myself well please let me know!

**Comment by sungam3r** [comment]
`"userCheck": null` is a field name and field value, now I don't understand what you call `queryName`. 
However, you can use apiResponse.Data as JObject - it is JObject.

**Comment by Dmo16** [comment]
@sungam3r 
Yes, I understand that this is a field name and field value. What I need to check for, is if the value is NULL. 

The only way that I can do that, is if I reference the field, like this: 
`apiResponse.Data.userCheck` if all I use is: `apiResponse.Data`, it _always returns _true_ because the Data object _always returns a field_, even if the query result is null.

The `queryName` variable is what I'd like to use to be able to pass the method any query, and use that variable to reference the field name.

Perhaps I'm not going about my checking the right way. Do you have an example where you check to see if the Data object is null?

A successful query like above would return something like this: 

`{ usercheck: {
     id: 1
     name: Roger
     email: test@email.com
}`

But because as a new user, no record is found, the graphql server returns this: 

`{"usercheck" : null}`

Which means when I check the Data JObject to see if it is null, it is not, because some json returns.

**Comment by rose-a** [comment]
Cast the response to a `JObject` and then use it like described in https://www.newtonsoft.com/json/help/html/QueryingLINQtoJSON.htm.

This way you can look for "dynamically" named fields. 

You could also use GraphQL aliases (see https://graphql.org/learn/queries/) to make sure your data "subfield" always has the same name...

**Comment by sungam3r** [comment]
> The only way that I can do that, is if I reference the field

No, not only. As @rose-a said just cast to `JObject`.

**Comment by Dmo16** [comment]
Thanks @sungam3r and @rose-a, I will investigate these solutions and report back as soon as I can.

**Comment by Dmo16** [comment]
@rose-a 

I used your second suggestion of aliasing my GraphQL queries so that they were consistent on return. This ended up solving my issue.

I'm now able to pass whatever objects I want to my generic GraphQL query method and because they all return with the subfield I alias the queries as, I can use the method dynamically.

Thank you both for your patience. I'm still pretty new at a lot of this stuff so, often times I don't explain myself correctly.
