### ISSUE TITLE
Release v2.0.0-alpha.3

### ISSUE THREAD

**Issue by brtchr** [graphql-dotnet/graphql-client#144]
Any plans for a new alpha release with HTTPClient support?

**Comment by plemanach** [comment]
Any plan for the release?

**Comment by henningms** [comment]
Is this project being (actively) worked on / maintained?

**Comment by sungam3r** [comment]
It seems not so. In my projects, I switched to using my own client.

**Comment by chelliwell** [comment]
I've also been watching this project, but I need support for subscriptions (still a work-in-progress branch here).
So instead I am currently developing my client apps with https://github.com/sahb1239/SAHB.GraphQLClient. Have been flushing out a few bugs/enhancements in recent months, but it seems more active. (Bear in mind that the maintainer is doing it in his own free time)

**Comment by sungam3r** [comment]
I have seen https://github.com/sahb1239/SAHB.GraphQLClient but switched in favor of my own CSharp generator. The work on generators is in progress and tracked in graphql-dotnet/graphql-dotnet#1424

**Comment by plemanach** [comment]
is there a way to get this project moving ? could we add a new maintainer for this project ?

**Comment by sungam3r** [comment]
In fairness, it should be noted that the project is quite small (http wrapper) and you can simply copy it into your project and use with your fixes.

**Comment by rose-a** [comment]
closing this in favor of #108
