### ISSUE TITLE
StartAsync method in GraphQLHttpSubscriptionResult should not be `async void`

### ISSUE THREAD

**Issue by Drutol** [graphql-dotnet/graphql-client#145]
Hello,

I've been playing with subscriptions and I have run into this issue. It prevents from capturing exceptions that may be raised by the connection like for example server disconnection. _Without workarounds at least_, but overall `async void` should be avoided.

It applies to version `2.0.0-alpha.3` at least, I can't find the code for this version on github unfortunately.

**Comment by rose-a** [comment]
obsolete API, will not be part of v2.0.0
