### ISSUE TITLE
Mutation is not working

### ISSUE THREAD

**Issue by YannickSilva** [graphql-dotnet/graphql-client#149]
Hi i have a problem, every time i'm trying to proceed a mutation it returns **Cannot perform runtime binding on a null reference** , only query are working. How to solve this or this package only allow us to query and not mutate ?

**Comment by rose-a** [comment]
which version of the package are you using? Please use the latest alpha (2.0.0-alpha.3)

**Comment by YannickSilva** [comment]
I'm using version 1.0.3 i will try to use the version you recommended

**Comment by YannickSilva** [comment]
I'm on nuget already and the only avaible version is 1.0.3

**Comment by rose-a** [comment]
https://www.nuget.org/packages/GraphQL.Client/2.0.0-alpha.3

**Comment by YannickSilva** [comment]
I'm already using alpha version, but i receive a message that graphqlclient is obsolete what i'nm supose to do ?

**Comment by rose-a** [comment]
![grafik](https://user-images.githubusercontent.com/15836594/73636975-7531df80-4667-11ea-824b-8395b68ffeb2.png)

**Comment by YannickSilva** [comment]
Sorry for always bother you, can you send me an example of a mutation of your code can be a simple one, i am having an issue saying **GraphQL.Client.Http.GraphQLHttpException: 'Unexpected HttpResponseMessage with code: InternalServerError'**

**Comment by rose-a** [comment]
https://github.com/graphql-dotnet/graphql-client/blob/subscriptions-api/tests/GraphQL.Integration.Tests/GraphQLClientExtensions.cs#L11

**Comment by YannickSilva** [comment]
Same thing bro, is not working

**Comment by rose-a** [comment]
Since "InternalServerError" is a **server error**, you might wanna check your server. Maybe you're pointing to an invalid endpoint?

**Comment by YannickSilva** [comment]
Is not my server problem, i just query something and it works, but when i try to mutation it gives back that message i told you. I'm going to show you a screenshot of my Query and other of my mutation, so you can take a look

**Comment by YannickSilva** [comment]
![Query](https://user-images.githubusercontent.com/25250749/73640040-dc529280-466d-11ea-97f3-8217bc137fb3.png)

This my query and it works

**Comment by YannickSilva** [comment]
![Mutation](https://user-images.githubusercontent.com/25250749/73640089-f7250700-466d-11ea-9028-009bfb061404.png)

This is my mutation but it always give a http message error

**Comment by YannickSilva** [comment]
I created Graphql api with express and mongodb and tested it with postman, and it is working fine the same with GrapiQL

**Comment by rose-a** [comment]
There is nothing wrong with your code.

Please **DO** check your server and what exactly causes the internal error (malformed query, bad variables, bad variable serialization, an actual *internal error* while processing your mutation, ...). 

Mutations do work with this library! If you take a look at the source code you'll realize the method `SendMutation` is really just an alias for `SendQuery` (it uses exactly the same methods under the hood and does nothing special).

**Comment by YannickSilva** [comment]
I tried again and it worked, thanks for your help and patience with me
