### ISSUE TITLE
OperationName and Variables Request example in Readme not usable

### ISSUE THREAD

**Issue by LittleColin** [graphql-dotnet/graphql-client#15]
Returns two errors:

- Unknown type "Episode".
- Cannot query field "hero" on type "Root". Did you mean "person"?

**Comment by joemcbride** [comment]
You will need to change those to be specific to your Schema.  Are you using a specific example?

**Comment by deinok** [comment]
Yes, you are right the schema of https://swapi.apis.guru/ its not the same of http://graphql.org/learn/

Its only an orientative example. Further documentation will be done ;)

**Comment by LittleColin** [comment]
Cool - looking forward to how this library progresses. As a newcomer to GraphQL I found it difficult to see how the Variable values were being substituted into the query and tried to run it against swapi myself. Is $episode replaced by "JEDI" in your example and does that make a valid graphQL query in the following?

> query HeroNameAndFriends($episode: Episode) {
>       hero(episode: $episode) {

**Comment by deinok** [comment]
yes the equivalent without variables it's:
```graphql
query HeroNameAndFriends{
    hero(episode: "JEDI") {
        name
        friends {
            name
        }
    }
}
```

I recommend you to take a look at:
1. http://graphql.org/learn/ - Introduction to the GraphQL
2. http://facebook.github.io/graphql/October2016/ - The GraphQL Specification (Harder to understand)
