### ISSUE TITLE
Authorization token is not working, how to solve this issue

### ISSUE THREAD

**Issue by YannickSilva** [graphql-dotnet/graphql-client#154]
I have been trying to send an authorization token in my api, and every time i try to pass that my app crash. Have any one passed through this before ?

Code Example:

 **GraphQLHttpClient graphQLClient = new GraphQLHttpClient("http://***********/graphql");**

**graphQLClient.DefaultRequestHeaders.Add("Authorization", $"bearer {Token}");**

**Comment by rose-a** [comment]
Try it like this: https://stackoverflow.com/questions/14627399/setting-authorization-header-of-httpclient/32691285

**Comment by YannickSilva** [comment]
Thanks, i solved this, but now i'm having another error, i want to fetch a single post by id but every time i send it it says user not found, i tested in postman and graphiQL is working fine but on Xamari it says user not found, i'm sending the ID as a string
