### ISSUE TITLE
How get arrays of value in field name

### ISSUE THREAD

**Issue by YannickSilva** [graphql-dotnet/graphql-client#158]
Hey a have a query like This:

**getPosts
    {
        posts
        {
            _id
            title
            imageUrl
            creator
            {
                _id
                name
            }
            createdAt
        }
    }**

How i am supposed to do **var Sucess = graphQLResponse.GetDataFieldAs<PostModel>("getPosts{posts}");**

I am trying but everything goes wrong

**Comment by rose-a** [comment]
Please use the most recent version of the library (2.0.0)
