### ISSUE TITLE
base/supporting HttpClient class

### ISSUE THREAD

**Issue by emceelovin** [graphql-dotnet/graphql-client#159]
is GraphQLClient based off System.Net.HttpClient? im asking because im aiming for http pooling support, and System.Net.HttpClient supports that by default.

**Comment by rose-a** [comment]
![grafik](https://user-images.githubusercontent.com/15836594/74108899-d9303880-4b7e-11ea-8cc9-2a6fd29ed1d0.png)

**Comment by emceelovin** [comment]
very good. thank you!
