### ISSUE TITLE
Broken example?

### ISSUE THREAD

**Issue by stackunderflows** [graphql-dotnet/graphql-client#162]
I updated to the latest version of the nuget and now I'm getting an error that GraphQLClient doesn't exist. If it was removed, can you update the sample in the readme to reflect this? If it was moved, where?

**Comment by rose-a** [comment]
The example is wrong, use `GraphQLHttpClient` instead...

**Comment by stackunderflows** [comment]
I tried to flip my working code to use `GraphQLHttpClient` but I'm not getting any data and no exception either. Is there something wrong with this code? 

            var request = new GraphQLRequest()
            {
                Query = @"query
	            GetAllUsers {
                  getUsers {
                      items {
                          id
                          name
                          wifiModel
                      }
                      nextToken
                  }
                }"
            };

            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Add("Authorization", token);
            GraphQLHttpClientOptions options = new GraphQLHttpClientOptions()
            {
                EndPoint = new Uri(url)
            };

            var graphClient = new GraphQL.Client.Http.GraphQLHttpClient(options, client);
            
            var foo = await graphClient.SendQueryAsync<RootObject>(request);
