### ISSUE TITLE
RowVersion not working with GraphQl Client

### ISSUE THREAD

**Issue by noufionline** [graphql-dotnet/graphql-client#163]
When I try to use byte[] (Timestamp column) its throws the following exception.

GraphQL.ExecutionError: Input string was not in a correct format.
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Byte.Parse(String s, IFormatProvider provider)
   at GraphQL.ValueConverter.<>c.<.cctor>b__1_1(Object value)
   at GraphQL.Types.ByteGraphType.ParseValue(Object value)
   at GraphQL.Execution.ExecutionHelper.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)
   at GraphQL.Execution.ExecutionHelper.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)
   at GraphQL.Execution.ExecutionHelper.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)
   at GraphQL.Execution.ExecutionHelper.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)
   at GraphQL.Execution.ExecutionHelper.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)
   at GraphQL.Execution.ExecutionHelper.AssertValidValue(ISchema schema, IGraphType type, Object input, String fieldName)
   at GraphQL.Execution.ExecutionHelper.GetVariableValue(Document document, ISchema schema, VariableDefinition variable, Object input)
   at GraphQL.Execution.ExecutionHelper.GetVariableValues(Document document, ISchema schema, VariableDefinitions variableDefinitions, Inputs inputs)
   at GraphQL.DocumentExecuter.BuildExecutionContext(ISchema schema, Object root, Document document, Operation operation, Inputs inputs, IDictionary`2 userContext, CancellationToken cancellationToken, Metrics metrics, IEnumerable`1 listeners, Boolean throwOnUnhandledException, Action`1 unhandledExceptionDelegate, Nullable`1 maxParallelExecutionCount)
   at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options)
   --- End of inner exception stack trace ---

**Comment by noufionline** [comment]
@sungam3r

I have already opened an issue related to this. 

Input type with RowVersion is not working (#1534)

From the client side I am facing issue.

**Comment by rose-a** [comment]
So basically the server complains about a bad input variable... can you verify what's coming in on the server side and compare that to what you'd expect?

**Comment by noufionline** [comment]
While using the graphql UI List<object> is received but from the client the server receives 64bit string

**Comment by rose-a** [comment]
I guess the easy workaround would be converting the byte array to a list on the client before sending it.

I'm not yet sure if it would be a good idea to alter the serialization of all bytearrays...

**Comment by rose-a** [comment]
What are you trying to submit using that bytearray? Maybe another representation would be better suited?

**Comment by noufionline** [comment]
@rose-a 
I am updating Lookup Items in SQL Server database. Each table contains a TimeStamp column which keeps track of change tracking (Concurrency). In C# Timestamp columns are represented as byte[].

**Comment by sungam3r** [comment]
> I have already opened an issue related to this. Input type with RowVersion is not working (#1534) 
From the client side I am facing issue.

My first comment was https://github.com/graphql-dotnet/graphql-dotnet/issues/1534#issuecomment-585780624 . It would save us a lot of time.

**Comment by rose-a** [comment]
Ok, IMO you should not use a "bytearray" type to convey this information. The natural way would be using a `DateTimeGraphType` on your API and convert this in C#. Alternatively use a `long` if you just want to have an opaque timestamp on your API.

You should avoid *binary* fields in your API.

**Comment by sungam3r** [comment]
> While using the graphql UI List is received but from the client the server receives 64bit string

@rose-a If so, I think you should think about how to serialize byte arrays. After all, you do not serialize arrays of strings or other types (ints) like base64 string? Right?

**Comment by rose-a** [comment]
@sungam3r https://discuss.jsonapi.org/t/handling-binary-data/315

**Comment by sungam3r** [comment]
> You should avoid binary fields in your API.

In principle, I agree. But I was interested in another question. Do I understand correctly that the serialization format of `int[]` and `byte[]` is very different?

**Comment by rose-a** [comment]
Yes it is, but `byte[]` can either represent "a list of bytes", but in most cases is indeed binary data, as it is in @noufionline's case.

Converting the bytearray to a `List<byte>` would clearly express the intend to send a "list of bytes" instead of binary data and will most likely automatically result in the desired output from the JSON serializer.

**Comment by noufionline** [comment]
![GraphQL byte array error](https://user-images.githubusercontent.com/13216154/74603268-27878f00-50cb-11ea-9e1d-8931f1af633e.png)

Please find some graphics to get a better idea of my issue

**Comment by sungam3r** [comment]
> @sungam3r https://discuss.jsonapi.org/t/handling-binary-data/315

I look from the other side. The server declares the schema. This schema has a field with input argument of type `[Byte!]`. It is a **array** of some custom scalar named `Byte`. If the server declared field of type `Bytes` or `Binary` or something else **but not array**, then a discussion about the format would still make sense. Now the graphql-client just violates the server API.

**Comment by rose-a** [comment]
@noufionline As I already said, create your variables object like so:

```csharp
Variables = new { Lookup = item.ToList() }
```

This will tell the JSON serializer that you want to send a list of bytes!

**Comment by noufionline** [comment]
@rose-a 
Let me try your approach. I will come back soon with the results.

**Comment by sungam3r** [comment]
> This will tell the JSON serializer that you want to send a list of bytes!

Excellent! I was sure that you have some conventions to set up the serialization process.

**Comment by sungam3r** [comment]
If this is not yet mentioned in the readme, then this is a good reason to add it there.

**Comment by rose-a** [comment]
@sungam3r Even the GraphQL guys define `[Byte!]` as a [List](https://spec.graphql.org/June2018/#sec-Type-System.List) (sorry for the nitpicking :wink:).

**Comment by noufionline** [comment]
@rose-a 
Your approach worked like a charm!. Thanks a lot.

@sungam3r 
Thanks a lot for your help. Sorry for all the confusions as well.

**Comment by kdawg1406** [comment]
@noufionline would you be able to share your solution to this problem?  I'm having the same issue, but it is difficult trying to piece together what works from this and other threads.

Thank you very much!!

Karl
