### ISSUE TITLE
Delete package "GraphQL.Client.Http" from GitHub Packages

### ISSUE THREAD

**Issue by rose-a** [graphql-dotnet/graphql-client#165]
The package [GraphQL.Client.Http](https://github.com/graphql-dotnet/graphql-client/packages/120660) should be completely removed from GitHub Packages.

Since the packages in this repository are owned by the [graphql-dotnet](https://github.com/graphql-dotnet) organization, a organization-member needs to do that! @joemcbride @deinok

**Comment by rose-a** [comment]
Pinging graphql-dotnet members again...
@deinok @joemcbride @johnrutherford @SimonCropp @mkmarek @moserware

**Comment by rose-a** [comment]
Bump!!!

**Comment by deinok** [comment]
https://help.github.com/en/packages/publishing-and-managing-packages/deleting-a-package#about-public-package-deletion

**Comment by rose-a** [comment]
Sorry, I already found that help article....

But as I said, I've got no permission to do that!

![grafik](https://user-images.githubusercontent.com/15836594/78469905-89589280-7725-11ea-8649-47bd11d255e7.png)

**Comment by deinok** [comment]
I also can't, because they are public. Its not related to ownership

**Comment by rose-a** [comment]
Ah...my oversight.... sorry
