### ISSUE TITLE
Docs and samples point to Hero query that doesn't exist in the schema

### ISSUE THREAD

**Issue by codepoet80** [graphql-dotnet/graphql-client#166]
The query shown in Readme:
{
hero {
		name
	}
}

Results in the error:
{
  "errors": [
    {
      "message": "Cannot query field \"hero\" on type \"Root\". Did you mean \"person\"?",
      "locations": [
        {
          "line": 29,
          "column": 3
        }
      ]
    }
  ]
}

**Comment by rose-a** [comment]
Fixed in 292e7c6edecb9032c6ceb3f00345ed84fc6051e9
