### ISSUE TITLE
JSON error when trying to hit GitHub GraphQL API

### ISSUE THREAD

**Issue by patridge** [graphql-dotnet/graphql-client#17]
I'm trying to do a [GitHub API sample request](https://developer.github.com/v4/guides/forming-calls/#communicating-with-graphql) in code that I have already done with curl. Unfortunately, my requests all fail with a JSON exception. Since I've only been trying to work with GraphQL for about a day, it's very likely I am screwing up something very obvious, but I've narrowed it down to a success/fail situation that only differs by the API endpoint.

If I call `GetIntrospectionQueryAsync` on `https://swapi.apis.guru/`, everything appears to work fine. As soon as I change that URL to `https://api.github.com/graphql`, it throws the following exception when executing `GetIntrospectionQueryAsync`. (Here is my repro solution [GraphQLFailRepro.zip](https://github.com/graphql-dotnet/graphql-client/files/1656490/GraphQLFailRepro.zip).)

```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: R. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at GraphQL.Client.GraphQLClient.<ReadHttpResponseMessageAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GraphQL.Client.GraphQLClient.<GetAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GraphQL.Client.GraphQLClientExtensions.<GetIntrospectionQueryAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GraphQLFailRepro.Program.<AttemptGitHubIntrospection>d__1.MoveNext() in /Users/…/Projects/GraphQLFailRepro/GraphQLFailRepro/Program.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GraphQLFailRepro.Program.<Main>d__3.MoveNext() in /Users/…/Projects/GraphQLFailRepro/GraphQLFailRepro/Program.cs:line 53
```

**Comment by deinok** [comment]
I will take a look and try to reproduce ASAP ;)

**Comment by patridge** [comment]
Not that it _should_ matter too much, but that attached repro solution ZIP was a .NET Core 2.0 console app originally created in Visual Studio for Mac [v7.3.3].

**Comment by deinok** [comment]
Okey, I have taked a look. And found some interesting things:

- GitHub GraphQL only accepts POST (Except Introspection Methods) (End of https://developer.github.com/v4/guides/intro-to-graphql/#discovering-the-graphql-api)
- GitHub GraphQL in case of unauthentication don't give access to anything with a 401 Code
- GitHub GraphQL seems like any GET action will trigger an introspection query (Even if no query is sended).
- GitHub GraphQL seems to ask an User-Agent Header in some cases.


So, my recomendation for now is use POST based methods.

Even, im gona try to fix this error, atleast giving more information.

**Comment by patridge** [comment]
Thank you for looking into it. I was seeing a lot of those same points.

I have definitely been able to send the GET introspection and POST query requests with an auth header via other tools without a user agent, but if you see something they are expecting there, I'll give it a try.

**Comment by deinok** [comment]
Np, this weekend I probably release v1.0.1 in order to fix this little issues that have been discovered with GitHub API.

**Comment by deinok** [comment]
@patridge v1.0.1 released
This do the following.
If the HttpCode is no 2XX and the body cannot be parsed to a GraphQLResponse it will throw an exception with the HttpResponseMessage.
So it would be more easy to debug.

**Comment by patridge** [comment]
Well, I'm getting a Forbidden out of the API that doesn't seem to make sense. When I make the same request, with the same bearer-token authentication header, it works fine via the Postman and Insomnia tools.

> GraphQL.Client.Exceptions.GraphQLHttpException: Unexpected HttpResponseMessage with code: Forbidden
>   at GraphQL.Client.GraphQLClient.<ReadHttpResponseMessageAsync>d__20.MoveNext()

On the off chance the default headers system didn't work, I even tried a custom HttpMessageHandler that did nothing but set up the Authorization header: same "Forbidden" exception result.

I'm currently trying (and failing) to set up a proxy to see if I can intercept the entire request in an easier-to-read form. So far, it's not intercepting the request coming from Insomnia or dotnet.

**Comment by patridge** [comment]
Here's most of the relevant code that's failing, if it helps.

```csharp
var graphClient = new GraphQLClient("https://api.github.com/graphql");
graphClient.DefaultRequestHeaders.Add("Authorization", $"bearer {gitHubAccessToken}");
//var test = await graphClient.GetIntrospectionQueryAsync();
var request = new GraphQLRequest
{
    Query = @"query { viewer { login } }"
};
var test = await graphClient.PostAsync(request);
```

**Comment by deinok** [comment]
```
var graphClient = new GraphQLClient("https://api.github.com/graphql");
graphClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {gitHubAccessToken}");
graphClient.DefaultRequestHeaders.Add("User-Agent", "deinok");
var request = new GraphQLRequest {
	Query = @"query { viewer { login } }"
};
var test = await graphClient.PostAsync(request).ConfigureAwait(false);
```

See that im adding the User-Agent my user. Thats the only error :)
Any User-Agent should work but the recomendation its add your username

**Comment by patridge** [comment]
Wow! I'm feeling pretty stupid about that mistake. Thank you! All the prior GitHub clients I've used (pre-GraphQL stuff) have had me set the [`ProductHeaderValue` which translates to a user-agent](https://github.com/octokit/octokit.net/blob/master/Octokit/Http/ProductHeaderValue.cs#L4). All I can guess is that Insomnia set a user-agent for me that let it pass.

Thanks again for helping me nail that down!

**Comment by deinok** [comment]
Np, to be honest, i spend a lot of time debugging this hahaha
Its not the expected behaviour of an HttpServer to refuse if no User-Agent is set

**Comment by akash-geon** [comment]
Hi @deinok 

I wrote a .Net Core console application which queries a GraphQL endpoint and indexes that data to elastic search.
The code used for querying the graphQL endpoint is 
`using (var client = new GraphQLClient(_graphQLConfig.GraphQLUrl))
{
    try
    {
        var graphQLResponse = client.PostAsync(request).GetAwaiter().GetResult();
        if (graphQLResponse.Errors != null)
            throw new GraphQLException(graphQLResponse.Errors.First());
        return graphQLResponse;
    }
    catch(GraphQLException ex)
    {
        throw ex;
    }
    catch (Exception ex)
    {
        throw ex;
    }
}`

But whenever I hit non-existence endpoint, I am getting a Newtonsoft.Json.JsonSerializationException exception
`Error converting value 404 to type 'GraphQL.Common.Response.GraphQLResponse'. Path '', line 1, position 3.`

The stack trace is
`   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 989
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 167
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) in /_/Src/Newtonsoft.Json/JsonSerializer.cs:line 907
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader) in /_/Src/Newtonsoft.Json/JsonSerializer.cs:line 873
   at GraphQL.Client.GraphQLClient.ReadHttpResponseMessageAsync(HttpResponseMessage httpResponseMessage)
   at GraphQL.Client.GraphQLClient.PostAsync(GraphQLRequest request, CancellationToken cancellationToken)`

But on an earlier reply, you have mentioned that the client will throw an HttpResponseMessage exception.
Can you suggest why an HttpResponseMessage exception?

> @patridge v1.0.1 released
> This do the following.
> If the HttpCode is no 2XX and the body cannot be parsed to a GraphQLResponse it will throw an exception with the HttpResponseMessage.
> So it would be more easy to debug.
> 
> Reopen this if you cannot debug or found another error

**Comment by cerojasg** [comment]
> ```
> var graphClient = new GraphQLClient("https://api.github.com/graphql");
> graphClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {gitHubAccessToken}");
> graphClient.DefaultRequestHeaders.Add("User-Agent", "deinok");
> var request = new GraphQLRequest {
> 	Query = @"query { viewer { login } }"
> };
> var test = await graphClient.PostAsync(request).ConfigureAwait(false);
> ```
> 
> See that im adding the User-Agent my user. Thats the only error :)
> Any User-Agent should work but the recomendation its add your username

Thanks very much! i was crazy with this error. God....

**Comment by keithdoherty** [comment]
@akash-geon did you ever figure out that error? I am seeing the same error myself.
