### ISSUE TITLE
Unhandled exception. System.InvalidOperationException: no implementation of "GraphQL.Client.Abstractions.Websocket.IGraphQLWebsocketJsonSerializer" found

### ISSUE THREAD

**Issue by pysiak** [graphql-dotnet/graphql-client#171]
Crazy! Before the weekend this:
```GraphQLHttpClient gql = new GraphQLHttpClient(_config["API:Endpoint"]);```
worked for me. Now I'm getting this:
```
Unhandled exception. System.InvalidOperationException: no implementation of "GraphQL.Client.Abstractions.Websocket.IGraphQLWebsocketJsonSerializer" found
   at GraphQL.Client.Abstractions.GraphQLJsonSerializerExtensions.EnsureAssigned[TSerializerInterface](TSerializerInterface jsonSerializer)
   at GraphQL.Client.Http.GraphQLHttpClient..ctor(GraphQLHttpClientOptions options, HttpClient httpClient)
   at GraphQL.Client.Http.GraphQLHttpClient..ctor(GraphQLHttpClientOptions options)
   at GraphQL.Client.Http.GraphQLHttpClient..ctor(Action`1 configure)
   at GraphQL.Client.Http.GraphQLHttpClient..ctor(Uri endPoint)
   at GraphQL.Client.Http.GraphQLHttpClient..ctor(String endPoint)
   at ConsoleApp1.Program.GetCourses() in C:\...
   at ConsoleApp1.Program.Main(String[] args) in C:\...
   at ConsoleApp1.Program.<Main>(String[] args)
```

I tried: restoring packages, uninstalling and installing. Any ideas?

**Comment by rose-a** [comment]
Ran into this myself, will be fixed in next release (292e7c6edecb9032c6ceb3f00345ed84fc6051e9)...

In the meantime please configure the JSON serializer manually, i.e.

```csharp
GraphQLHttpClient gql = new GraphQLHttpClient(o => {
    o.EndPoint = _config["API:Endpoint"];
    o.JsonSerializer = new NewtonsoftJsonSerializer();
});
```

**Comment by pysiak** [comment]
Thanks, your fix worked. I just realized the last thing I did on Friday was to upgrade from 2.0.0 to 2.1.0.
This seems to break the previous invocation.

**Comment by rose-a** [comment]
> I just realized the last thing I did on Friday was to upgrade from 2.0.0 to 2.1.0.
This seems to break the previous invocation.

Yep, the serializers were moved to separate packages in 2.1.0, I tried to implement a fallback, which is obviously borked at the moment 😉

**Comment by pysiak** [comment]
I see. I'll stick with 2.1.0 as I'm good now, thanks!

**Comment by clintmasden** [comment]
Ran into this today. Thanks for the 2.1 fix @rose-a.

**Comment by rose-a** [comment]
fixed in v2.1.2

**Comment by JensMeire** [comment]
Installed the 3.0.0 today and i encountered this issue

**Comment by rose-a** [comment]
the exception says *no implementation of "GraphQL.Client.Abstractions.Websocket.IGraphQLWebsocketJsonSerializer" found*, so please provide the one you prefer out of the two!

Which constructor are you using?

**Comment by JensMeire** [comment]
Oh, ok, my bad. 
Didn't read the notes (fresh install), thought the bug could crawled back into the new release :)

**Comment by rose-a** [comment]
I guess the exception message should be reworded...

**Comment by DayZeroLLC** [comment]
For those coming here from google searches, working on a new project using something along the lines of 
var graphQLClient = new GraphQLHttpClient("https://api.example.com/graphql", new NewtonsoftJsonSerializer());

Ensure
1. nuget reference to GraphQL.Client.Serializer.Newtonsoft
2. using GraphQL.Client.Serializer.Newtonsoft;
