### ISSUE TITLE
Subscribe with Authentication is not working for me

### ISSUE THREAD

**Issue by ClarenceMG** [graphql-dotnet/graphql-client#172]
```csharp
var options = new GraphQLHttpClientOptions
{
     EndPoint = new Uri(APIUrl)
};

var httpClient = new HttpClient();
httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

var graphQLHttpClient = new GraphQLHttpClient(options, httpClient, new GraphQL.Client.Serializer.Newtonsoft.NewtonsoftJsonSerializer()); 
```

This is my client.

Now I try to subscribe:

```csharp
IObservable<GraphQLResponse<object>> subscriptionStream = graphQLHttpClient.CreateSubscriptionStream<object>(request);

IDisposable subscription = subscriptionStream.Subscribe(response =>
{
    var value = response.Data;
    if (response.Data != null)
    {
        var serializeResponse = JsonConvert.SerializeObject(response);
        Console.WriteLine(serializeResponse);
    }
});
```

But I never receive a response.

**Comment by ClarenceMG** [comment]
` IDisposable subscription = subscriptionStream.Subscribe(response =>
        {
            var value = response.Data;

            if (response.Data != null)
            {
                var serializeResponse = JsonConvert.SerializeObject(response);

                Console.WriteLine(serializeResponse);
            }
        });`

After subscribe it I receive a response null.

**Comment by rose-a** [comment]
What exactly is null? `response` itself should never be null... If `response.Data` is null, `response.Error` will most likely contain the error stating the cause for that (which in your case could be something like "not authorized").

As on authorization via websockets, this is no easy topic. I'm quite curious on how this is implemented in your server (please let me know).

A websocket only sends HTTP headers once with the request to upgrade the HTTP connection to a websocket. Then you can send as many requests as you like via that websocket without ever sending that header again (how do you replace your token when it expires?).

This library opens a single websocket and reuses that as long as it can be kept open. If you set `GraphQLHttpClientOptions.UseWebSocketForQueriesAndMutations` to `true` it also sends queries and mutations over that connection (which reduces overhead).

In my own personal projects im using a PR build of [graphql-dotnet/server](https://github.com/graphql-dotnet/server/pull/208) which adds a `authorization` field to every request payload to be evaluated on a per request basis by the server, which works perfectly fine. To achieve that on the client side you'd have to reimplement one of the JSON serializer packages to include a authorization field in their internal [GraphQLRequest object](https://github.com/graphql-dotnet/graphql-client/blob/develop/src/GraphQL.Client.Serializer.Newtonsoft/GraphQLRequest.cs)...

As for the server it obviously depends on the implementation you're using...

**Comment by ClarenceMG** [comment]
Immediately after subscribe me I receive a response with `Data = Null`, `Errors = Null` and `Extensions = Null`.

It could great if you provide us an example of how you implement this library.
Thank you.

**Comment by rose-a** [comment]
There is an [example](https://github.com/graphql-dotnet/graphql-client#create-subscription) in the readme. You can find [further examples](https://github.com/graphql-dotnet/graphql-client/blob/develop/tests/GraphQL.Integration.Tests/WebsocketTests/Base.cs) inside the integration test project, although they're a bit obfuscated by test helpers and extension methods.

Show us your query string and request object, would you?

Also you shouldn't use `object` as `TResponse`. Either model a class for your response as shown in the readme or use the extension which accepts an anonymous type as an argument (see [here](https://github.com/graphql-dotnet/graphql-client/blob/develop/tests/GraphQL.Integration.Tests/QueryAndMutationTests/Base.cs#L33), a equivalent extension method exists for `CreateSubscriptionStream` too).

**Comment by ClarenceMG** [comment]
This is my query:
```
subscription {
      activityAdded {
         reconditioningActivityId
         description
         isDefault
         requireApproval
         approvers
     }
}
```

This is my object:
```csharp
public class ActivityAdded
{
     public string ReconditioningActivityId { get; set; }
     public string Description { get; set; }
     public bool IsDefault { get; set; }
     public bool RequireApproval { get; set; }
     public string Approvers { get; set; }
}
```
I did tests and the server not receive the token, I don't know if I'm not adding fine my DefaultRequestHeaders. 

```csharp
var options = new GraphQLHttpClientOptions
{
       EndPoint = new Uri(APIURL)
};

var httpClient = new HttpClient();
httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", MYTOKEN);

if (graphQLHttpClient == null)
{
       graphQLHttpClient = new GraphQLHttpClient(options, httpClient);
}
```

```csharp
IObservable<GraphQLResponse<ActivityAdded>> subscriptionStream = graphQLHttpClient.CreateSubscriptionStream<ActivityAdded>(request);

IDisposable subscription = subscriptionStream.Subscribe(response =>
{
      if (response.Data != null)
      {
          var serializeResponse = JsonConvert.SerializeObject(response);

          dataChanged?.Invoke(serializeResponse);
      }
});
```

**Comment by ClarenceMG** [comment]
It should be noted that my server is running on ngrok. @rose-a

**Comment by ClarenceMG** [comment]
![Screen Shot 2020-02-25 at 7 50 52 PM](https://user-images.githubusercontent.com/19200610/75304203-5eb31a00-5808-11ea-8ad4-f67666dc6ad9.png)

**Comment by ClarenceMG** [comment]
My server always receive `context { }` empty.
Do you know why is happening this? @rose-a

**Comment by rose-a** [comment]
Yes, that happens because this client does not send any `context` field. 

What server library are u using? I suspect its apollo-server?

Currently there is no fixed specification on how to do authentication over websockets, and Apollo has from a quick glance decided to go for the "authenticate the websocket once on establishing the connection". 

I myself prefer the approach to add the authentication token to each query/mutation/subscription payload so you can check this on each request and be able to change it without destroying and reestablishing the websocket connection (since im using the websocket for queries/mutations too). How this can be done with graphql-dotnet was descibed in an [earlier answer](#issuecomment-590736653).

As I already said the implementation has to match that of the server. Feel free to locate and share the specification your server is using or even do a PR implementing it.

**Comment by ClarenceMG** [comment]
Ok, thank you very much, now I am clear.
Just a question.
Regarding security, do you think it is advisable to send the token in the payload?
@rose-a

**Comment by rose-a** [comment]
Well, regarding security it doesn't matter if you send it in the payload or in a http header (like it's usually done with normal web requests). 

You always need to encrypt your communication using https (or wss when websockets are concerned) when sending auth tokens around!

**Comment by ClarenceMG** [comment]
How do I add an extra field in the Payload?For example:
context: {
   authorization: "Bearer <token>"
}
I tried adding a field in GraphQLRequest editing the library but I cannot do it work.

@rose-a

**Comment by rose-a** [comment]
Currently you'll have to reimplement one of the serializers (because that uses a private implementation of `GraphQLRequest` in order to correctly set JSON property names)

**Comment by ClarenceMG** [comment]
Thank you so much @rose-a. 
I'm going to test it.

**Comment by binemecio** [comment]
Thank you @rose-a
