### ISSUE TITLE
authorization not working with subscriptions

### ISSUE THREAD

**Issue by binemecio** [graphql-dotnet/graphql-client#174]
The authorization for subscriptions does not work, however for queries and mutations it works fine.

Searching in some forums I found that authentication with websocket is different that https (headers do not work with websocket)

can you send me an example of how I could send authentication parameters to consume a subscription from your library?

**Comment by MysticFragilist** [comment]
Hey! I saw that your post were a lot related to this one [#172](https://github.com/graphql-dotnet/graphql-client/issues/172), I think @rose-a discuss about how you can achieve authorization around websocket and he link a sample project you could check out. Hope it helps!

**Comment by rose-a** [comment]
closing this in favour of #172
