### ISSUE TITLE
Unable to install package into VS2015 using NuGet

### ISSUE THREAD

**Issue by Topbox35** [graphql-dotnet/graphql-client#176]
Attempting to install the Graphql-client into a bare bones project targeting .net v4.6.1 generates an error related to the package not containingany assembly references or content that's compatible with that framwork. However, the quoted dependencies for the GraphQL client include this version of .net.

Please can you suggest a fix?

![InstallProblem](https://user-images.githubusercontent.com/12893428/75552278-e168ee80-5a2d-11ea-9536-e58af51c4acf.png)

**Comment by rose-a** [comment]
Weird, there is nothing in GraphQL.Client.Abstractions which has any incompatibilities with net461...

It's built for netstandard2.0 and only has a dependency on System.Reactive, which I have personally running in multiple net461 applications without problems....

**Comment by sungam3r** [comment]
@Topbox35 Does this only happen in 2015 version? Have you tried others?

**Comment by Topbox35** [comment]
@sungam3r I tried Visual Studio 2017 and everything worked fine, so on this basis it seems the problem is related to VS2015. Sorry not to reply sooner...I've been a little distracted with world pandemics.

**Comment by rose-a** [comment]
@Topbox35 Thanks for your further enquiries!

VS2015 seems to have issues with .Net Standard 2.0, see [this StackOverflow answer](https://stackoverflow.com/a/46803711).

I'm closing this issue, since its a Microsoft compatibility thing which only surfaces with an old IDE using an old .NET Framework version...
