### ISSUE TITLE
The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by qbolPoL** [graphql-dotnet/graphql-client#181]
I used version 1.0.3 and everything worked.

At some point the server changed (EndPoint changed). They claim that nothing but the address has changed, but now every time I try to connect I get an error:

HttpRequestException: The SSL connection could not be established, see inner exception.

I don't know what the reason may be.
I tried to switch to version 2.1.0, but the error is the same (I would prefer to stay on 1.0.3, because changing to 2.1.0 would require rewriting a large part of the program).

Using INSOMNIA and CURL gets a valid response, the problem is only using this code:

```
static void Main(string[] args)
        {
            MainAsync2().Wait();        
        }
       
        static async Task MainAsync2()
        {
            //string 
            var request1 = new GraphQLRequest
            {
                Query = @"
                     query {
                        getDistributorProductListing {                      
                            edges {
                                node {  
                                    id
                                    ean
                                    }
                                  }
                        }
                    }"
            };
        
      
            var graphQLClient = new GraphQLClient("https://Y/api/graphql/Z?apikey=X");
           

            var graphQLResponse = await graphQLClient.PostAsync(request1);
            var responseType = graphQLResponse.GetDataFieldAs<CreateDistributorProductResult>("getDistributorProductListing"); 

         
        }
```

EDIT1:
It's crashing on:   
var graphQLResponse = await graphQLClient.PostAsync(request1);

**Comment by rose-a** [comment]
v1 is no longer maintained! Please use the most recent version! 

What's in the inner exception?

**Comment by qbolPoL** [comment]
The SSL connection could not be established, see inner exception
Authentication failed, see inner exception
The message received was unexpected or badly formatted

I'm changing it now to 2.1.0, but the error is the same, I'm pretty sure, will confirm it in few minutes.

**Comment by rose-a** [comment]
Well, it says "Authentification failed"... You don't do anything authentication related in your snippet...

**Comment by qbolPoL** [comment]
I'm sending apikey in URL, it works for CURL and INSOMNIA, I don't need any more information then this to receive data.

I'm new at this, if I'm doing something dumb, just correct me.

**Comment by rose-a** [comment]
Does it work when you use  `https://` in your URL?

**Comment by qbolPoL** [comment]
Same error with https://

**Comment by rose-a** [comment]
Is the API you're trying to access a public one? If yes, please post a link to the spec, otherwise it's quite hard to help you... 

I don't think its an error within this lib (it just sends genuine http requests), and its obviously related to the changes that were made on the server side...

**Comment by qbolPoL** [comment]
Unfortunately, it's a private one.

I have a lead I think.
Can I turn off ,,Validate certificates" on my side?
INSOMNIA requested that changed, maybe that's the problem.

**Comment by rose-a** [comment]
Using "invalid" certificates (i.e. "self-signed") certainly needs explicit configuration in C#.

You can access the HttpClient used inside GraphQlHttpClient via the property `graphQLClient.HttpClient`, or alternatively configure the HttpClient and then pass it to GraphQlHttpClient via its constructor.

 Please check out the microsoft docs on how to enable the use of "invalid" certificates.
