### ISSUE TITLE
The new API only works in a Console app

### ISSUE THREAD

**Issue by Osukarin** [graphql-dotnet/graphql-client#186]
I am using GraphQL API for .NET for a web application. In this new version, I have implemented in my test Console Application, and it works ok. But when I pass the implementation to my Web App, it does not work, and it throws me a:

The thread 0x611c has exited with code 0 (0x0).

I have made a Web App in blank to test if it works there, but it gave me the same result before.

**Comment by rose-a** [comment]
> The thread 0x611c has exited with code 0 (0x0).

That's no exception, but rather default debug output....
