### ISSUE TITLE
Remove default JsonSerializer and require explicit configuration

### ISSUE THREAD

**Issue by joerneu** [graphql-dotnet/graphql-client#188]
This line always overwrites Option.JsonSerializer:

https://github.com/graphql-dotnet/graphql-client/blob/a72700006a0d5fb797bdc0d1d2bc0708556ebb09/src/GraphQL.Client/GraphQLHttpClient.cs#L57

Therefore the following code does not work as expected:

```
_client = new GraphQLHttpClient(o =>
{
    o.EndPoint = new Uri(_testUrl);
    o.JsonSerializer = new SystemTextJsonSerializer(
        options =>
        {
            options.Converters.Add(new JsonStringEnumConverter());
        });
});
```

The constructor above calls the constructor

https://github.com/graphql-dotnet/graphql-client/blob/a72700006a0d5fb797bdc0d1d2bc0708556ebb09/src/GraphQL.Client/GraphQLHttpClient.cs#L53

which sets the JsonSerializer always to `NewtonsoftJsonSerializer`.

By the way, I think it would be better to make a breaking change, remove the reference to `GraphQL.Client.Serializer.Newtonsoft` and require the caller to provide the serializer.

**Comment by sungam3r** [comment]
> By the way, I think it would be better to make a breaking change, remove the reference to GraphQL.Client.Serializer.Newtonsoft and require the caller to provide the serializer.

Agree.

**Comment by rose-a** [comment]
Yeah you're right, I guess there should be only one "source of truth"...
