### ISSUE TITLE
Mutation returning unexpected id

### ISSUE THREAD

**Issue by Krummelz** [graphql-dotnet/graphql-client#192]
I'm consuming the Monday.com Graph API.
I get a zero back in my response.Data.id field, when I expect to see some kind of integer instead (or the string version of it; I've tried both in my response class below).

My request setup is as follows:

```C#
public class ItemResponse
{
  public int id;
}


var itemMutationRequest = new GraphQLRequest()
{
  Query = @"
  mutation create_item($itemName:String!, $boardId:Int!, $groupId:String!)
  {
    create_item(item_name: $itemName, board_id: $boardId, group_id: $groupId) 
    {
      id
    }
  }",
  OperationName = "create_item",
  Variables = new
  {
    boardId = boardId,
    groupId = groupId,
    itemName = itemName
  }
};
```

So this gives me back a zero for my response id.
However, if I change the `id` property of `ResponseItem` to a string type, it comes back as null.

If I run this
```javascript
mutation {
    create_item(item_name:"test", board_id:391645430, group_id: "new_group86681"){
        id
    }
}
```
through [postwoman.io](https://postwoman.io/) then I get the following result:
```javascript
{
  "data": {
    "create_item": {
      "id": "418632259"
    }
  },
  "account_id": 337126
}
```

Even though I don't get a proper value back for my response id by using this graphql-client, the item is still created successfully, and there are no errors nor exceptions thrown. Is there something I'm missing here?

**Comment by rose-a** [comment]
Hm, that `account_id` field in the response is not allowed per GraphQL spec (see https://spec.graphql.org/June2018/#sec-Response-Format)... 

Please post the code where you actually send that `itemMutationRequest`! Might be the same mistake as here: https://github.com/graphql-dotnet/graphql-client/issues/193#issuecomment-601572195

**Comment by Krummelz** [comment]
Wow that's interesting! I'll see if I can reach out to their devs to let them know. 

Here is the full set of code from above:

```C#
public class ItemResponse
{
  public int id;
}

public class ItemService
{
  public Task<GraphQLResponse<ItemResponse>> CreateItem(string itemName, int boardId, string groupId)
  {
    var itemMutationRequest = new GraphQLRequest()
    {
      Query = @"
      mutation create_item($itemName:String!, $boardId:Int!, $groupId:String!)
      {
        create_item(item_name: $itemName, board_id: $boardId, group_id: $groupId) 
        {
          id
        }
      }",
      OperationName = "create_item",
      Variables = new
      {
        boardId = boardId,
        groupId = groupId,
        itemName = itemName
      }
    };

    var graphQLClient = new GraphQLHttpClient(MondayAPI.MONDAY_API);
    graphQLClient.HttpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue(MondayAPI.GetAPIKey);

    return graphQLClient.SendMutationAsync<ItemResponse>(itemMutationRequest);
  }
}
```

I call it from elsewhere as follows:

```C#
ItemService _itemService = new ItemService();
var response = await _itemService.CreateItem("test item", 391645430, "new_group86681");
```
With the above response I check `response.Data.id`, and it always comes back with a zero.

**Comment by rose-a** [comment]
yeah, you're missing the `create_item` object...

Your Response type should be something like this (reusing your `ItemResponse` class):

```csharp
public class CreateItemResponse 
{
    public ItemResponse Create_Item { get; set; }
}
```

Watch our for the property name, I'm not sure the serializers will manage to match the `create_item` field name to a `CreateItem` property... Either put the underscore in the property name like above or use GraphQL aliasing to give it a camel-case name...

**Comment by Krummelz** [comment]
Ahhhh that was such a silly mistake! 

Thanks for the help! I've made it work by changing my data stucture to the following:

```C#
public class Create_Item 
{
  public int id;
}
public class ItemResponse
{
  public Create_Item create_item;
}
```
