### ISSUE TITLE
Remove dependency on Newtonsoft.Json from GraphQL.Client

### ISSUE THREAD

**Issue by rose-a** [graphql-dotnet/graphql-client#201]
![grafik](https://user-images.githubusercontent.com/15836594/77321921-34735000-6d13-11ea-9ead-954f78c221d9.png)

**Comment by sungam3r** [comment]
Did you seem to remove this dependency?

**Comment by rose-a** [comment]
Yes, only the *GraphQL.Client.Serializer.Newtonsoft* package should be dependent on *Newtonsoft.Json*

**Comment by sungam3r** [comment]
That is, you forgot to remove the dependency from 3.0.0?

**Comment by rose-a** [comment]
Didn't have in mind that there was one...
