### ISSUE TITLE
Question about GraphQLHttpRequest.PreprocessHttpRequestMessage

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-client#209]
Why is it needed in `GraphQLHttpRequest` if there is already `GraphQLHttpClientOptions.PreprocessRequest`. Why not have both delegates in `GraphQLHttpClientOptions`? From my point of view it would be a more understandable design rather than mixing delegate inside DTO - GraphQLHttpRequest.

**Comment by rose-a** [comment]
This seems to be the "predecessor" of `GraphQLHttpClientOptions.PreprocessRequest`. 

The only difference makes is that you could do requests with different preprocessing methods, although I can't think of any use case where this would be needed....

So IMO `GraphQLHttpRequest.PreprocessHttpRequestMessage` can be completely eliminated.

**Comment by sungam3r** [comment]
`PreprocessRequest` works with `GraphQLRequest`, `PreprocessHttpRequestMessage` works with `HttpRequestMessage` - different abstraction levels.

> The only difference makes is that you could do requests with different preprocessing methods

True. Well, now I think this is actually useful, as it sets a convenient way to pass parameters without changing the method signature. For example, in this way you can set unique request headers that cannot be set in `DefaultRequestHeaders`. In general, I see asymmetries in the way headers work for request and response. Compare with `GraphQLHttpResponse<T>` : `GraphQLResponse<T>` where we have explicit `ResponseHeaders` property. Perhaps the initial thought was that the `GraphQLHttpRequest` has more initiative and ability to modify the request, so it can obtain the whole `HttpRequestMessage` object to do something with it. 

Need to think more.

**Comment by rose-a** [comment]
`GraphQLHttpRequest.PreprocessHttpRequestMessage` does not work when using a Websocket to send the requests, `GraphQLHttpClientOptions.PreprocessRequest` does...

**Comment by sungam3r** [comment]
Obviously since `GraphQLHttpClientOptions.PreprocessRequest` works with `GraphQLRequest` - DTO, not with `HttpRequestMessage`. I think if in general there is no explicit need for `GraphQLHttpRequest.PreprocessHttpRequestMessage`, then it is better to remove it to simplify design.

**Comment by rose-a** [comment]
#216 is a usecase for `GraphQLHttpRequest.PreprocessHttpRequestMessage`...

**Comment by sungam3r** [comment]
It makes sense.

**Comment by rose-a** [comment]
I assume #218 made this discussion obsolete?

**Comment by sungam3r** [comment]
Ok.
