### ISSUE TITLE
Clean up GraphQLSerializationExtensions.cs in GraphQL.Client

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-client#211]
I see such configuration in GraphQL.Client.csproj
```	
        <ItemGroup>
	  <Compile Remove="GraphQLSerializationExtensions.cs" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="GraphQLSerializationExtensions.cs" />
	</ItemGroup>
```

Is this a forgotten file? When enabled it does not compile.

**Comment by rose-a** [comment]
Seems that's where that Newtonsoft dependency came from (#201)...

Seems to be a leftover from moving the serialization into separate packages... shoud be cleaned up.
