### ISSUE TITLE
Update GitVersionTask when compatibility issue is fixed

### ISSUE THREAD

**Issue by rose-a** [graphql-dotnet/graphql-client#214]
There is a [compatibility issue](https://github.com/GitTools/GitVersion/issues/2063) with GitVersionTask in combination with MSBuild 16.5 and .NET Core 3.1.200, which prevents building the project.

The build in GitHub actions works because the version vars get injected via environment.

Must be updated as soon as the fix is released.

**Comment by sungam3r** [comment]
> The build in GitHub actions works because the version vars get injected via environment.

What version vars?

**Comment by rose-a** [comment]
The first job in the GitHub workflow generates the GitVersion info using `gitversion.tool` (see [here](https://github.com/graphql-dotnet/graphql-client/blob/f501e5da6f59d471da1f64200b398d9369611464/.github/workflows/branches-ubuntu.yml#L11)).

Those are saved as artifact and [injected into the build environment](https://github.com/graphql-dotnet/graphql-client/blob/f501e5da6f59d471da1f64200b398d9369611464/.github/workflows/branches-ubuntu.yml#L44) in the following jobs. 

This circumvents a concurrency problem in GitVersionTask by picking them up [here](https://github.com/graphql-dotnet/graphql-client/blob/f501e5da6f59d471da1f64200b398d9369611464/src/src.props#L18) and saves resources.
