### ISSUE TITLE
GraphQLResponse.Extensions not deserialised properly

### ISSUE THREAD

**Issue by PaulKlein** [graphql-dotnet/graphql-client#215]
I'm trying to include Apollo Tracing data in my responses, which gets included in the Extensions field of the GraphQLResponse object.

For example my query result returns data like in the apollo example at https://github.com/apollographql/apollo-tracing#example

When I look at the values in the extensions map, it doesn't seem to have deserialised the trace extension object correctly.

`extensions.tracing.parsing` and similar fields are fine, but `extensions.tracing.execution.resolvers` is always an empty array.

This seems to be a problem in `GraphQL.Client.Serializer.Newtonsoft.MapConverter.ReadArray`, because the items in the resolvers array are of type `JTokenType.Property` and are therefore skipped / ignored.

Is it possible to extend the deserialiser to support this structure of extension JSON?

**Comment by rose-a** [comment]
I'll have a look into it... 

From the example I don't get why the contents of an array should be of type `JTokenType.Property`, they are objects!

**Comment by PaulKlein** [comment]
I had a bit more of a look into it, and I think the problem is how it's iterating over the items in `ReadArray`.

I made a small fix that seems to resolve this and created as a pull request if you'd like to check it.

Thanks
