### ISSUE TITLE
Send as form-data with binairy file

### ISSUE THREAD

**Issue by LaurensVanAcker** [graphql-dotnet/graphql-client#216]
How can I use this library to send the data as form-data instead of application/json and add a file?
I want to implement this interface: https://developer.clearfacts.be/?shell#upload-a-sales-invoice-through-a-mutation

I have a Stream-object with the PDF-file and this:

```csharp
var uploadRequest = new GraphQLRequest {
    Query = @"
        mutation upload {
            vatnumber: $vat,
            filename: $name,
            invoicetype: $invoicetype
         }",
         OperationName = "upload",
             Variables = new {
                 name = filename,
                 vat = "1234",
                 invoicetype = "SALE"
             }
         };

var graphQLUploadResponse = await graphQLClient.SendMutationAsync<File>(uploadRequest);
```

**Comment by rose-a** [comment]
You can propably achieve this by using a `GraphQLHttpRequest` instead of a `GraphQLRequest` and then turn the resulting `HttpRequestMessage` inside out with the `GraphQLHttpRequest.PreprocessHttpRequestMessage` action...

Interesting usecase... please let me know if you are successful!

**Comment by rose-a** [comment]
Please check out v3.0.3, the code for generating the `HttpRequestMessage` has been moved into [GraphQLHttpRequest](https://github.com/graphql-dotnet/graphql-client/blob/29407e0d5b38f315333644d187d103cabed01822/src/GraphQL.Client/GraphQLHttpRequest.cs#L38).

By inheriting from this class and overriding the `ToHttpRequestMessage()` you have full control over the HTTP request... Should be easy to create a convenient `GraphQLHttpFormDataRequest` now...

**Comment by LaurensVanAcker** [comment]
Thanks! It works!

 ```csharp
internal class GraphQLHttpFormDataRequest : GraphQLHttpRequest {
    public Stream File { get; internal set; }
    public string Filename { get; internal set; }

    public override HttpRequestMessage ToHttpRequestMessage(GraphQLHttpClientOptions options, IGraphQLJsonSerializer serializer) {
    if (File is null)
        throw new ArgumentException(nameof(File));

    return new HttpRequestMessage(HttpMethod.Post, options.EndPoint) {
        Content = new MultipartFormDataContent("Upl----") {
            { new StringContent(Query), nameof(Query)},
            { new StringContent(JsonConvert.SerializeObject(Variables, NewtonsoftJsonSerializer.DefaultJsonSerializerSettings)), nameof(Variables)},
            { new StreamContent(File), Filename, Filename }
        }
    };
}
```
