### ISSUE TITLE
GraphQL HttpClient does not have correct logic for retries

### ISSUE THREAD

**Issue by RobinHSanner** [graphql-dotnet/graphql-client#217]
The GraphQL client does retries but it doesn't do them correctly, i.e. whether to retry or not depends on the returned status code.  For a NotFound and BadRequest both it just keeps retrying.

HttpStatusCodes that might benefit from retries might include:
RequestTimeout, TooManyRequests, ServiceUnavailable, GatewayTimeout

**Comment by rose-a** [comment]
Are you using websockets?

**Comment by RobinHSanner** [comment]
No websockets, HttpClient

**Comment by RobinHSanner** [comment]
And I watch it in the output window try over and over

**Comment by rose-a** [comment]
There is no "retry logic" inside this library when sending GraphQL requests vial plain HTTP (not using Websockets).

Feel free to review the code yourself.

**Comment by sungam3r** [comment]
Maybe it is debugger behavior? I sometimes observed this.
