### ISSUE TITLE
Inconsistent MapConverter array return values between NewtonSoft and SystemText Json Serializers

### ISSUE THREAD

**Issue by BillBaird** [graphql-dotnet/graphql-client#223]
If a GraphQL errors collection contains extensions where a map value is an array, the NewtonSoft MapConverter returns an `IEnumerable<object>`, where the SystemTextJson MapConverter returns a `List<object>`.  These should both work the same way.

While both MapConverter implementations of ReadArray() return an `IEnumerable<object>`, the calling methods differ in that the NewtonSoft implementation of ReadToken simply passes the IEnumerable along, while the SystemTextJson implementation of ReadValue calls ToList() on the result of ReadArray().

I suggest these behave consistently (I would vote for adding ToList() to the NewtonSoft MapConverter implementation), although either way can work.

An example that can be used to reproduce would be as simple as
```json
"extensions": {
        "codes": [
          "some code"
        ]
}
```
and deserializing using both the NewtonSoft and SystemTextJson MapConverters.

**Comment by rose-a** [comment]
Thanks for your feedback, your proposals are fairly reasonable...

Will take a look into them.
