### ISSUE TITLE
What is the new GetDataFieldAs ?

### ISSUE THREAD

**Issue by toszi** [graphql-dotnet/graphql-client#228]
I have been trying to create a consuming part for my backend and have been trying to follow many different tutorials, however everyone is using old versions and thereby using GetDataFieldAs to get it to be a json string fit for the object that is wished for. Despite this i have seen many posts in here that stats that it has been removed from the API, and that is why i cannot access it anymore, however no one ever tells what is its replacement? As it is the only little step im missing before my consumption of my api works. 

My code for trying to consume my api looks as following:
```
var graphQLClient = new GraphQLHttpClient("http://localhost:44398/graphql", new NewtonsoftJsonSerializer())
            var request = new GraphQLRequest
            {
                Query = @"?query={
                              materials{
                                id
                                name
                                description
                                gwp_z
                                concrete_scm_details{
                                  fly_ash
                                }
                                pct80_gwp_per_category_declared_unit
                                manufacturer{
                                  name
                                  alt_names
                                  location{
                                    country
                                    postalCode
                                  }
                                }
                                plant{
                                  name
                                  alt_names
                                  location{
                                    localName
                                  }
                                  owned_by{
                                    name
                                    location{
                                      country
                                    }
                                  }
                                }
                              }
                            }
                         "
            };
            var response = await graphQLClient.SendQueryAsync<List<Material>>(request);

            Console.WriteLine(JsonSerializer.Serialize(response, new JsonSerializerOptions { WriteIndented = true }));
            if (response.Errors != null && response.Errors.Any())
            {
                throw new ApplicationException(response.Errors[0].Message);
            }
```

Hope someone can help me find the new way to translate the GraphQLResponse to an object.

**Comment by rose-a** [comment]
Hi, basically the structure of your response type must match the structure of the query string (obviously).

The Readme provides a simple [example](https://github.com/graphql-dotnet/graphql-client#execute-querymutation) for this using a previously declared object (compare this to the query string above). Please note that its easy to forget the root data field (in your case `materials`), which must be present in your return type.

Using the provided extension methods which accept a `Action<TResponse>` as parameter you can also use an anonymous type to declare the response type...

I suspect you missed out the `materials` property, so please try this:

```csharp
var response = await graphQLClient.SendQueryAsync(request, () => new { materials = new List<Materials>() });
List<Materials> materials = response.Data.materials;
```

**Comment by toszi** [comment]
When i copy your SendQueryAsync into my code i get an error stating "The type arguments for method 'GraphQLHttpClient.SendQueryAsync<TResponse>(GraphQLRequest, CancellationToken)' cannot be inferred from the usage."

Im using the 3.1.0 version of GraphQL.Client, gotten from the Nuget manager. Do you have any further ideas how to get through? Or should i just pass List<Material> in as the TResponse?

**Comment by rose-a** [comment]
Please check if you have the namespace `GraphQL.Client.Abstractions` included...

The extension method resides in [here](https://github.com/graphql-dotnet/graphql-client/blob/master/src/GraphQL.Client.Abstractions/GraphQLClientExtensions.cs)

**Comment by toszi** [comment]
thank you very much, now it does not give any errors, now i know some of my faults is on the server side.
