### ISSUE TITLE
Cannot read data back from a mutation

### ISSUE THREAD

**Issue by directfarmer** [graphql-dotnet/graphql-client#229]
Hi everybody
I'm using GraphQL.Client (ver 3.1.0) to create a client application consuming my GraphQL back end API. Everything is working fine when I send query requests but when I try to send a mutation I'm not able to serialize the data coming back from the mutation. When I send the mutation below in the GraphQL playground

`mutation
{
	modifyUser(user : {
		id : 4,
		name : "Jack"
	})
	{
		id
	}
}
`

I get the following answer

`{
  "data": {
    "modifyUser": {
      "id": 4
    }
  }
}`

To read the data I use the following code

`
string req = "<server_url>/mutation { modifyUser(user:{ id:4,name=\"Jack\"}){ id }";
            GraphQLResponse<Response<List<int>>> graphQLResponse = await _graphQlClient.SendMutationAsync<Response<List<int>>>(req);`

Where the class Response is as follow
`public class Response<T>
    {  
public T Data { get; set; }

        public List<ErrorModel> Errors { get; set; }

        public bool HasErros { get { return Errors != null && Errors.Count > 0; } }

        public void OnErrorThrowException()
        {
            if (Errors != null && Errors.Any())
            {
                throw new ApplicationException($"Message: {Errors[0].Message} Code: {Errors[0].Code}");
            }
        }
    }
`
But always the Data property of the class is null

I tried different combination for the Response class but I've never been successful 
Thanks in advance for any help
Marco

**Comment by sungam3r** [comment]
You need a class with `modifyUser` property, not `data`.

**Comment by directfarmer** [comment]
Thanks for the quick answer. But this means that I need a different class for each mutation due to the fact that each of them respond with a different data section name. Is this correct?
Marco

**Comment by sungam3r** [comment]
Of course.

**Comment by rose-a** [comment]
you can avoid that "separate class" by using an anonymous type as return type... this way you can create a "query-specific" shell and reuse the object of interest inside that...

```csharp
var response = await _graphQlClient.SendMutationAsync(req, () => new { modifyUser = new User()});
var user = response.Data.modifyUser;
```

**Comment by sungam3r** [comment]
More precisely, avoid an **explicitly created** class. The class is still created by the compiler.

**Comment by directfarmer** [comment]
thanks a lot @rose-a this is what I was looking for

**Comment by rose-a** [comment]
yea of course, thats propably just a little bit more convenient. I would be very happy about a solution to eliminate this outermost object. This has resulted in the most issues since v2.0.0 was released and its not really intuitive...

**Comment by directfarmer** [comment]
but I've just tried and there's no a SendMutationAsync method which is not templated... I mean there's only the SendMutationAsync<TResponse> version of this method

**Comment by rose-a** [comment]
It's an extension method in namespace `GraphQL.Client.Abstractions`.

https://github.com/graphql-dotnet/graphql-client/blob/561b1d75a64149952c68951fcdf699a5ae4aa01a/src/GraphQL.Client.Abstractions/GraphQLClientExtensions.cs#L34

**Comment by sungam3r** [comment]
> but I've just tried and there's no a SendMutationAsync method which is not templated

Yes, method is templated, compiler **infers** the type. It can be "explicit" type or anonymous type.

**Comment by directfarmer** [comment]
ok now everything is clear
thanks a lot

**Comment by AlexNek** [comment]
I really wonder why it's been closed for so long. And instead of `_graphQlClient.SendMutationAsync<LogInResponse>(request) ` I have to write something like this 
```csharp
var userData = await _graphQlClient.SendMutationAsync<dynamic>(request)
                   .ToObservable()
                   .Select(
                       response =>
                           {
                               //Check if there are any errors in the GraphQL response
                               if (response.Errors != null && response.Errors.Any())
                               {
                                   var errorMessages = string.Join(", ", response.Errors.Select(e => e.Message));
                                   Log.WriteLine($"GraphQL errors occurred: {errorMessages}");

                                   // Optionally, you can throw an exception or return a special error object
                                   throw new Exception($"Login failed: {errorMessages}");
                               }

                               if (response.Data != null)
                               {
                                   LogInResponse loginData =
                                       JsonConvert.DeserializeObject<LogInResponse>(response.Data.ToString());
                                   if (loginData != null)
                                   {
                                       SaveUserData(loginData.Login);
                                       return loginData;
                                   }
                               }

                               return null;
                           });
return userData?.Login;
```
Or am I missing something?

**Comment by rose-a** [comment]
There actually is an [example](https://github.com/graphql-dotnet/graphql-client?tab=readme-ov-file#execute-querymutation) in the readme...

Use a proper response class or the extension method accepting an anonymous object to define your response type, then the client does the deserializing work for you.

I wouldn't use `ToObservable()`, just await the response, check your errors (yes, you need to do that yourself) and then use the response object in `response.Data` (which might be `null`).

**Comment by AlexNek** [comment]
Thanks for the quick response and notice. Look like that auto converting from Angular is not optimal.
This code working well:
```csharp
var response = await _graphQlClient.SendMutationAsync<LogInResponse>(request);
IfErrorThrowException(response, "Login failed:");
return response.Data.Login;
```

**Comment by AlexNek** [comment]
I was expecting that `graphQLError.Extensions["info"]` give me something but the Extensions field is null. Is it ok or error? Is it possible to read _info_ field?
```json
{
    "errors": [
        {
            "message": "Bad Request Exception",
            "code": 400,
            "data": {},
            "info": [
                "password is too weak"
            ]
        }
    ],
    "data": null
}
```

**Comment by rose-a** [comment]
Since its not contained in an `extensions` key in the error object, it does not get deserialized into the `graphQLError.Extensions` dictionary.

This is not an error but a strict interpretation of the GraphQL spec (see [here](https://spec.graphql.org/June2018/#example-fce18)).
