### ISSUE TITLE
Test deserialization of GraphQL Error Path

### ISSUE THREAD

**Issue by rose-a** [graphql-dotnet/graphql-client#232]
This library should be able to handle errors like the example in the [spec](https://spec.graphql.org/June2018/#sec-Errors).

The compatibility querstion was raised in https://github.com/graphql-dotnet/graphql-dotnet/pull/1657.

**Comment by rose-a** [comment]
Ok, I can confirm this working "sort of" 🙄 

Newtonsoft does the deserialization of the error path as expected (array with strings and one integer).

`System.Text.Json` instead returns an array with `JsonElement`s... which also correctly "represent" the path elements, but have to be used entirely different...

**Comment by sungam3r** [comment]
Well, honestly I was expecting such problems. [Documentation](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#deserialization-of-object-properties) explicitly states this behavior. Maybe you should look again at GraphQL.NET S.T.J serializer. It seems we have already solved this problem there.
