### ISSUE TITLE
HttpClient does not contain a definition for AsGraphQLClient

### ISSUE THREAD

**Issue by PetrShchukin** [graphql-dotnet/graphql-client#237]
I haven't found anything in change.log. Previously I did
`
       private readonly HttpClient _apiClient;
       private readonly GraphQLHttpClient _graphQL;

        public DistributorClient(HttpClient client)
        {
            _apiClient = client;
            _graphQL = _apiClient.AsGraphQLClient(new GraphQLHttpClientOptions() { EndPoint = new Uri(_apiClient.BaseAddress.AbsoluteUri + "graphql") });
        }
`
and after updating from version 2 -> 3 I've got an error "HttpClient does not contain a definition for AsGraphQLClient" I've noticed that HttpClientExtensions was removed.

**Comment by sungam3r** [comment]
Yes, this API has been removed.

**Comment by PetrShchukin** [comment]
Is there any suggestion how can I make it work with version 3? Thanks!

**Comment by sungam3r** [comment]
Now there is public ctor https://github.com/graphql-dotnet/graphql-client/blob/master/src/GraphQL.Client/GraphQLHttpClient.cs#L55

**Comment by PetrShchukin** [comment]
made it work
```
using GraphQL.Client.Serializer.Newtonsoft;
_graphQL = new GraphQLHttpClient(new GraphQLHttpClientOptions() { EndPoint = new Uri(_apiClient.BaseAddress.AbsoluteUri + "graphql") }, new NewtonsoftJsonSerializer(), _apiClient);
```
