### ISSUE TITLE
SendQueryAsync returning response object but all fields null

### ISSUE THREAD

**Issue by Aps91** [graphql-dotnet/graphql-client#238]
Hey, I was trying to upgrade graphql client version to 3.1.0. While trying to use SendQueryAsync I am getting expected response object, but contains Null for all fields. No exceptions are raised. Can anyone suggest some possible reasons for this.

**Comment by aldrin-ronco** [comment]
I had the same problem because I was not using the responseType class to
wrap the resulting class, could you provide the relevant code snippets?

maybe I can help you

**Comment by Aps91** [comment]
Thank you.. I have used the following query.
`using (var client = new GraphQLHttpClient(con, new NewtonsoftJsonSerializer()))
{
	var request = new GraphQLRequest
			{
				Query = @"
					query Subscription($subID: String!) {
					 subscriptionByUrn(subId: $subID) { 
							field1 
							field2 
							field3 
							field4 
							field5 
							field6 
					   }
					}",
				Variables = new { subID = "xxx" }
			};
	var response = await client.SendQueryAsync<Subscription>(request);				
}	`

And Response class is

`public class Subscription
{
	public string field1 { get; set; }
	public string field2 { get; set; }
	public string field3 { get; set; }
	public string field4 { get; set; }
	public string field5 { get; set; }
	public string field6 { get; set; }
}`

**Comment by sungam3r** [comment]
So the response will have top level data field named `subscriptionByUrn`:
```json
"data": {
  "subscriptionByUrn": {
    "field1": "",
    "field6": ""
  }
}
```

You should use something like

```c#
public class A { public Subscription subscriptionByUrn { get; set; } }
var response = await client.SendQueryAsync<A>(request); } 
```

**Comment by Aps91** [comment]
That solved my issue. Thank you so much!!!
