### ISSUE TITLE
ListGraphType<SomeInputType> not handling empty lists

### ISSUE THREAD

**Issue by BillBaird** [graphql-dotnet/graphql-client#248]
This is a behavior I am seeing with the newer releases (currently occuring on 3.1.2) that did not occur in older releases from early last year.

Using ListGraphType, lists can contains values, be empty, or be null.  This issue is occuring when using ListGraphType<InputType> where empty lists are not accepted unless variables are used.

Consider a mutation which takes a List parameter of name/value pairs and an associated mutation:
```csharp
public NameValueInputType()
{
    Name = "NameValueInput";
    Field<NonNullGraphType<StringGraphType>>("name", "The name of the item");
    Field<StringGraphType>("value", "The optional value of the item");
}

Field<ResultType>("someMutation",
    arguments: new QueryArguments(
        new QueryArgument<ListGraphType<NameValueInput>> { Name = "items" }
    ),
    resolve: context =>
    {
        var items = context.GetArgument<List<NameValueInput>>("items");
        ... Do something with the items
    }
)
```
These might be used in a call that takes variables, such as:
```graphql
mutation Test($items: [NameValueInput]){someMutation(items:$items){ return fields }}
```

Note that "items" is an optional parameter.

This mutation can be called using variables.  All four forms work fine:
```json
{"items":[{"name":"MyName","value":"ABC"}]}
```
or
```json
{"items":[]}
```
or
```json
{"items":null}
```
or
```json
{ }
```
The first properly passes in a list with a single name/value pair, while the second passes in an empty list.  The third and fourth pass the value null for "items".

The problem arises when simply putting this in with the values hard-coded.  These three forms work as expected:
```graphql
mutation {someMutation(items:[{name:"MyName",value:"ABC"}]){ return fields }}
mutation {someMutation(items:null){ return fields }}
mutation {someMutation{ return fields }}
```
But passing an empty list does not:
```graphql
mutation {someMutation(items:[]){ return fields }}
```
The call is never made and the client returns the error
```
{
  "errors": [
    {
      "message": "GraphQL.ExecutionError: Value cannot be null. (Parameter 'source')
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at GraphQL.Language.CoreToVanillaConverter.Value(GraphQLValue source)
   at GraphQL.Language.CoreToVanillaConverter.Arguments(IEnumerable`1 source)
   at GraphQL.Language.CoreToVanillaConverter.Field(GraphQLFieldSelection source)
   at GraphQL.Language.CoreToVanillaConverter.Selection(ASTNode source)
   at GraphQL.Language.CoreToVanillaConverter.SelectionSet(GraphQLSelectionSet source)
   at GraphQL.Language.CoreToVanillaConverter.Operation(GraphQLOperationDefinition source)
   at GraphQL.Language.CoreToVanillaConverter.AddDefinitions(GraphQLDocument source, Document target)
   at GraphQL.Language.CoreToVanillaConverter.Convert(String body, GraphQLDocument source)
   at GraphQL.Execution.GraphQLDocumentBuilder.Build(String body)
   at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options)
   --- End of inner exception stack trace ---",
      "extensions": {
        "code": "ARGUMENT_NULL",
        "codes": [
          "ARGUMENT_NULL"
        ]
      }
    }
  ]
}
```
The reference to "source" is misleading as nothing in the schema is named source.  Rather, I assume this is related to how it is being parsed.

The workaround is to use variables, which arguably is the "GraphQL way", but I believe the hard-coded form is also valid and should be addressed.

Thanks in advance!

**Comment by rose-a** [comment]
This looks like an issue with the [graphql-dotnet](https://github.com/graphql-dotnet/graphql-dotnet/) library, since the client passes the query string "as is" and from the stacktrace the error is thrown from within the document executor...

@joemcbride FYI
