### ISSUE TITLE
Query.Variables is Null when calling WebApi using 3.1.3

### ISSUE THREAD

**Issue by rgnewlife** [graphql-dotnet/graphql-client#258]
Hi!

I'm having an issue with query variables using GraphQL.Client 3.1.3 and GraphQL.Client.Serializer.Newtonsoft 3.13 calling an netcoreapp3.1 WebApi from a console app.  **My query.Variables object in the WebApi is always null.**  I've tried implementing as new and also explicitly populating a JObject.  No joy.

My WebApi works fine with Postman calls, and queries without parameters (i.e GetAllAsync) also work using GraphQL.Client.

This is my simplified calling code:

        static async Task<PrayerGroup> GetPrayerGroupByIdAsync(Guid prayerGroupId)
        {
            GraphQLRequest request = new GraphQLRequest();

            string query = @"query GetPrayerGroupById($id:ID!)
                            {prayergroup(id:$id)
                                {
                                    id
                                    prayerGroupName
                                    prayerGroupDescription
                                    dateCreated
                                    dateLastModified
                                }
                            }";

            request.Query = query;

            // Variables object is null in Web Api
            request.Variables = new { prayerGroupId };
            
            // This does not work either:

            //JObject variables = new JObject();
            //variables.Add("id", prayerGroupId);
            //request.Variables = variables;
            
            var response = await _client.SendQueryAsync<PrayerGroup>(request);
            if (response.Errors != null && response.Errors.Any())
            {
                throw new ApplicationException(response.Errors[0].Message);
            }

            return response.Data;
        }

This is my GraphQLQuery Object in the WebApi:

    public class GraphQLQuery
    {
        public string OperationName { get; set; }
        public string NamedQuery { get; set; }
        public string Query { get; set; }
        public JObject Variables { get; set; } //https://github.com/graphql-dotnet/graphql-dotnet/issues/389
    }

 This is my GraphQL execution method in the WebApi:

        [HttpPost]
        public async Task<IActionResult> Post([FromBody] GraphQLQuery query)
        { 
            if (query == null) { throw new ArgumentNullException(nameof(query)); }

            var executionOptions = new ExecutionOptions
            {
                Schema = _schema,
                Query = query.Query,
                Inputs = query.Variables.ToInputs(),
                ExposeExceptions = true
            };

            
            var result = await _documentExecuter.ExecuteAsync(executionOptions).ConfigureAwait(false);

            if (result.Errors?.Count > 0)
            {
                return BadRequest(result);
            }

            return Ok(result);
        }
  
TIA for any help!

**Comment by rgnewlife** [comment]
So I managed to fix this by changing variables to:

request.Variables = new { id = prayerGroupId };

Now my call returns Ok, but the object is not populated.  Ughh.

**Comment by rose-a** [comment]
How does your `PrayerGroup` class look like? The top-level response object must have a property named `prayergroup` (like your top-level query field)!

The returned object will look like this:

```csharp
var response = new { 
    prayergroup = new {
        id = string.Empty,
        prayerGroupName = string.Empty,
        prayerGroupDescription = string.Empty,
        dateCreated = DateTime.Now,
        dateLastModified = DateTime.Now
    }
};
```

**Comment by rgnewlife** [comment]
Thanks Alexander,

My PrayerGroup is a simple POCO.  This is my first attempt to use GraphQL, so I am just trying to get a round trip with simple objects to work at this point.



    public class PrayerGroup : BaseEntity
    {
        [Required]
        [Display(Name = "Prayer Group Name")]
        public string PrayerGroupName { get; set; }

        [Required]
        [Display(Name = "Prayer Group Description")]
        public string PrayerGroupDescription { get; set; }

        // TODO:  Implement
        //public List<Believer> Believers { get; set; } = new List<Believer>();

        public PrayerGroup() : base()
        {           
        }
    }

    public class BaseEntity
    {
        
        [Required]
        public Guid Id { get; set; }
        
        [Display(Name = "Date Created")]
        [Required]
        public DateTime DateCreated { get; set; }

        [Display(Name = "Date Last Modified")]
        [Required]
        public DateTime DateLastModified { get; set; }

        public BaseEntity()
        {         
        }
    }

The response is:

{
    "statusCode": 200,
    "data": {
        "prayerGroupName": null,
        "prayerGroupDescription": null,
        "id": "00000000-0000-0000-0000-000000000000",
        "dateCreated": "0001-01-01T00:00:00",
        "dateLastModified": "0001-01-01T00:00:00"
    },
    "errors": null,
    "extensions": null
}

I'm a little confused about what I am doing wrong because the exact same query executed through my GraphQL Server and Postman returns:

{
    "data": {
        "prayergroup": {
            "id": "abdb69cc-2d89-4883-8579-9d68e5c84437",
            "prayerGroupName": "PGTest1",
            "prayerGroupDescription": "Prayer Group 1 Added from Postman",
            "dateCreated": "2020-06-24",
            "dateLastModified": "2020-06-28"
        }
    }
}

**Comment by rose-a** [comment]
Your response class has to represent the content of the `data` field in the response:

```json
{
    "data": {
        "prayergroup": {
            "id": "abdb69cc-2d89-4883-8579-9d68e5c84437",
            "prayerGroupName": "PGTest1",
            "prayerGroupDescription": "Prayer Group 1 Added from Postman",
            "dateCreated": "2020-06-24",
            "dateLastModified": "2020-06-28"
        }
    }
}
```

so you basically need a class which has a property `PrayerGroup` of type `PrayerGroup` defined in your response:

```csharp
public class PrayerGroupResponse 
{
    public PrayerGroup PrayerGroup { get; set; }
}
```

and then use that as the response type

```csharp
var response = await _client.SendQueryAsync<PrayerGroupResponse>(request);
```

Alternatively you could use an anonymous type:

```csharp
var response = await _client.SendQueryAsync(request, () => new { prayergroup = new PrayerGroup() });
```

**Comment by rgnewlife** [comment]
Hi,

Thanks.  I added the anonymous type call and that did the trick.
