### ISSUE TITLE
Parse error on "\\" (error) at [1, 81]

### ISSUE THREAD

**Issue by RickySan65** [graphql-dotnet/graphql-client#259]
When i use query below i get "Parse error on "\\" (error) at [1, 81]"  i have to pass the \\\" to get the correct query, if i use the generated query in postman it works...

```
{
  "query": "{
    squad(id:30737) {
      name
      cards (includedOnKanban:true,
             closed:true,
             archived:false,
             cancelled:false,
             updatedSince: \\\"2019-10-10T00:00:00-0300\\\") {
        identifier
        title
        description
      }
    }
  }"
}
```

**Comment by rose-a** [comment]
The parse error is reported by the GraphQL server you're talking to, not by this library.

Here are some tips to get your query fixed:

- Remove all the quotes from your query, only those around your timestamp are needed (without the backslashes)
- Use GraphQL variables to pass your query arguments (as described [here](https://graphql.org/learn/queries/#variables) and [here](https://github.com/graphql-dotnet/graphql-client#operationname-and-variables-request)), this also takes care of parsing and formatting them correctly

**Comment by RickySan65** [comment]
that doesnt seem to work either

                var cardInfo = new GraphQLRequest
                {
                    Query = @"{squad(id:" + SquadID + ")" +
                    "{name  description  cards (includedOnKanban:true, updatedSince:$UpdatedSince){identifier title description}}}",
                    Variables = new { UpdatedSince = "2020-01-01T00:00:00-0300"}
                    };
                
                var response = await _client.SendQueryAsync<Responses.squad>(cardInfo);
                var x = response.Data._squad.cards;

i get 

Variable $UpdatedSince is used by  but not declared

**Comment by sungam3r** [comment]
Right. You did not declare variable.

**Comment by sungam3r** [comment]
https://shopify.dev/concepts/graphql/variables

**Comment by RickySan65** [comment]
its a query though, i'm not creating data...

**Comment by sungam3r** [comment]
It doesn't matter, there are examples, the syntax is common for queries, mutations, subscriptions

**Comment by RickySan65** [comment]
the api i query against doesn't allow mutations on that particular query (squad)

**Comment by sungam3r** [comment]
I talk you not about mutations. I talk about **syntax**.

**Comment by RickySan65** [comment]
```
 var cardInfo = new GraphQLRequest
            {
                Query = @"{squad(id:" + SquadID + ")" +
                "{name  description  cards (includedOnKanban:true, updatedSince:$UpdatedSince){identifier title description}}}",
                Variables = new { UpdatedSince = "2020-01-01T00:00:00-0300"}
                };
            
            var response = await _client.SendQueryAsync<Responses.squad>(cardInfo);
            var x = response.Data._squad.cards;
```
so in this where to i declare the variable?

**Comment by sungam3r** [comment]
query aaa($UpdatedSince: YourType) { squad(id: 45533, updatedsince: $UpdatedSince) } { your selection set }
