### ISSUE TITLE
Missing Throttling parameters in Error Object of SendQueryAsync<> method

### ISSUE THREAD

**Issue by Khungersumit** [graphql-dotnet/graphql-client#267]
Hi

Please include Throttling parameters such as "time_remaining", "remaining_credits","required_credits"  in 
 **SendQueryAsync<>** method's response object.

For e.g

**What I get in Postman:** 
{
    "errors": [
        {
            "code": 30,
            "message": "There are not enough credits to perfom the requested operation, which requires 2101 credits, but the are only 1001 left. In 0:01:14 minutes you will have enough credits to perform the operation",
            "operation": "products",
            "request_id": "5f438ca4021e31279b6d8291",
            "required_credits": 2101,
            "remaining_credits": 1001,
            "time_remaining": "0:01:14 minutes"
        }
    ],
    "data": {
        "products": null
    }
}

**What I get using GraphQLHttpClient**
.....
.....
  "StatusCode": 200,
  "Data": {
    "products": null
  },
  "Errors": [
    {
      "Locations": null,
      "Message": "There are not enough credits to perfom the requested operation, which requires 11161 credits, but the are only 1001 left. In 0:11:18 minutes you will have enough credits to perform the operation",
      "Path": null,
      "Extensions": null
    }
  ],
  "Extensions": null
}

Please include "time_remaining", "remaining_credits" and "required_credits" parameters.

Thanks
Sumit Khunger

**Comment by rose-a** [comment]
These are custom error fields which are not in line with the [GraphQL Spec](https://spec.graphql.org/June2018/#sec-Errors). Those need to go into the extensions map!

If possible, change your server implementation to follow the spec. 

If this is not possible, a workaround would be to reimplement one of the JsonSerializers to support your custom error format (see [here](https://github.com/graphql-dotnet/graphql-client/issues/263#issuecomment-675264405))
