### ISSUE TITLE
Looks like possible NPE in GraphQLHttpException constructor

### ISSUE THREAD

**Issue by SapphireBrand** [graphql-dotnet/graphql-client#27]
The constructor for GraphQLHttpException accesses httpResponseMessage.StatusCode in the base class constructor parameters before validating that httpResponseMessage is not null.

**Comment by deinok** [comment]
Mmmm, seems like `Exception.Message` is readonly.
The solution is 
* Let the Message as: `$"Unexpected {nameof(System.Net.Http.HttpResponseMessage)}"`
* Let it as it is

Any better idea @SapphireBrand ?

**Comment by SapphireBrand** [comment]
How about $"Unexpected {nameof(System.Net.Http.HttpResponseMessage)} with code: {httpResponseMessage?.StatusCode}"

That should work, no? nullable<int> has a ToString method.
