### ISSUE TITLE
Unexpected behavior with GraphQLHttpRequest query variable

### ISSUE THREAD

**Issue by Walid-Abdulrazik** [graphql-dotnet/graphql-client#273]
i have the following query

```csharp
            GraphQLHttpClient client = new GraphQLHttpClient(new GraphQLHttpClientOptions
            {
                EndPoint = new Uri("https://graphql.somewebsite.com/")
            }, new NewtonsoftJsonSerializer());

            var request = new GraphQLHttpRequest
            {
                Query = @"
                         query baseQ ($WhereVariable: String)
                            {
                            BodySystem(Where: $WhereVariable){
                                     Id
                                     Name
                                     RowVersion
                                     Description
                                      }}
                        ",
                OperationName = "baseQ",
                Variables = new { WhereVariable = "Name == \"Eye\"" }
            };

var response = await client.SendQueryAsync<Data.BodySystem.data>(request);
                BS = response.Data.BodySystem;
```

It compiles fine, it runs fine without error but does not return the desired result ...
if i run the same query in GraphiQL web interface it returns the desired result ...

what could be causing this and how can i fix this ?

**Comment by AhmedHamdy81** [comment]
According to the GraphQL spec, the variables key in the body should be sent as an Object.
GraphiQL client sends this as a string which can cause unexpected behaviour on other GraphQL servers which follow the spec.
Also note that GraphiQL is just a UI element and intentionally requires you to provide your own "fetcher" to handle the network. You absolutely don't have to copy the one from the example in this repo, you can format the request to your server however your server requires it.

**Comment by Walid-Abdulrazik** [comment]
actually GraphiQL works alright in my case ... but my code it does not ! it compiles fine and it runs without throwing any exception or error ... 

but the data i get back is wrong ... actually it looks like the graphql engine or client is ignoring that there is a variable and it just returns all the data in the table ...

**Comment by rose-a** [comment]
Please provide the variables JSON you put into GraphiQL

**Comment by Walid-Abdulrazik** [comment]
i am sorry but the problem turned out to be much deeper ... the GraphQL variables are not sent at all ... i had to return to microsoft httpclient library and it now works ... there seems to be a problem with the graphql client library and it is not related to double quotes at all ... the variable part of the json is not sent ...

**Comment by rose-a** [comment]
As far as I can see the problem is likely that the json serializers convert all json property names to camel case by default.

This results in your variables being serialized as follows (which works without any problems when I add your `GraphQLRequest` to the serialization test):

```json
{"whereVariable":"Name==\"Eye\""}
```

Since you're using a capital variable name in the query the server does not discover the variable and since it's declared as nullable ignores it.

The fix would just be using a camel case variable name everywhere:

```csharp
var request = new GraphQLHttpRequest
{
    Query = @"
        query baseQ ($whereVariable: String)
        {
            BodySystem(Where: $whereVariable){
                Id
                Name
                RowVersion
                Description
            }
        }
    ",
    OperationName = "baseQ",
    Variables = new { whereVariable = "Name == \"Eye\"" }
};
```

**Comment by Walid-Abdulrazik** [comment]
did not cross my mind ... this answer is brilliant ... so if i can override the default serializer behaviour i can fix this

**Comment by Walid-Abdulrazik** [comment]
how can i override the default serializer behaviour of the library?

**Comment by Shane32** [comment]
```cs
new NewtonsoftJsonSerializer(opts => { opts.ContractResolver = new DefaultContractResolver(); })
```
Something like that maybe?

See: https://github.com/graphql-dotnet/graphql-client/blob/master/src/GraphQL.Client.Serializer.Newtonsoft/NewtonsoftJsonSerializer.cs

**Comment by Shane32** [comment]
Also see: https://www.newtonsoft.com/json/help/html/ContractResolver.htm

**Comment by Walid-Abdulrazik** [comment]
thank you @Shane32  ... i'll try it and let you all know ... thank you very much ...

**Comment by rose-a** [comment]
@Walid-Abdulrazik there is a test doing just that: https://github.com/graphql-dotnet/graphql-client/blob/3cd3566afcfa20ab7c8e794e652f28dd98164659/tests/GraphQL.Client.Serializer.Tests/NewtonsoftSerializerTest.cs#L14

**Comment by Walid-Abdulrazik** [comment]
both solutions work ... either change to camel casing or change default serializer ... positively both work ... thank you guys ...
