### ISSUE TITLE
Blazor WebAssembly - handle unsupported properties properly

### ISSUE THREAD

**Issue by rose-a** [graphql-dotnet/graphql-client#280]
In #274 we've added a workaround for unsupported properties in WASM which swallows the `PlatformNotSupported` exceptions.
We should add proper guards to avoid execution this part of the code completely when running on WebAssembly.

@bjorg, I've found [this answer](https://github.com/dotnet/aspnetcore/issues/18268#issuecomment-573123617) in a GitHub issue on "detecting if the code runs in WASM".

Could you please try if `RuntimeInformation.IsOSPlatform(OSPlatform.Create("WEBASSEMBLY"))` correctly detects your code running in WebAssembly? This way we could purposely avoid accessing these properties without swallowing exceptions...

Seems that from .NET 5 on we'll get a `OperatingSystem.IsBrowser()` method to do just this, according to [this article](https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/#dealing-with-apis-that-are-unsupported-in-blazor-webassembly)...

**Comment by bjorg** [comment]
I saw the announcement for `OperatingSystem.IsBrowser()`, but I was not aware of `RuntimeInformation.IsOSPlatform(OSPlatform.Create("WEBASSEMBLY"))`.

I'm happy to test it and see if it works as expected. The expectation being that unsupported properties are simply ignored and not set, correct?

**Comment by rose-a** [comment]
yeah, I'm thinking something like

```csharp
if(!RuntimeInformation.IsOSPlatform(OSPlatform.Create("WEBASSEMBLY"))){
    _clientWebSocket.Options.ClientCertificates = ((HttpClientHandler)Options.HttpMessageHandler).ClientCertificates;
    _clientWebSocket.Options.UseDefaultCredentials = ((HttpClientHandler)Options.HttpMessageHandler).UseDefaultCredentials;
}
```

**Comment by bjorg** [comment]
Here you go: https://github.com/graphql-dotnet/graphql-client/pull/283

Please verify that I didn't break anything for other runtime targets.
