### ISSUE TITLE
New "Panic.StringUtils" dependency results in "detected package downgrade"-build error

### ISSUE THREAD

**Issue by cwe1ss** [graphql-dotnet/graphql-client#282]
Hi!

The newly introduced dependency on "Panic.StringUtils" resulted in some "Detected package downgrade" errors in our solution. I guess the reason is that Panic.StringUtils still targets .NET Standard 1.1.

I've seen that this library is really small (just 2 classes) so maybe it would be better to just copy the code you need so that you don't require this additional dependency?

error NU1605: Detected package downgrade: System.Runtime.InteropServices from 4.3.0 to 4.1.0. Reference the package directly from the project to select a different version.
error NU1605: Detected package downgrade: System.IO.FileSystem.Primitives from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version.
error NU1605: Detected package downgrade: System.Runtime.InteropServices from 4.3.0 to 4.1.0. Reference the package directly from the project to select a different version.
error NU1605: Detected package downgrade: System.Diagnostics.Debug from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version.
error NU1605: Detected package downgrade: System.Diagnostics.Tracing from 4.3.0 to 4.1.0. Reference the package directly from the project to select a different version.
error NU1605: Detected package downgrade: System.IO.FileSystem from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version.
error NU1605: Detected package downgrade: System.IO.FileSystem.Primitives from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version.
error NU1605: Detected package downgrade: System.Net.Primitives from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version.
error NU1605: Detected package downgrade: System.Runtime.Handles from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version.
error NU1605: Detected package downgrade: System.Runtime.InteropServices from 4.3.0 to 4.1.0. Reference the package directly from the project to select a different version. 
error NU1605: Detected package downgrade: System.Diagnostics.Tracing from 4.3.0 to 4.1.0. Reference the package directly from the project to select a different version.
error NU1605: Detected package downgrade: Microsoft.Win32.Primitives from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version.
 </details>

**Comment by sungam3r** [comment]
I also noticed this. I suggest to copy code and get rid of dependency.

**Comment by rose-a** [comment]
well ok... I guess thats what happened in https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Utilities/StringUtils.cs too ;)

**Comment by sungam3r** [comment]
Maybe

**Comment by cwe1ss** [comment]
Thank you very much for this very quick fix! Much appreciated!! 👍
