### ISSUE TITLE
Feature request: Multi-targeting for GraphQL.Client.Serializer.Newtonsoft

### ISSUE THREAD

**Issue by oysteingl** [graphql-dotnet/graphql-client#288]
- Why do we need this
The examples in the documentation are not possible to follow when using the library in .NET 4.6.1. The main library works, but since the Serializer-project does not multi-target, it is not possible to add a valid serializer to the client.

**Comment by rose-a** [comment]
I'm perfectly able to build and run the example with `net461` as target framework with minor code changes (i.e. fixing the `using` statement)...
