### ISSUE TITLE
Only working for .NET 4.5?

### ISSUE THREAD

**Issue by KammererTob** [graphql-dotnet/graphql-client#29]
I tried to use this library while targeting .NET Framework 4.6.2, but i always get a `System.MissingMethodException` saying that
`get_DefaultRequestHeaders()` method was not found.
This works fine when targeting .NET 4.5.2. Is this a known issue, or am i doing something wrong?

Here is my code snippet which causes the issue:

    graphQLClient.DefaultRequestHeaders.Authorization =
         new AuthenticationHeaderValue("Basic", Convert.ToBase64String(
             System.Text.ASCIIEncoding.ASCII.GetBytes(string.Format("{0}:{1}", UserName, Password))));

**Comment by deinok** [comment]
Its an unknown and unexpected error.
I will look further ASAP and release a bugfix.

**Comment by deinok** [comment]
I don't know why you have this kind of error.
The only thing that i could recommend is that you should clean your solution.
ref: https://stackoverflow.com/questions/8058832/system-missingmethodexception-method-not-found

Also, I have tested your code in 4.5.2 and 4.6.2 and in the two cases seems like it is working.

[Issue-29.zip](https://github.com/graphql-dotnet/graphql-client/files/1766270/Issue-29.zip)

**Comment by KammererTob** [comment]
I will create a completely fresh project (maybe other dependencies are causing some kind of conflict). Thanks for investigating this fast!
