### ISSUE TITLE
Support for dedicated subscription endpoint

### ISSUE THREAD

**Issue by oliversalzburg** [graphql-dotnet/graphql-client#297]
In Apollo Server, one usually has a dedicated endpoint for subscriptions that differs from the one used for queries and mutations.

To my understanding this is due to the fact that Apollo Server can act as a gateway to multiple GraphQL backends through schema stitching. When operating as a gateway, subscriptions are not supported. Providing subscriptions on a dedicated endpoint allows to work around this limitation, because mutations and queries can be routed to the gateway, while subscriptions can be routed to a dedicated service.

I was surprised that this client only accepts a single endpoint. I was under the impression that a setup with 2 endpoints is not uncommon.

Am I missing something here? As this apparently isn't supported as of now, I feel like I might be doing something wrong.

**Comment by oliversalzburg** [comment]
After reading through some of the open tickets, it appears as if there is already work in progress to support a dedicated websocket endpoint.

**Comment by rose-a** [comment]
Correct, meanwhile you could use a separate instance of `GraphQLHttpClient` to use the websocket endpoint...

**Comment by oliversalzburg** [comment]
I'm closing this, as it was mostly a question and the issue is being tracked elsewhere :)
