### ISSUE TITLE
Documentation or tutorials?

### ISSUE THREAD

**Issue by DerKO9** [graphql-dotnet/graphql-client#299]
I am new to GraphQL and I am trying to learn by using this library. Are there any beginner tutorials or documentation for me to look at? All I can find on the readme is a simple query and response, which I was able to understand and run myself. However, I need mutations that send List < MyClass > and I have no idea how mapping works.

All my google searches have been tutorials on how to set up a GraphQL server, but non for client. This also appears to be THE .net GraphQL client library and I can't find any other library with decent documentation either.

**Comment by rose-a** [comment]
Mutations work exactly like queries.

Write your query and put your list into the variables object. Make sure your chosen JSON lib is serializing your list to the JSON structure your server expects as variable for your mutation.

This is all demonstrated in the [readme](https://github.com/graphql-dotnet/graphql-client#operationname-and-variables-request) and in the [example project](https://github.com/graphql-dotnet/graphql-client/blob/master/examples/GraphQL.Client.Example/Program.cs).
