### ISSUE TITLE
GraphQLError class need more properties

### ISSUE THREAD

**Issue by MMalikKhan** [graphql-dotnet/graphql-client#30]
Hi @deinok , I am playing with this graphQL client so far so good. Error handling on our server actually have a additional property which send the exact errorcode. Based on which different actions are taken,  however when there is an error, i only see Location and Message property, any additional properties returned are ignored. Can you please add something like this to your classes so any additional properties which were returned will not be lost, instead will be loaded in this property ?

[JsonExtensionData] private IDictionary<string, JToken> _additionalData;

Also, is this library good to use with UWP app?

Thank You

**Comment by deinok** [comment]
Can you give me an example of the error type you are returning (An example of the JSON)?
To have more information of the better way to handle this.

About the UWP, I haven't test it. But the lib targets netstandard1.1, netstandard1.3 and netstandard2.0 (netstandard1.1 CAN be deleted in V2) so it should go well for UWP apps.

**Comment by MMalikKhan** [comment]
@deinok thank you for your quick reply

`{
    "error": [
        {
            "message": "Duplicate found - 409 - {\"statusCode\":409,\"error\":\"Conflict\",\"message\":\"Evidence evidence_id already exists\"}",
            "locations": [
                {
                    "line": 2,
                    "column": 33
                }
            ],
            "path": [
                "createEvidence"
            ],
            "name": "Duplicate"
        }
    ]
}`

above is a sample error object for a duplicate record, currently server is putting "Duplicate" as a error in the name property, but with currently error object only have Location and Message property, i am not able to access 'name' property.  The reason i was suggesting you to add a generic property which can hold all the other non-standard properties.. 
I appreciate if you can remove the older netstandard 1..1 and make it complaint with UWP then it will help lot of other users as well, also add this 'name' property or do some update so that additional properties which are not in GraphQLError class can also be available for anyone if required. 

let me know if you need any additional information, if possible can you get this change push to nuget once updated. Let me know if you need a hand or PR. 

thank you

**Comment by MMalikKhan** [comment]
@deinok any updates for me mate?

**Comment by deinok** [comment]
Well, its okey to have a way to define this new properties, as it is allowed in the spec.
So yes, this will be in the next release (Released this next week end).

About UWP, you should be able to use it, cause UWP support netstandard.
So, if you are having problems with UWP open a new issue with all the information you can, and it will be faced ASAP
