### ISSUE TITLE
GraphQLRequest - Anonymous type missing square brackets in mutation query.

### ISSUE THREAD

**Issue by spang98** [graphql-dotnet/graphql-client#302]
When inserting a 'New' anonymous type inside another, it doesn't format the query correctly. I've checked this with Fiddler and it is missing the square brackets for a valid request. I've used Postman to send the request and Postman has the brackets.

```csharp
var request = new GraphQLRequest
{
    Query = @"
    mutation(
        $id: Int!
        $TestItems: [TestItemInput]!
    ) {
        createTest(
            TestItems: $TestItems
            id: $_id
        ) {
            TestItems {
                value
                Card {
                    id
                    card_reference
                    card_alias_card_reference
                    balance
                    initial_balance
                    updated_at
                    created_at
                }
            }
        }
    }",
    Variables = new
    {
        TestItem = new
        {
            item_id = itemID,
        },
    }
```

Am I doing this wrong? Is there a different way to implement this?

**Comment by rose-a** [comment]
From my point of view there are multiple issues with your `GraphQLRequest`:

1. AFAIK the variable declarations and usages in your query string must be separated with a comma.
2. You don't pass the `id` variable in your variables object
3. Your `TestItems` variable should be a list of `TestItemInput`. You 
  a. misspelled the variable name in the anonymous object (should be `TestItems` instead of `TestItem`)
  b. only passed a single object instead of a list

**Comment by spang98** [comment]
Sorry, I butchered the syntax because I was removing and renaming them. It's actually syntaxed correctly in C#. In the variables, it actually does have a list of items and TestItemInput doesn't only contain item_id. The issue is still lies within the new inside the new in the variables. Is it actually possible to have the new inside the new? I wouldn't see why not but the closed brackets don't get added for some reason.

**Comment by rose-a** [comment]
Yes, that's possible and I've done that more than once. Make sure that variable names match after your variables object is serialized into JSON. By default the serializer implementations in this library serialize property names to *camelCase*! 

If you wan't other people to find your errors then please post the correct code. Further your GraphQL server should answer with an error describing whats wrong with your query (i.E. if a variable is missing from the input object, which could point to a naming issue). That too would be helpful information.

**Comment by spang98** [comment]
Hi, see below for request and response from the server.

This request doesn't add the square brackets for ReversalItems.

                var BalanceAdjustmentRequest = new GraphQLRequest
                {
                    Query = @"
                    mutation(
                      $currency: String
                      $value: Int
                      $card_reference: String!
                      $unit_epos_reference: String!
                      $merchant_id: Int!
                      $merchant_transaction_reference: String
                    ) {
                      createBalanceAdjustment(
                        currency: $currency
                        card_reference: $card_reference
                        value: $value
                        unit_epos_reference: $unit_epos_reference
                        merchant_id: $merchant_id
                        merchant_transaction_reference: $merchant_transaction_reference
                      ) {
                        id
                        value

                        LineItem {
                          Transaction {
                            merchant_transaction_reference
                          }
                          Card {
                            id
                            card_reference
                            card_alias_card_reference
                            balance
                            initial_balance
                            created_at
                            updated_at
                          }
                        }
                      }
                    }",
                    Variables = new
                    {
                        currency = Lookup.GetDefaultCurrency().CurrencyName,
                        card_reference = voucherNo,
                        value = "-" + Helpers.Currency.GetBaseValue(amountToRedeem, lookup.GetDefaultCurrency()),
                        unit_epos_reference = 12345, //Lookup.SiteID,
                        merchant_id = SysSettings.ToggleMerchantID,
                        merchant_transaction_reference = merchID
                    }
                };

Response.
{
    "errors": [
        {
            "message": "Variable \"$ReversalItems\" got invalid value {\"line_item_id\":\"512601\",\"shipping_refund\":false}; Expected type ReversalItemInput to be an object at value.line_item_id.",
            "locations": [
                {
                    "line": 5,
                    "column": 3
                }
            ],
            "customer_facing": false
        },
        {
            "message": "Variable \"$ReversalItems\" got invalid value {\"line_item_id\":\"512601\",\"shipping_refund\":false}; Expected type ReversalItemInput to be an object at value.shipping_refund.",
            "locations": [
                {
                    "line": 5,
                    "column": 3
                }
            ],
            "customer_facing": false
        }
    ]
}

Adding in the square brackets after the ':' and before the ',' for ReversalItems in Fiddler or Postman fixes the request.

**Comment by rose-a** [comment]
Sorry, but is this the correct GraphQL request you postet there? There are no `ReversalItems`...

**Comment by spang98** [comment]
Yes, that is C#. The response is from Postman.

This is the query on Postman.
mutation(
  $merchant_id: Int!
  $unit_epos_reference: String!
  $merchant_transaction_reference: String
  $ReversalItems: [ReversalItemInput]!
) {
  createReversal(
    ReversalItems: $ReversalItems
    merchant_transaction_reference: $merchant_transaction_reference
    unit_epos_reference: $unit_epos_reference
    merchant_id: $merchant_id
  ) {
    merchant_transaction_reference
    LineItems {
      value
      Card {
        id
        card_reference
        card_alias_card_reference
        balance
        initial_balance
        updated_at
        created_at
      }
    }
  }
}
Variables from Postman - includes the brackets.
{
  "ReversalItems": [
    {
      "line_item_id": "512601",
      "shipping_refund": false
    }
  ],
  "merchant_transaction_reference": "f",
  "merchant_id": 17,
  "unit_epos_reference": "12345"
}

The C# request doesn't generate the square brackets. Please let me know if this is still wrong syntax.

**Comment by rose-a** [comment]
Those are entirely different quers strings!

The Variables object for your last post can be constructed as follows:

```c#
Variables = new {
    ReversalItems = new List<ReversalItem> {
        new ReversalItem {
            line_item_id = 512601,
            shipping_refund = false
        }
    },
    merchant_transaction_reference = "f",
    merchant_id = 17,
    unit_epos_reference = "12345"
}

public class ReversalItem {
    public int line_item_id { get; set; }
    public bool shipping_refund { get; set; }
}
```

Please test your JSON serialization, you're using multiple naming conventions for your variables there! [This unit test](https://github.com/graphql-dotnet/graphql-client/blob/5356743fc186dcdf2be29c7777f46e0e10b6d46f/tests/GraphQL.Client.Serializer.Tests/BaseSerializerTest.cs#L40) shows how to do that.

**Comment by spang98** [comment]
The only issue that i have no is the fact that the 'ReversalItems' doesn't get capitalised. The server expects 'ReversalItems' to be capitalised whereas the other 3 variables doesn't require this.

**Comment by rose-a** [comment]
Just rename your variable in your GraphQL query, the server doesn't care about the variable name.

```graphql
mutation(
  $merchant_id: Int!
  $unit_epos_reference: String!
  $merchant_transaction_reference: String
  $reversalItems: [ReversalItemInput]!
) {
  createReversal(
    ReversalItems: $reversalItems
    merchant_transaction_reference: $merchant_transaction_reference
    unit_epos_reference: $unit_epos_reference
    merchant_id: $merchant_id
  ) {
    merchant_transaction_reference
    LineItems {
      value
      Card {
        id
        card_reference
        card_alias_card_reference
        balance
        initial_balance
        updated_at
        created_at
      }
    }
  }
}
```
