### ISSUE TITLE
How do I access the response body, other than 'data' and 'errors' members?

### ISSUE THREAD

**Issue by jaacquees** [graphql-dotnet/graphql-client#305]
Hello

I am using this library to consume an graphql API. Sometimes the API response is of the form:

 **_{
error_code": "ColumnValueException",
"status_code": 200,
"error_message": "invalid value, please check our API documentation [...]",
"error_data":[...]
 }_**

How do I access these members, which are neither "data" nor "errors" ?

thanks

Jaacquees

**Comment by sungam3r** [comment]
Well, it is not spec complying response. Your graphql server should answer you different.

**Comment by jaacquees** [comment]
Thanks @sungam3r, without knowing the GraphQL standard by heart yet, I suspected it was the case. I thought it was strange that the API didn't use the 'errors' enumerable member to send back error messages and details.

Thanks for confirming.
