### ISSUE TITLE
Is any way to get raw response data?

### ISSUE THREAD

**Issue by hupo376787** [graphql-dotnet/graphql-client#307]
Hi, we have some extra property in Error, when I use 
`var graphQLResponse = await graphQLClient.SendMutationAsync<CheckFreeTrialResponse>(request);`
'graphQLResponse' just ignores my `trace` $ `code`, so I want to get the raw response string.
Thanks.

![image](https://user-images.githubusercontent.com/14960168/99371351-c1e65e80-28f9-11eb-80b5-531434486366.png)

**Comment by rose-a** [comment]
Hi, currently there is no simple way to get the raw response.

Your customized error is not compliant with the GraphQL spec though, custom extensions must go into the `extensions` map inside your error.

Then you will be able to access them in `graphQLResponse.Errors[0].Extensions["trace"]` and `graphQLResponse.Errors[0].Extensions["code"]`

**Comment by hupo376787** [comment]
Got it. Thanks, bro.

**Comment by rgwood** [comment]
I would find this very useful in 2 situations:

1. Deserialization failed and I want to log the raw response for investigation
2. Deserialization succeeded and I want to log the raw response to replay it later (this often comes up during development)
