### ISSUE TITLE
How to customize the GraphQL Client with Asp.net Core Integration Testing - WebApplicationFactory

### ISSUE THREAD

**Issue by MatheswaranSagadevan** [graphql-dotnet/graphql-client#315]
Hi,

All your test examples are built on top of IWebHostBuilder and making it run asynchornously.

I have a requirement where I need to mix the approaches. I have the Custom Web Application Factory from asp.net core integration testing, and want to create a test for web socket subscriptions.

When I do so, it is returning the below error:
 System.Net.WebSockets.WebSocketException : Unable to connect to the remote server
    ---- System.Net.Http.HttpRequestException : No connection could be made because the target machine actively refused it.
    -------- System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it.

**Comment by MatheswaranSagadevan** [comment]
But this customized approach is working fine for Query and Mutation with Http Requests.
I'm facing the error only when i try to convert the tests to web sockets.

kindly do the needful asap.

**Comment by rose-a** [comment]
AFAIK the web application factory thom asp.net core does not support websockets.... thats why the test setup in this repo is so "bulky" (it actually spins up a real web server, not just a mock).
