### ISSUE TITLE
Does it support .net5 plz? I can't connect with my shopify endpoint.

### ISSUE THREAD

**Issue by imWayneWY** [graphql-dotnet/graphql-client#317]
I am new in .net and I have no idea why it doesn't work.

```
            GraphQLHttpClient httpClient = new GraphQLHttpClient("my_graphql_uri", new NewtonsoftJsonSerializer());
            httpClient.HttpClient.DefaultRequestHeaders.Add("X-Shopify-StoreFront-Access-Token", "the_access_token");
            services.AddSingleton(s => httpClient);
```

When I set a breakpoint at the last line, it shows httpClient.HttpClient.BaseAddress is null. I am thinking maybe it's because I am using NET 5? Could someone give me a tip for how to solve this please? Thanks.

**Comment by rose-a** [comment]
`GraphQLHttpClient` does never set the base address of `HttpClient`...

There is no reason why it should not be compatible with .NET 5 since it targets `netstandard2.0`
