### ISSUE TITLE
ClientWebSocket properties throw "The method or operation is not implemented" in Unity

### ISSUE THREAD

**Issue by teocomi** [graphql-dotnet/graphql-client#318]
Hiya,

I found that [these lines](https://github.com/graphql-dotnet/graphql-client/blob/master/src/GraphQL.Client/Websocket/GraphQLHttpWebSocket.cs#L408-L409) in `GraphQLHttpWebSocket.cs` throw when registering a subscription in Unity (running on windows with .NET Stabdard 2.0) with message "The method or operation is not implemented".

Not sure what the best way to fix it is. Maybe they should be wrapped in a try/catch statement to handle the `Blazor WebAssembly` case as well.

Cheers!

**Comment by sungam3r** [comment]
It is by design according to the comment:
>  // the following properties are not supported in Blazor WebAssembly and throw a PlatformNotSupportedException error when accessed

**Comment by teocomi** [comment]
Hey @sungam3r I'm not sure I understand,  think the point of the [if statement  above](https://github.com/graphql-dotnet/graphql-client/blob/master/src/GraphQL.Client/Websocket/GraphQLHttpWebSocket.cs#L405) is to prevent the exception from being thrown?

**Comment by rose-a** [comment]
@teocomi could you try to work out what "OSPlatform" your code runs in? Maybe post the properties of `System.Runtime.InteropServices.RuntimeInformation` of your environment?

Maybe your environment is something else than `"BROWSER"`... unfortunately the the documentation for those platform values is not very extensive...

**Comment by teocomi** [comment]
The OSPlatform unfortunately shows as `OSPlatform.Windows`, and these the `RuntimeInformation ` values:

![image](https://user-images.githubusercontent.com/2679513/103443961-fde04380-4c5b-11eb-9b3a-f20b2cf23523.png)

Hence my suggestion to use a try/catch...

**Comment by rose-a** [comment]
We circled arround this topic a while back... but in the light of the bad documentation (if any) on those *OSPlatform* values I think swallowing this exception will be the way to go... especially as it's not possible to set those anyway on unsupported platforms...
