### ISSUE TITLE
Custom HttpClient for GraphQLClient

### ISSUE THREAD

**Issue by OneCyrus** [graphql-dotnet/graphql-client#32]
It would be very helpful to supply my own instance of HttpClient to the GraphQLClient constructor. Currently it allows to supply a HttpMessageHandler. But this way I can't specify authorization tokens.

Or is there another way to acomplish this?

**Comment by deinok** [comment]
Well, if you specify better what is your use case i can give help.

If you need to add a Header you can use something like this:
```csharp
var graphClient = new GraphQLClient("https://api.github.com/graphql");
graphClient.DefaultRequestHeaders.Add("Authorization", $"bearer {gitHubAccessToken}");
//var test = await graphClient.GetIntrospectionQueryAsync();
var request = new GraphQLRequest
{
    Query = @"query { viewer { login } }"
};
var test = await graphClient.PostAsync(request);
```

IDK if this solves your issue or you have a better idea of how to implement your case

**Comment by OneCyrus** [comment]
thanks that did the trick!

my use case is integration testing a graphql endpoint which is started as a .net core TestServer. it was a bit tricky because it's not an endpoint which is accessible as any other real endpoint.

**Comment by Adebayo-Adesegun** [comment]
I can't add DefaultRequestHeaders with IGraphQLClient, how can this be done, please?

**Comment by ikelds** [comment]
> 
> 
> I can't add DefaultRequestHeaders with IGraphQLClient, how can this be done, please?
> 
> @Version of GraphQL.Client is 3.1.3

Try:

GraphQLHttpClient client = new GraphQLHttpClient("https://example.com/graphql", new NewtonsoftJsonSerializer());
client.HttpClient.DefaultRequestHeaders.Add("Authorization", accessToken);

**Comment by Adebayo-Adesegun** [comment]
> > I can't add DefaultRequestHeaders with IGraphQLClient, how can this be done, please?
> > @Version of GraphQL.Client is 3.1.3
> 
> Try:
> 
> GraphQLHttpClient client = new GraphQLHttpClient("https://example.com/graphql", new NewtonsoftJsonSerializer());
> client.HttpClient.DefaultRequestHeaders.Add("Authorization", accessToken);

I had to use the HttpClient Library to get around this party issue as IGraphQLClient didn't seem to have a direct support for adding Default HTTP Headers, you can try this example code snippet: 

public class ExampleController : Controller
    {

        private readonly HttpClient _httpClient;

        public ExampleController()
        {
            _httpClient = new HttpClient
            {
                BaseAddress = new Uri(_urlHelper.GraphQLUri)
            };
            _httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("bearer", "jbkjsbkjbsdkbksbvksdvbjsvb");
        }

  [HttpPost]
  public async Task<IActionResult> Create(ExampleVM model)
  {
    
var query = new {
                Query = @"mutation quote($quote: QuoteInput!) {
                              quote(quote :$quote) {
                                id,
                                address,
                                message,
                              }
                            }", 

                Variables = new
                {
                    quote = new
                    {
                        active = true,
                        slipFileExtension = ext,
                        slipBase64 = brokingSlipb64,
                        message = model.Message,
                        userId = SignedInDetail.GetUserId(),
                        quoteId = 0,
                        status = 1
                    }
                }
            };

             var json = JsonConvert.SerializeObject(query);
            var data = new StringContent(json, Encoding.UTF8, "application/json");
            var response = await _httpClient.PostAsync("", data);

  }

}

You can just treat it like a normal HTTP request. The GraphQL server endpoint figures the rest out from your structure.

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-client/blob/master/src/GraphQL.Client/GraphQLHttpClientOptions.cs#L49-L53
