### ISSUE TITLE
Cannot receive any data after SubscriptionStream started

### ISSUE THREAD

**Issue by oesebus** [graphql-dotnet/graphql-client#323]
Dear all , 

Iam trying to receive some data from a GraphQL server through Subscription mechanism but my observer stop receiving data just after receiving an empty value . Let me show you some code to help you to understand my point :

//App : .NET Core 3.1 / C#

//The _graphQLClient dependency is injected in the DI in the startup file :

var _graphQLClient = new GraphQLHttpClient("https://xxxxxxxxxxxxx", new NewtonsoftJsonSerializer());
            _graphQLClient.Options.WebSocketEndPoint = new Uri("wss://xxxxxxxxxxxxxx");
            //_graphQLClient.Options.EndPoint = new Uri("https://xxxxxxxxxxxxxxx");
            _graphQLClient.Options.ConfigureWebsocketOptions = (o) => {
                o.SetRequestHeader("api-key", "xxxxxxxxxxxxxxxxxxxx");
                };
            _graphQLClient.Options.UseWebSocketForQueriesAndMutations = true;
            _graphQLClient.InitializeWebsocketConnection();
            _graphQLClient.Options.OnWebsocketConnected += OnWebSocketConnected();

            return _graphQLClient;

BackGroundService logic 

// StartAsync :
  public override Task StartAsync(CancellationToken cancellationToken)
        {
            try
            {
                _subscriptions.Add(_graphQLClient.WebSocketReceiveErrors.Subscribe(e =>
                {
                    if (e is WebSocketException we)
                        _logger.Error($"WebSocketException: {we.Message} (WebSocketError {we.WebSocketErrorCode}, ErrorCode {we.ErrorCode}, NativeErrorCode {we.NativeErrorCode}");
                    else
                        _logger.Error($"Exception in websocket receive stream: {e}");
                }));

                _subscriptions.Add(_graphQLClient.CreateSubscriptionStream<NowOnAirResult>(new NowOnAirRequest().Request)
                                                            .SubscribeSafe(new NowOnAirObserver()));

            }
            catch (Exception ex)
            {
                _logger.Error(ex.Message);
            }
            finally
            {
                Console.WriteLine($"Is Disposed ? {_subscriptions.IsDisposed}");
            }

            return Task.CompletedTask;
        }

My Observer :
public class NowOnAirObserver : IObserver<GraphQLResponse<NowOnAirResult>>
    {
        public void OnCompleted()       
        {
            Console.WriteLine($"The provider has finished sending push-based notifications");
        }

        public void OnError(Exception error)
        {
            Console.WriteLine($"An exception is raised by the observer => {error.Message}");
        }

        public void OnNext(GraphQLResponse<NowOnAirResult> value)
        {
            if (value.Data is null)
                Console.WriteLine($"RECEIVE : {value.Data}");
            else
            Console.WriteLine($"RECEIVE {value.Data.item_id}");
        }
    }

I can connect to the server successfully . But after few seconds , the connection is cloded and the OnCompleted Method is called by the Observer.

Not possible to receive any data but with the same query with Node.JS i can get my expected results

Many thanks for your help ,

Ismael

**Comment by ZiedMayel** [comment]
@oesebus 
I have a similar problem : 
**### GraphQL.Client.Http.Websocket.GraphQLWebsocketConnectionException: {"type":"connection_error","payload":{"message":"Cannot convert undefined or null to object"}}**

Did you find a solution for your problem? Or do you have any clue about my error described above? 

Thanks ..

**Comment by oesebus** [comment]
@ZiedMayel  Could you share your code to help us to understand what's the problem  ? Thanks

**Comment by ZiedMayel** [comment]
@oesebus 
this is my code

**Initialize the client:** 

`//
            //initialize graphQl client
            //
            _graphQlHttpClient =
                new GraphQLHttpClient(new Uri(chargeTripSetting.Value.BaseUrl), new SystemTextJsonSerializer());

            _graphQlHttpClient.HttpClient.DefaultRequestHeaders.Add("x-client-id", "segfsegwgwgwegweg");
            
            //
            //set up Websocket endpoint
            //
            _graphQlHttpClient.Options.WebSocketEndPoint = new Uri("wss://api.myapi.io/graphql");

            _graphQlHttpClient.Options.ConfigureWebsocketOptions = options =>
            {
                options.SetRequestHeader("x-client-id", "segfsegwgwgwegweg");
            };

            _graphQlHttpClient.Options.UseWebSocketForQueriesAndMutations = false;
            //
            //subscribe to some Websocket observables
            //
            _graphQlHttpClient.WebSocketReceiveErrors.Subscribe(OnWebSocketReceivesErrors);

            _graphQlHttpClient.WebsocketConnectionState.Subscribe(OnWebSocketConnectionStateChanged);`

**Subscription** : 

`
                string routeUpdateSubscriptionQuery = await GraphQlUtils.ReadQuery(SubscriptionNames.RouteUpdate);

                GraphQLHttpRequest routeUpdateSubscriptionRequest = new GraphQLHttpRequest
                {
                    Query = routeUpdateSubscriptionQuery,
                    OperationName = "opName",
                    Variables = new { id = response.Data.NewRouteId }
                };

                IObservable<GraphQLResponse<RouteUpdateSubscriptionResponse>> subscriptionStream = _graphQlHttpClient
                    .CreateSubscriptionStream<RouteUpdateSubscriptionResponse>(routeUpdateSubscriptionRequest);

                _streamSubscription = subscriptionStream.Subscribe(OnNext);
`

**Comment by ZiedMayel** [comment]
@oesebus 
I fixed the issue by initializing the web socket connection payload. In my case I need to set a Header "x-client-id" and it is needed to be set like that and not like you described in your first post : 
this is not working
´
_graphQLClient.Options.ConfigureWebsocketOptions = (o) => {
o.SetRequestHeader("api-key", "xxxxxxxxxxxxxxxxxxxx");
};
this is working
´
var headers = new Dictionary<string, string>();
            
            headers.Add("api-key", "THE_API_KEY");

            _graphQlHttpClient.Options.ConfigureWebSocketConnectionInitPayload = options => headers;
´

**Comment by oesebus** [comment]
@ZiedMayel  Thanks a lot !
