### ISSUE TITLE
Unity / Mono  - ClientCertificates NotImplementedException

### ISSUE THREAD

**Issue by dwelch2344** [graphql-dotnet/graphql-client#324]
Hey @rose-a, new to .NET / Unity but I think I'm running into the #318 **ClientWebSocket issue** still with 3.2.1 - same scenario as OP but on Mac. The difference I'm seeing is that I'm getting a `System.NotImplementedException` instead of a `PlatformNotSupportedException` so the try / catch doesn't do anything. 

I can trap the Exception to print it out, and it ends up looking like this: 
```
Subscription Exception Handler - System.NotImplementedException: The method or operation is not implemented.
  at System.Net.Http.HttpClientHandler.get_ClientCertificates () [0x00000] in <7ebf3529ba0e4558a5fa1bc982aa8605>:0 
  at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.InitializeWebSocket () [0x000b5] in <a79a8e26596a4659b989a8e130b9b057>:0 
  at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket+<>c__DisplayClass27_0`1+<<CreateSubscriptionStream>b__5>d[TResponse].MoveNext () [0x00148] in <a79a8e26596a4659b989a8e130b9b057>:0 
UnityEngine.Debug:Log(Object)
<>c:<DoIt>b__4_0(Exception) (at Assets/Api.cs:55)
GraphQL.Client.Http.Websocket.<>c__DisplayClass27_0`1:<CreateSubscriptionStream>b__3(Exception)
System.Reactive.BasicProducer`1:Subscribe(IObserver`1)
GraphQL.Client.Http.Websocket.<<CreateSubscriptionStream>b__5>d:MoveNext()
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start(<<CreateSubscriptionStream>b__5>d&)
GraphQL.Client.Http.Websocket.<>c__DisplayClass27_0`1:<CreateSubscriptionStream>b__5(IObserver`1)
System.ObservableExtensions:Subscribe(IObservable`1, Action`1)
Api:DoIt() (at Assets/Api.cs:59)
CharacterInventory:TestEquip() (at Assets/CharacterInventory.cs:38)
UnityEngine.EventSystems.EventSystem:Update() (at /Applications/Unity/Hub/Editor/2019.4.18f1/Unity.app/Contents/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/EventSystem.cs:377)
```

Is it possible that the certificate library that I've got configured is throwing a different exception than other runtimes or something? Would it be safe to catch both exceptions? 

Any help would be appreciated :) 

From the Java / Node world by trade, so excuse my sloppy code. Included for reference tho ;)  

```c#
public class Api { 
    private GraphQLHttpClient client;




    public class Response
    {
        public Post postAdded { get; set; }
    }


    public class Post
    {
        public string author { get; set; }
        public string comment { get; set; }
    }

    public void Start()
    {
        client = new GraphQLHttpClient("http://localhost:4000/graphql", new NewtonsoftJsonSerializer());
        
    }

    public bool DoIt()
    {
        Debug.Log("About to start?");
        var query = new GraphQL.GraphQLRequest
        {
            Query = @"subscription {
                postAdded{
                author
                comment
                }
            }"
        };

            //IObservable<GraphQL.GraphQLResponse<Response>> subscriptionStream = client.CreateSubscriptionStream<Response>(query);
            IObservable<GraphQL.GraphQLResponse<Response>> subscriptionStream = client.CreateSubscriptionStream<Response>(query, ex =>
            {
                Debug.Log("Failed?!? " + ex);
                throw ex;
            });

            var subscription = subscriptionStream.Subscribe(response =>{
                Debug.Log("Got a response");
                Response thing = response.Data;
                Debug.LogFormat("{0} by {1}", thing.postAdded.comment, thing.postAdded.comment);
            });

            Debug.Log("Opened? " + subscription);
    }
}
            
```

**Comment by dwelch2344** [comment]
For reference, I believe this might be related - https://github.com/mono/mono/issues/8644

**Comment by dwelch2344** [comment]
Sweet, was just able to confirm the general idea is right. Completely new to Visual Studio IDE, but was able to clone the repo and build locally to resolve my issue. Not sure how to make VS happy with the missing ClientCertificates functions (and it's late so I'm lazy) but I did comment out the entire directive block and rebuilt the lib + my game with success.  


Essentially, cutting the following made my local scenario work. Clearly not a good plan for the future, but would adding the additional `NotImplemented` catch blocks be a problem here? 
https://github.com/graphql-dotnet/graphql-client/blob/14f30c99c65d00f0be681c9e0f70fce22ee964a5/src/GraphQL.Client/Websocket/GraphQLHttpWebSocket.cs#L383-L426

**Comment by rose-a** [comment]
Hi @dwelch2344, thanks for raising this issue.

I think it'd be fine to handle `NotImplementedException` the same way as `PlatformNotSupportedException` in this case (in a way "PlattformNotSupported" implicates "NotImplemented"). @sungam3r any thoughts?

I'd welcome a PR, I'm quite occupied at the moment.

**Comment by sungam3r** [comment]
Right.

**Comment by dwelch2344** [comment]
Sweet - on it now!

**Comment by dwelch2344** [comment]
@rose-a @sungam3r  PR opened, let me know if you'd like adjustments or I should adjust anything else. First C# PR so definitely new territory :)  thanks!

**Comment by dwelch2344** [comment]
@rose-a @sungam3r Looks like the PR was approved but a test failed. Was that related to my changes? Anything I can do to help out? Thanks in advance :)

**Comment by sungam3r** [comment]
I am not familiar with the tests of this project. Ping @rose-a

**Comment by dwelch2344** [comment]
Circling back on this. @rose-a thoughts? Anything I can do to help this along?

**Comment by rose-a** [comment]
Hi, sorry for not responding... The tests currently have a stability problem (see #161), I don't think the failing test is due to your changes.

I'll try to merge and release this later today... sorry again for the delay!
