### ISSUE TITLE
Make GraphQL requests from command line with curl

### ISSUE THREAD

**Issue by TechGeeky** [graphql-dotnet/graphql-client#328]
I recently started working with `GraphQL` so I am kinda confuse on how to make `GraphQL` requests from command line with curl. I have built a simple application by following an example from [here](https://github.com/graphql-dotnet/examples/tree/master/src/AspNetCore) and everything works fine from the UI playground. This is how my request looks like from the UI playground - 

[![enter image description here][1]][1]

After I hit execute button in middle everything works for me. Now I am confuse on how to convert this request into curl call which I can use from the command line? I am mainly confuse on how to use `QueryVariables` in my curl request. Any example basis on my example will help me understand better.

Below is how I am using my `Query` - 

**TitanQuery.cs**

```csharp
    Field<HumanType>(
        "request",
        arguments: new QueryArguments(
            new QueryArgument<NonNullGraphType<InputType>> { Name = "data", Description = "some stuff" }
        ),
        resolve: context => data.GetHumanByIdAsync(context.GetArgument<ContainerRequest>("data"))
    );
```

Below is how my `Schema` looks like - 

**TitanSchema.cs**

```csharp
    public TitanSchema(IServiceProvider provider) : base(provider)
    {
        Query = provider.GetRequiredService<TitanQuery>();
    }
```

My `InputType` and `HumanType` class are pretty simple and straight forward and everything works fine end to end through UI playground.

Below is my `Startup` class.

```csharp
 public Startup(IHostingEnvironment env) {
   var builder = new ConfigurationBuilder()
     .SetBasePath(env.ContentRootPath)
     .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
     .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
     .AddEnvironmentVariables();
   Configuration = builder.Build();
 }

 public IConfigurationRoot Configuration { get; }

 public void ConfigureServices(IServiceCollection services) {
   // graphql stuff
   services.AddSingleton <DummyData> ();
   services.AddSingleton <TitanQuery> ();
   services.AddSingleton <HumanType> ();
   services.AddSingleton <InputType> ();
   services.AddSingleton <FilterType> ();
   services.AddSingleton <ISchema, TitanSchema> ();

   services.AddGraphQL(options => {
       options.EnableMetrics = true;
     })
     .AddErrorInfoProvider(opt => opt.ExposeExceptionStackTrace = true)
     .AddSystemTextJson()
     .AddUserContextBuilder(httpContext => new GraphQLUserContext {
       User = httpContext.User
     });

     // old legacy stuff here
 }

 public void Configure(IApplicationBuilder app, IHostApplicationLifetime lifetime) {
   // old legacy middlewares (nothing related to graphql middleware yet)
   ....


   if (IS_LOCAL_DEVELOPMENT)
     app.UseDeveloperExceptionPage();

   // add http for Schema at default url /graphql
   app.UseGraphQL <ISchema> ();
   // use graphql-playground at default url /ui/playground
   app.UseGraphQLPlayground();
 }
```

Can someone help me on how my curl request will look like for my above request in UI playground? And do I need any other change to have my curl request working or whatever I have will work fine?

  [1]: https://i.stack.imgur.com/5PmMw.png

**Comment by rose-a** [comment]
The question is what such a tool could provide or do better as sending a post request with the hand-crafted (or prepared in a file) JSON body supplied by @joemcbride.

If you use a "IDE-style" tool like Playground or Altair (at least for the latter there's a standalone version available), you get auto-completion, error-checking and live-documentation... that's not feasible on the commandline.

IMO joe's comment answered the OPs request, and I don't consider a GraphQL cli tool as a scope for this library.

**Comment by sungam3r** [comment]
Obviously in environments where UI is not available - CLI/CI. I'm OK to close this issue.

**Comment by imolorhe** [comment]
FWIW Altair allows you to copy the request as cURL, so you could try that (you can also copy the request as curl from the chrome dev tools network tab btw)
<img width="358" alt="Screenshot 2021-03-06 at 11 24 22 PM" src="https://user-images.githubusercontent.com/4608143/110222535-2cd09b00-7ed3-11eb-85c5-31e8160bedce.png">
