### ISSUE TITLE
Disposing HttpClient in GraphQLHttpClient

### ISSUE THREAD

**Issue by OleksandrTaranSecurrency** [graphql-dotnet/graphql-client#329]
I wonder if there is any good reason to call Dispose on the HttpClient in the GraphQLHttpClient.

https://github.com/graphql-dotnet/graphql-client/blob/5356743fc186dcdf2be29c7777f46e0e10b6d46f/src/GraphQL.Client/GraphQLHttpClient.cs#L198

There are several articles in the internet that describe why it's bad. Like this one https://www.aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

**Comment by rose-a** [comment]
Good question... is there any good reason to dispose of `GraphQLHttpClient` within a running application?

It's propably more a thing of "cleaning up after itself" (a object should clean up all the resources it grabbed when it's disposed of). 
The case where this theory currently fails is when a `HttpClient` is passed into `GraphQLHttpClient` using the constructor.

**Comment by OleksandrTaranSecurrency** [comment]
> The case where this theory currently fails is when a HttpClient is passed into GraphQLHttpClient using the constructor.
This is actually the reason why I posted this question.

Theoretically you can check if HttpClient was instantiated internally or passed as constructor dependency and then either dispose it or do nothing.

We did run into socket exhaustion and the only place where dispose is called  on HttpClient is GraphQLHttpClient.

**Comment by rose-a** [comment]
Why do you dispose of `GraphQLHttpClient`?

**Comment by OleksandrTaranSecurrency** [comment]
Well I think it's absolutely logical to call dispose on the objects that implement IDisposible, however It's not me, it's DI container.

`
builder.Services.AddScoped<IGraphQLClient>(s => new GraphQLHttpClient(finP2POptions.GraphQlUrl, new NewtonsoftJsonSerializer()));
`

Since GraphQLHttpClient is IDisposable it will be disposed when a web request is done.

Alternatively we could try a singleton but according to the article that I posted above we might get DNS issues. It's highly unlikely but still possible.

I think it still makes  sense to dispose HttpClient only when it was created inside GraphQLHttpClient, otherwise(if it's passed as a constructor dependency) it should be the responsibility of the calling code to decide when the httpclient should be disposed.

**Comment by rose-a** [comment]
> Well I think it's absolutely logical to call dispose on the objects that implement IDisposible

I totally support that, but there is that strange behaviour of `HttpClient` which makes it hard to handle...

> I think it still makes sense to dispose HttpClient only when it was created inside GraphQLHttpClient

Correct.

But the way you configure `GraphQLHttpClient` in your DI container it actually creates a new `HttpClient` since you don't pass one in the constructor...

**Comment by rose-a** [comment]
The disposing behavoir has been fixed in [v3.2.3](https://github.com/graphql-dotnet/graphql-client/releases/tag/v3.2.3).

Please make sure you configure your DI container to inject `HttpClient` into `GraphQLHttpClient`.
