### ISSUE TITLE
[dotnet-graphql-client] - Dotnet Global Tools

### ISSUE THREAD

**Issue by deinok** [graphql-dotnet/graphql-client#33]
Creation of a Global Tools to send queries

**Comment by sungam3r** [comment]
In principle, the task is understandable, but the value of such a utility is doubtful. @rose-a What do you think?

**Comment by rose-a** [comment]
Don't think its necessary... why would you use a dotnet tool to query a GraphQL API? There are plenty of good GraphQL clients (Insomnia, Altair, ...) which feature autocompletion etc...

So yeah, closing this ;)

**Comment by sungam3r** [comment]
Indeed, there are plenty of good GraphQL clients.
The only reason I can think of - CI cases without UI, but I’m sure that for this case something already exists.
