### ISSUE TITLE
Headers not passed for Subscription

### ISSUE THREAD

**Issue by Archuna** [graphql-dotnet/graphql-client#334]
Hi ,
   I was able to pass headers for query and mutation from grapqhl client and validate the token in the server.
But for Subscription , i was not able to send the headers. My server showed that payload was null.

var graphQLClient = new GraphQLHttpClient("http://localhost:5000/graphql/", new NewtonsoftJsonSerializer());
graphQLClient.HttpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer eyJhbGc.....");

This is how i send headers to server . Is there any other way to send header details to server for subscription.

Thanks in advance.

**Comment by rose-a** [comment]
There are 2 properties (`ConfigureWebsocketOptions` and `ConfigureWebSocketConnectionInitPayload`) in the [GraphQLHttpClientOptions](https://github.com/graphql-dotnet/graphql-client/blob/dd418d16b690e503f054c5c355927cd91e8188d6/src/GraphQL.Client/GraphQLHttpClientOptions.cs#L60) class for that.

It depends on how your server expects the authorization info to be transmitted...

**Comment by Archuna** [comment]
@rose-a I was able to authenticate in server using ConfigureInitPayload option. But then I failed to get response for the Subscription. The Subscription resolver in server was not called at all.
I have added header options in the following way.
`var graphQLHttpClient = new GraphQLHttpClient("my-server-uri", new NewtonsoftJsonSerializer());
                graphQLHttpClient.HttpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {token}");
                graphQLHttpClient.Options.ConfigureWebSocketConnectionInitPayload = (GraphQLHttpClientOptions options) =>
                {
                    return new
                    {
                        Authorization = $"Bearer {token}"
                    };
                };`

Should anything else be added in addition to this to pass the call further to the Subscription's resolver.

Thanks.

**Comment by rose-a** [comment]
That depends on how your server implements it...

Here's the example from the Apollo docs: https://www.apollographql.com/docs/react/data/subscriptions/#5-authenticate-over-websocket-optional

**Comment by Archuna** [comment]
@rose-a , My server is implemented using Hotchocalate. When I disable the authentication part in server, I could get the subscription response in the client from the server. 
Only when I enable Authentication this problem comes. This is the reason I asked you if any additional client options needs to be given.

**Comment by Archuna** [comment]
@rose-a . After updating graphql.client version, I was able to find that the token gets authenticated and then moves to resolver's implementation in server. Though the server sends a filled response, i found that the client is receiving an empty response.
Can u help on this.

**Comment by Archuna** [comment]
@rose-a  , My issue is solved. There was an issue on server side.
