### ISSUE TITLE
Queries return null value for number types (float, int) will generate JsonSerializationException

### ISSUE THREAD

**Issue by gregorypierce** [graphql-dotnet/graphql-client#338]
Recreated this using the StarWars source for ease of testing/debugging

If you perform the following query on the SWapi data source

`  var speciesRequest = new GraphQLHttpRequest {
            Query = @"query AllSpecies {
                                            allSpecies {
                                                species {
                                                name
                                                classification
                                                averageLifespan
                                                }
                                            }
                                        }",
            OperationName = "AllSpecies"                                            
        };
`

You will have times where attributes like averageLifespan can be null. If you build out a typical response:

`    using System.Collections.Generic;

    
    public class AllSpeciesResponse
    {
        public SpeciesContent allSpecies { get; set; }

        public class SpeciesContent
        {
            public List<SpeciesType> species {get; set; }

            public class SpeciesType{
                public string name {get;set;}
                public string classification {get;set;}
                public int averageLifespan {get;set;}
            } 
        }
    }`

An exception will be generated as the serializer will be trying to Cast the null into an Int/Float.

**Comment by rose-a** [comment]
You should use a nullable integer in this case. If the value can be `null`, then it shouldn't be automatically converted into an integer, because you can't tell the placeholder value apart from a real one.
