### ISSUE TITLE
How do consume query that returns array of objects ?

### ISSUE THREAD

**Issue by mveselov-de** [graphql-dotnet/graphql-client#345]
I have following query in schema

```
type Query {
findDuplicateScenes(distance: Int): [[Scene!]!]!
}
```

Now, I'm trying to call SendQueryAsync like so

```
  static void Main(string[] input_args)
        {
          //Building the list
           var scene_list=GetResult().Result;        
        }
 
        static async Task<IList<IList<Scene>>> GetResult()
        {
  var test_result = await graphQLClient.SendQueryAsync<IList<IList<Scene>>>(test_query);
            return test_result.Data;
}

```
This fails during runtime

> Innermost exception Newtonsoft.Json.JsonSerializationException : Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IList1[System.Collections.Generic.IList1[]]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
> To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.

Any suggestions how to fix this ?

**Comment by rose-a** [comment]
You're missing the "root" object which needs to have a property `findDuplicateScenes` which is of type `IList<IList<Scene>>`...

Try this:

```csharp
static async Task<IList<IList<Scene>>> GetResult()
{
    var test_result = await graphQLClient.SendQueryAsync(test_query, 
        () => new { findDuplicateScenes = new List<List<Scene>>() });
    return test_result.Data.findDuplicateScenes;
}
```

**Comment by mveselov-de** [comment]
Thanks! 

I also had to change GetResult slightly to

` static async Task<List<List<Scene>>> GetResult()`

Without this it failed trying to convert IList to List.
