### ISSUE TITLE
Unable to deserialize from ListGraphType to List

### ISSUE THREAD

**Issue by jeffrfinn** [graphql-dotnet/graphql-client#351]
Hi

I'm trying to call a a query and get a list of objects back with
`            var graphQlResponse = await graphQlHttpClient.SendQueryAsync<List<MyObject>>(request);`

I get the following error using System.Text.Json & something similar using Newtonsoft
`System.Text.Json.JsonException : The JSON value could not be converted to System.Collections.Generic.List`1[Event.Models.SportsEvent]. Path: $.data | LineNumber: 0 | BytePositionInLine: 9.`

I have tried using Newtonsoft & System.Text.Json serializers

if I deserialize the object to a dynamic or an object I see that the structure is like this
``            var graphQlResponse = await graphQlHttpClient.SendQueryAsync<dynamic>(request);``

`ValueKind = Object : "{"myObject":[{"id":"8e6281da-78b6-4592-9ef3-44274f6e7e5b","name":"Name13b61645-6da7-4ad5-b0ca-2b284e70928e"},{"id":"f92b0b54-43d6-41f3-ac49-6050e3aa8786","name":"Name77055403-644b-4737-857f-1c6928848bdd"},{"id":"e8452b90-6cf8-4260-8330-25ded8562aec","name":"Name80d2c0db-b114-4272-bcae-657b35601ff0"}]}"
`
I was poking around with the debugger and I see that the parent type is a JsonDocument from System.Text.Json and I think that this is putting an extra pair of {} around the object that is stopping it from being deserialized correctly.

If I remove the outer {} I can convert the json to the correct c# object

The NuGet packages that I'm usign are 
`<PackageReference Include="GraphQL.Client" Version="3.2.4" />
        <PackageReference Include="GraphQL.Client.Serializer.Newtonsoft" Version="3.2.4" />
        <PackageReference Include="GraphQL.Client.Serializer.SystemTextJson" Version="3.2.4" />`

And I'm using .Net Core 3.1

**Comment by jeffrfinn** [comment]
I found something that works, in the issue 
[https://github.com/graphql-dotnet/graphql-client/issues/345](https://github.com/graphql-dotnet/graphql-client/issues/345)

By using GraphQL.Client.Abstractions I can call my query like this
`            var graphQlResponse = await graphQlHttpClient.SendQueryAsync(request, () => new { myObject = new List<MyObject>()} );
`
and it deserializes correctly into my expected type.

I'm not sure to close this or not. I think the client should be able to deserialize a graphql response to the correct type even if it has a list. I have used the same method for single objects and it works fine.

**Comment by rose-a** [comment]
The only way I know this works is when deserializing to `JObject` using Newtonsoft, although you'd have to access everything by its path again later in your code.

The `dynamic` type has been explicitely eliminated in version 2.0 because it does not work with various runtimes.

The solution you found is the way to go.
