### ISSUE TITLE
Basic query question/advice

### ISSUE THREAD

**Issue by aromanarguello** [graphql-dotnet/graphql-client#36]
Hi, 

Thank you for creating such a good client for GraphQL calls. Currently, I am attempting to implement the client at my job since we are migrating our Automation calls from REST calls to GraphQL calls to hit the new GraphQL server. I have been trying to use the client to first obtain an Auth Token, which I need in order to proceed to another call. 
At the moment this is how I am proceeding with the call. I am not well versed in Async performance specially since C# is an Synchronous language. 

I don't seem to be returning anything. I was hoping you could guide me as to what I am doing wrong or how to better use the client to hit our server.

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using GraphQL.Client;
using GraphQL.Common.Request;
using GraphQL.Common.Response;

```

Method:
```
    public static async Task<GraphQLResponse> GetNewToken(string email, string password)
        {
            var tokenRequest = new GraphQLRequest
            {
                Query = @"
                  {
                    getUserToken(username: $email , password: $password )
                  }"
            };
            var endPoint = new GraphQLClient(ApiEndpointURI);
            var authToken = await endPoint.GetAsync(tokenRequest);
            Console.WriteLine(authToken.Data);
            return authToken.Data;
        }
```

I am making the call on a sandbox environment. When I Console.WriteLine VS outputs: 
```
System.Threading.Tasks.Task`1[GraphQL.Common.Response.GraphQLResponse]
```
When I go into debugger mode and I step into the function. I step over to `authToken.Data` and get the following error: 
`error CS0234: The Type or namespace name 'Common' does not exist in the namespace...`
I feel that much of this issue also falls on me not understanding how the username and password are interpolated correctly.

I really appreciate your assitance with the issue. Best!

**Comment by deinok** [comment]
```csharp
    public static async Task<GraphQLResponse> GetNewToken(string email, string password)
        {
            var tokenRequest = new GraphQLRequest
            {
                Query = @$"
                  {
                    getUserToken(username: {email} , password: {password})
                  }"
            };
            var endPoint = new GraphQLClient(ApiEndpointURI);
            var authToken = await endPoint.GetAsync(tokenRequest);
            Console.WriteLine(JsonConvert.SerializeObject(authToken));
            return authToken.Data;
        }
```

Try this and tell me what is Writed in the Console

**Comment by aromanarguello** [comment]
deinok,

Thank you for the prompt response. I have been playing around with adding `$` after the `@`, however this produces many other errors regarding missing sintax or expecting `}`, invalid member declarators, and this error: `Keyword, identifier, or string expected after verbatim specifier: @ ` . It wont allow me to add the `$`.

**Comment by deinok** [comment]
Well, in fact, Format that string in order to put the variables inside the
string

**Comment by aromanarguello** [comment]
I hard-coded the email and password for right now in the correct way as you suggested. It got it working. I am getting the token. 

Gracias por tu ayuda!
