### ISSUE TITLE
The remote party closed the WebSocket connection without completing the close handshake.

### ISSUE THREAD

**Issue by LeoReubelt** [graphql-dotnet/graphql-client#361]
I have been trying to create a websocket connection with aws using GraphQL.Client.  I can send queries and mutations successfully, but when it comes to creating the websocket connection, I get the following...  

subscription stream error 'The remote party closed the WebSocket connection without completing the close handshake.' - '0' 
subscription stream error 'The remote party closed the WebSocket connection without completing the close handshake.' - '0' 
subscription stream error 'The remote party closed the WebSocket connection without completing the close handshake.' - '0' 
subscription stream error 'The remote party closed the WebSocket connection without completing the close handshake.' - '0' 
subscription stream error 'The remote party closed the WebSocket connection without completing the close handshake.' - '0' 
subscription stream error 'The remote party closed the WebSocket connection without completing the close handshake.' - '0' 

I have seen other issues both here and various other places, but I have yet to find a fix that does not require building my own solution.  So if this is something that we can work through, that would be great.  If not, I will build my own. Here are the basics of what I am doing.

```
  CognitoAWSCredentials credentials = user.GetCognitoAWSCredentials(identityPoolId, region);
  AmazonAppSyncClient appSyncClient = new AmazonAppSyncClient(credentials);

  GetGraphqlApiResponse response = await appSyncClient.GetGraphqlApiAsync(new GetGraphqlApiRequest()
  {
      ApiId = appId
  });

  var api = response.GraphqlApi;

  Uri realTimeUri = new Uri(api.Uris["REALTIME"]);

  var headers = new AppSyncHeaders
  {
      Host = realTimeUri.Host,
      Authorization = accessToken
  };

  var realTimeUriWithAuth = new Uri(realTimeUri
      + $"?header={Convert.ToBase64String(Encoding.UTF8.GetBytes(JsonSerializer.Serialize(headers)))}"
      + "&payload=e30=");

  GraphQLHttpClient client = new GraphQLHttpClient(realTimeUriWithAuth, new NewtonsoftJsonSerializer());

  var appDataRequest = new GraphQLRequest(@"subscription {onCreateAppData {id pageData pageName}}");

  subscriptionStream = client.CreateSubscriptionStream<AppDataSubscriptionResult>(appDataRequest, ex =>
  {
      Debug.WriteLine($"subscription stream error '{ex.Message}' - '{ex.ErrorCode}' ");
  });

  subscription = subscriptionStream.Subscribe(response =>
  {
      Debug.WriteLine($"app data '{response.Data.onCreateAppData}'");
  });
```

**Comment by menkari** [comment]
Did you have any luck with this @LeoReubelt ?? I've been banging my head against the wall to get anything back from what I would consider to be a straightforward implementation with Subscriptions?

**Comment by LeoReubelt** [comment]
Thanks for asking @menkari.  No, I gave up and ended up doing it without graphql-client.  I will close this issue.
