### ISSUE TITLE
Using from .NET Framework 4.6.2

### ISSUE THREAD

**Issue by dlopezpl** [graphql-dotnet/graphql-client#365]
Hi
I'm sure this is a rare case scenario now a days, but I need to integrate a GraphQL API inside a .NET Framework 4.6.2 MVC web application.
To do that, I created a .NET Standard 2.0 class library project, added GraphQL.Client 3.2.4 package to it and finally referenced my library from the MVC app.
When trying to make a SendQueryAsync it hangs there an nothing happens, the await never returns. 
I tested the same library but referenced from a simple .NET Framework 4.6.2 console application and it works perfectly. 
Any clues on why that could be happening?
Thanks

**Comment by rose-a** [comment]
why do you create a "library wrapper project" for GraphQL.Client? This should work without any tinkering (I'm using this quite heavily myself...)

Maybe post your code how you setup and use `GraphQLHttpClient`?

**Comment by dlopezpl** [comment]
Thanks a lot for your answer.
You´re right. I did that because I thought it was necessary for .Net 4.6.2 but now I referenced it directly from .Net 4.8 without any trick.

The issue I had was related to the way I was using from a synchronous method. When the method is consumed from an MVC controller the value returned this way, entered in a deadlock:

`return graphQLClient.SendQueryAsync<CountryQueryResponse>(request).Result;`

If instead I return it using a TaskFactory, it worked OK.

```
var graphQLResponse = AsyncHelper.RunSync<GraphQL.GraphQLResponse<CountryQueryResponse>>(
                    () => graphQLClient.SendQueryAsync<CountryQueryResponse>(request)
                );
```

AsyncHelper class:
`class AsyncHelper
    {
        private static readonly TaskFactory _taskFactory = new
            TaskFactory(CancellationToken.None,
                        TaskCreationOptions.None,
                        TaskContinuationOptions.None,
                        TaskScheduler.Default);

        public static TReturn RunSync<TReturn>(Func<Task<TReturn>> task)
        {
            return _taskFactory.StartNew(task)
                                .Unwrap()
                                .GetAwaiter()
                                .GetResult();
        }
    }`

**Comment by rose-a** [comment]
Maybe read this Microsoft article for some ideas on how to use asyncronous methods in ASP.NET MVC 4: 

https://docs.microsoft.com/en-us/aspnet/mvc/overview/performance/using-asynchronous-methods-in-aspnet-mvc-4

I'll consider this issue resolved...
