### ISSUE TITLE
how to  Including credentials in requests

### ISSUE THREAD

**Issue by hichamlehouedj** [graphql-dotnet/graphql-client#371]
I want to resend cookies with every requiste how do I do that I searched for a long time and didn't find any results

This is an example similar to what I'm looking for in a javascript language with a library `ApolloClient `
```javascript
const client = new ApolloClient({
  uri: 'https://api.example.com',
  cache: new InMemoryCache(),
  // Enable sending cookies over cross-origin requests
  credentials: 'include'
});
```

**Comment by sungam3r** [comment]
Look at https://github.com/graphql-dotnet/graphql-client/issues?q=authorization, for example, https://github.com/graphql-dotnet/graphql-client/issues/330

**Comment by hichamlehouedj** [comment]
> Look at https://github.com/graphql-dotnet/graphql-client/issues?q=authorization, for example, #330

There is no solution to my problem there as you mentioned I want to resend httponly cookies

**Comment by rose-a** [comment]
I think #330 does in fact contain 2 alternative solutions to your problem (either setting `DefaultRequestHeaders` or adding a custom header on a per request basis)

**Comment by hichamlehouedj** [comment]
thank you
I solved the problem with `DefaultRequestHeaders`
