### ISSUE TITLE
Receive a notification when a subscription is ready

### ISSUE THREAD

**Issue by frabe1579** [graphql-dotnet/graphql-client#373]
Is there a way to receive a notification when a subscription is ready?
When I call IGraphQLClient.CreateSubscriptionStream, I receive an IObservable, and when I subscribe to it, the real subscription is started.
However, the subscription is not yet really ready to receive data.
For example, if after a subscription I call a mutation, and that mutation sends a message via the previous subscription, there is a high probability to not receive that message (if not a sufficient delay is passed between subscription registration and mutation sending).
Looking at the code, I think the correct position where to insert a way of notification is [This line](https://github.com/graphql-dotnet/graphql-client/blob/10c22365ebce413ae3c4249518fecbfd415af575/src/GraphQL.Client/Websocket/GraphQLHttpWebSocket.cs#L192).
Or is there any other way?
Thank You

**Comment by rose-a** [comment]
The `.Subscribe()` call returns **after** `await QueueWebSocketRequest(startRequest)` has returned (7 lines below the disposable you get back from `Subscribe()` is returned).

This ensures that a websocket connection has been established, and the `GQL_START` message has been sent, but there is no acknowledgement from the server that it has received and setup the subscription on its side.

This "subscription-ack" message that you're after is neither implemented in the [subscription-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md) which this library currently implements nor in its likely successor [graphql-ws](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md), which is not implemented by this library yet.

The only way I'm aware of how you could make sure that the subscription pipeline is fully established (if you have control over the server) is to make the server send a data packet back as soon as a subscription is created (i.e. by using a `ReplaySubject(1)`) and wait for the subscription to receive that.

**Comment by frabe1579** [comment]
Yes, I agree, the only reliable solution is sending a "ready" message server-side (and I have full control over the server).
Thank you.
