### ISSUE TITLE
Problem running on Blazor Preview

### ISSUE THREAD

**Issue by chanan** [graphql-dotnet/graphql-client#39]
Hi,

I ran the same exact code in a console app (.net Core 2.1.300-preview2-008533) and as a Blazor App (Preview 0.2.0). Console worked fine, but in Blazor:

WASM: Newtonsoft.Json.JsonSerializationException: Error getting value from 'Query' on 'GraphQL.Common.Request.GraphQLRequest'. ---> System.NullReferenceException: Object reference not set to an instance of an object.

Needless to say Query wasn't null and I tried with postQueryAsync as well to verify.

I am guessing that the difference might be that Blazor runs on Mono.

**Comment by deinok** [comment]
Blazor its an untested framework for this.
Also, remember that Blazor its in preview.

I will take a look, and try to fix the issue. But it probably wont be fast :(

**Comment by chanan** [comment]
Yeah, no problem, just wanted to let you know in case its an issue with Mono which will persist after Blazor is released, or used currently by someone using Xamarin.

**Comment by luetm** [comment]
I just ran into this as well. Totally understand, not here to make pressure. But would be awsome if this worked with blazor. Issue seems to be only in the DeserializeObject<>, not the non-generic variant.

**Comment by chanan** [comment]
@luetm Thanks for the link! Yes, same, wanted to use external libraries, but for now till its fixed, just doing the POST myself and using the internal JsonUtil work around. Hopefully it will be fixed in Blazor soon.

**Comment by deinok** [comment]
Guys can you try it again with Blazor 0.3.0 and our latest release?

**Comment by deinok** [comment]
related to https://github.com/mono/mono/issues/7839
