### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by deinok** [graphql-dotnet/graphql-client#4]
Setup a CI for testing and compilation of releases

**Comment by deinok** [comment]
@joemcbride So, we let CircleCI o we change to any other?

**Comment by joemcbride** [comment]
I'm perfectly fine sticking with CircleCI.  The way I've setup the other repos is they push nuget packages to MyGet.org, then there is a manual push to NuGet.org as needed.  This is so you can have a package built for a branch and test it though not pollute NuGet.org with a lot of packages.  Does CircleCI support encrypted credentials in the `.yml` file?

**Comment by joemcbride** [comment]
If you don't need/want to do that then can just close this issue probably.

**Comment by deinok** [comment]
We can set it like environment variables so no password or key exist in the .yml file.

**Comment by deinok** [comment]
CIRCLECI->Settings->BuildSettings->Environment Variables
$MY_GET_API_KEY -> the API Key

The $MY_GET_SOURCE I can set it in the .yml for fast changes
