### ISSUE TITLE
CodeGen from introspection

### ISSUE THREAD

**Issue by OneCyrus** [graphql-dotnet/graphql-client#40]
it would be really great to have codegen support. in the REST/swagger world it's very common to generate the classes from the definition/spec. With the introspection support in graphql and codegen support of roslyn this should be possible as well.

**Comment by deinok** [comment]
Could you close this and move it to: https://github.com/deinok/dotnet-graphql-client

Its in development, and when it will be able to become in production, will be moved to this org or repo

**Comment by deinok** [comment]
Also LGTM

**Comment by OneCyrus** [comment]
ok. thanks!

opened it here: https://github.com/deinok/dotnet-graphql-client/issues/3
