### ISSUE TITLE
Query schema from a local instance / Could not load GraphQL.IDocumentWriter

### ISSUE THREAD

**Issue by StefanKoenigMUC** [graphql-dotnet/graphql-client#406]
Hello,

i'm currently trying to try out a grapqhl instance ,where a graphql schema should be addressed locally (that means, no HTTP request should be mad, instead the locale instance of the schema shall be used).

For that I found the package `GraphQL.Client.LocalExecution` what sounds exactly for the solution I'm looking for, but I'm failing during setup.

When adding dependencies to the project (other graphql deps are:

` <PackageReference Include="GraphQL.Server.All" Version="6.1.0" />`

and the client is added like that:

```
    <PackageReference Include="GraphQL.Client" Version="4.0.2" />
    <PackageReference Include="GraphQL.Client.LocalExecution" Version="4.0.2" />
```

But when I'm starting the application, I'm getting an exception: 

`Could not load type 'GraphQL.IDocumentWriter' from assembly 'GraphQL, Version=5.3.0.0, Culture=neutral, PublicKeyToken=null'."
`

But I don't see the problem there? When additionally adding `GraphQL.Client.Serializer.SystemTextJson` still the same error.

Do you have an idea how to resolve that issue?

Thanks in advance,

**Comment by sungam3r** [comment]
I'm 99% sure that GraphQL.Client 4.x packages are compiled with GraphQL.NET 4.x

**Comment by sungam3r** [comment]
IDocumentWriter was renamed into IGraphQLSerializer in v5.

**Comment by sungam3r** [comment]
https://www.nuget.org/packages/GraphQL.Client.LocalExecution, yep v4

**Comment by StefanKoenigMUC** [comment]
thanks a lot for your efforts!
