### ISSUE TITLE
How to set timeout?

### ISSUE THREAD

**Issue by asebak** [graphql-dotnet/graphql-client#41]

**Comment by deinok** [comment]
you can use the CancellationToken. Are you asking for something like this? -> https://msdn.microsoft.com/es-es/library/system.net.http.httpclient.timeout(v=vs.110).aspx

**Comment by asebak** [comment]
@deinok how do you get access to the httpclient object, I cannot seem to find it in the api provided?

**Comment by asebak** [comment]
Noticed a pull-request was merged to support cancellationtokens, it was never released, any plans to release this, really need that feature.

**Comment by deinok** [comment]
This weekend we will publish the lateast release before start working on
Subscriptions feature

**Comment by graphdb2** [comment]
how can we setup timeout on the http client ?

**Comment by graphdb2** [comment]
Sorry got it working with the latest code 
```
 var httpClient = new HttpClient();
 httpClient.Timeout = new TimeSpan(0, 10, 0);
 var graphQLClient = httpClient.AsGraphQLClient(
 new GraphQLHttpClientOptions {EndPoint = new Uri(config.GraphQlURL)});
```

**Comment by deinok** [comment]
With this https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokensource.cancelafter?view=netframework-4.7.2 you can also  add timeouts per request insted of per client

**Comment by KoenVerbeeck** [comment]
I set the timeout on the httpclient:

```
var httpClient = new HttpClient();
httpClient.Timeout = new TimeSpan(0, 10, 0);

var options = new GraphQLHttpClientOptions { EndPoint = new Uri(GraphQLUri), HttpMessageHandler = new NativeMessageHandler(), };

//var graphQLClient = new GraphQLHttpClient(GraphQLUri, new NewtonsoftJsonSerializer());
var graphQLClient = new GraphQLHttpClient(options, new NewtonsoftJsonSerializer(),httpClient);

graphQLClient.HttpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", result.AccessToken);
```

However, I still get a timeout error (with an OK status code), so this seems to be ignored?

![image](https://github.com/graphql-dotnet/graphql-client/assets/7213731/b35886b5-63e1-47ac-96ae-57a013e6f287)
