### ISSUE TITLE
Change pull request settings 

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-client#415]
I suggest to disable merge and rebase options to keep history more clean.

Before
![изображение](https://user-images.githubusercontent.com/21261007/179343111-e01ffca5-4227-4d9d-8388-2159abdc3c21.png)
After
![изображение](https://user-images.githubusercontent.com/21261007/179343147-448f69db-4b68-4542-b4cf-dfd2bfe8556f.png)

I already changed settings. @rose-a please verify

**Comment by rose-a** [comment]
I'm fine with that 👍
