### ISSUE TITLE
Type Based Deserialization

### ISSUE THREAD

**Issue by PascalSenn** [graphql-dotnet/graphql-client#42]
Hello there

We do face some problems with this client. 
The deserialization happens without reflecting the types properly. 

Let me clear things out:

**Challenge:**
One of the most powerful features of GraphQL are Unions. But unions do have the problem that they are of different types. If we want to store objects of different types in a property we need to wrap them with some kind of abstraction (Likewise an interface). That's given.  
As given by C#'s type system it's not possible to create an instance of an interface. Which obviously makes sense. 
So if we query for union types (or any type basically). We actually need to parse them into the right classes. 

**Solution:**
Newtonsoft provides type based de- / serialization. With the setting `TypeNameHandling.Auto` and a custom `SerializationBinder` it's possible to parse Json based on it's `"$type"` property. 
One thing left. We need to know the types. And this is the most important part of any typesafe graphql client. We do need to *always* query `__typename`. 

**Proposal**
- [ ] decorating every request with __typename on all nodes
- [ ] extending `GraphQLClientOptions` by a property `TypeNameRegister`. 
- [ ] creating TypeNameRegister  
```csharp    
    public interface ITypeNameRegister {
          Dictionary<string, Type> {get; set;}
          
          /// <summary>
          /// Registers a type for deserialization
          /// </summary>
          /// <param name="schemaTypeName">Name of the type in the schema (property __typename)</param>
          /// <param name="type">The type to parse the object to</param>
          void RegisterType(string schemaTypeName, Type type);
        
          /// <summary>
          /// Registers a type for deserialization
          /// </summary>
          /// /// <param name="schemaTypeName">Name of the type in the schema (property __typename)</param>
          /// <typeparam name="Type">The type to parse the object to</typeparam>
          void RegisterType<Type>(string schemaTypeName)

    }
```

- [ ] creating a TypeNameSerializer and a TypenameSerialization Binder
- [ ] automatically search for know types and add the `"$type"` property for the deserialization. 
```csharp
  // something like this:       
       GraphQLResponse response; 
       ....
        
            foreach (var typeToken in response.Data.SelectTokens("$..*.__typename"))
            {
                if (typeToken is JToken token)
                {
                   // that will be based on the dictionary in the actual implementation
                    if (TypenameSerializationBinder.KnownTypes.FirstOrDefault(x => x.Name == token.Value<string>()) is Type type)
                    {
                        token.Parent?.Parent?.First?.AddBeforeSelf(new JProperty("$type", type.Name));
                    }
                }
            }
        
```

**Comment by PascalSenn** [comment]
Happy to make a PR as soon as I got the time

**Comment by deinok** [comment]
@PascalSenn Can you give me an abstract example in order to better understand this?

**Comment by PascalSenn** [comment]
Sure:
```csharp

    public interface IWorker 
    {
        string Name {get;set;}
    }

    public class Builder : IWorker
    {
        public string Name {get;set;}
    }

    public class Developer : IWorker
    {
        public string Name {get;set;}
        public string Lang {get;set;}
    }

    public class Team : IWorker
    {
        public IWorker[] Members {get;set;}
    }

    public class BuilderType : ObjectGraphType<Builder>
    {
        public BuilderType() {
            Field(x => x.Name)
        }
    }

    public class DeveloperType : ObjectGraphType<Developer>
    {
        public DeveloperType() {
            Field(x => x.Name)
            Field(x => x.Lang)
        }
    }

    public class TeamType :  ObjectGraphType<Team>
    {
        public TeamType() {
            Field<ListGraphType<WorkerType>>("members", resolve: x => x.Source.Members);
        }
    }

    public class WorkerType : UnionGraphType
    {
        public WorkerType() {
            Type<BuilderType>();
            Type<DeveloperType>();
        }
    }


   // Deserialize into Team will fail because there Members is an interface
```

**Comment by deinok** [comment]
So, for what I understand you need be able to deserialize Types that have Interfaces in its properties.
Is this correct?

**Comment by PascalSenn** [comment]
basically, yes.

**Comment by rose-a** [comment]
Should be possible by adding a custom json converter to `GraphQLHttpClientOptions`

**Comment by maaft** [comment]
Could you give an example how this json converter looks like? 

And shouldn't this be the standard behavior of this client?
