### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. (Parameter 'value') in .net Maui on Android when using WebSockets

### ISSUE THREAD

**Issue by Laradius** [graphql-dotnet/graphql-client#430]
{System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.<>c__DisplayClass27_0`1[[ProgramClassHere, ProgramNameHere, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<CreateSubscriptionStream>b__3(Exception e) in /_/src/GraphQL.Client/Websocket/GraphQLHttpWebSocket.cs:line 211}

It happens when initializing websocket connection (either directly or by subscription stream).

The unhandled exception happens at line 402 of GraphQLHttpWebSocket.cs 

` _clientWebSocket.Options.ClientCertificates = ((HttpClientHandler)Options.HttpMessageHandler).ClientCertificates;`

The error being thrown after execution of it at line 211 is due to X509CertificateCollection ArgumentNullException

` if (!(e is WebSocketException))
                            throw e;`

Error:

```
{System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at System.Net.WebSockets.ClientWebSocketOptions.set_ClientCertificates(X509CertificateCollection value)
   at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.InitializeWebSocket() in [redacted]
   at GraphQL.Client.Http.Websocket.GraphQLHttpWebSocket.<>c__DisplayClass27_0`1.<<CreateSubscriptionStream>b__5>d[[-.Models.GraphQLModels.ResposeTypes.ProjectResponseType, -, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in [redacted] src\GraphQL.Client\Websocket\GraphQLHttpWebSocket.cs:line 157}
```

It works fine on Windows, however it breaks on Android.

Will this client be compatible with .NET MAUI?

**Comment by sungam3r** [comment]
What is the type of `_clientWebSocket` and its options ?

**Comment by Laradius** [comment]
> What is the type of `_clientWebSocket` and its options ?

By line 402 _clientWebSocket type is System.Net.WebSockets.ClientWebSocket and optinons type is System.Net.WebSockets.ClientWebSocketOptions

**Comment by sungam3r** [comment]
I asked about runtime values. On Windows I don't see null check in `ClientWebSocketOptions.ClientCertificates.set`. Maybe `ClientWebSocketOptions` instance on your platform is some inherited type.

**Comment by Laradius** [comment]
((HttpClientHandler)Options.HttpMessageHandler).ClientCertificates returns null

![Screenshot_1](https://user-images.githubusercontent.com/31272990/182094279-2cb57ddd-965e-4c28-83cb-fe6587236992.png)
![Screenshot_2](https://user-images.githubusercontent.com/31272990/182094287-8974eb76-07af-4213-81dc-085bc555dc48.png)
![Screenshot_3](https://user-images.githubusercontent.com/31272990/182094289-3e20b8cf-77f7-4822-be92-a8ab2078765e.png)

**Comment by Laradius** [comment]
> I asked about runtime values. On Windows I don't see null check in `ClientWebSocketOptions.ClientCertificates.set`. Maybe `ClientWebSocketOptions` instance on your platform is some inherited type.

just commenting out the `_clientWebSocket.Options.ClientCertificates = ((HttpClientHandler)Options.HttpMessageHandler).ClientCertificates;` makes the library work, but I doubt it's the correct way

**Comment by sungam3r** [comment]
Ooops, I looked into wrong assembly. Sources:
```c#
 [UnsupportedOSPlatform("browser")]
        public X509CertificateCollection ClientCertificates
        {
            get => _clientCertificates ??= new X509CertificateCollection();
            set
            {
                ThrowIfReadOnly();
                _clientCertificates = value ?? throw new ArgumentNullException(nameof(value));
            }
        }
```

**Comment by Laradius** [comment]
@sungam3r  Thanks a lot for fixing that issue 💯
