### ISSUE TITLE
Consider using IHttpClientFactory instead of HttpClient

### ISSUE THREAD

**Issue by vertonghenb** [graphql-dotnet/graphql-client#44]
Using a HttpClient without using static even when you're disposing the object, is considered a bad practise due to the connection that is in a n a TIME_WAIT state . Consider changing the implementation to use IHttpClientFactory as mentioned by Steve Gordon: 
https://www.stevejgordon.co.uk/introduction-to-httpclientfactory-aspnetcore

https://github.com/graphql-dotnet/graphql-client/blob/7644e14a1be0819cbfdda3909a2257b4778da20b/src/GraphQL.Client/GraphQLClient.cs#L43

**Comment by deinok** [comment]
An interesting feature, but here are some points:
- Microsoft.Extensions.Http is only for netstandard2.0 | This project is also for netstandard1.X
- For now, the Microsoft.Extensions.Http is in preview.
- Also, this seems more likely to avoid the `using` of an HttpClient. The GraphQLClient is like a wrapper for an HttpClient, so it is not used directly.


As an advance, we are going to create an extension method for HttpClient like `httpClient.AsGraphQLClient() -> GraphQLClient`. So you can use an HttpClient for anything and then transform it to a GraphQLClient,

**Comment by RehanSaeed** [comment]
ASP.NET Core 2.1 with HttpClientFactory is out now. It would be useful to add the `AsGraphQLClient()` method tyou mentioned above.
