### ISSUE TITLE
Implementation of HttpClientHandler in Client

### ISSUE THREAD

**Issue by adolfie450** [graphql-dotnet/graphql-client#477]
Due to using graphQL on a Maui App emulated and a .net GraphApiServer (hot chocolate) i need to Implement the HttpClientHandler

`_HttpClient = new HttpClient(new HttpClientHandler()
            {
                ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => true
            });
`
I have used Conveyor and NRok but the above is still needed to Trust the certificates. 

I cannot seem to implement this in the graphql-client so i am forced to use the Plain old Vanilla HttpClient. And this is presenting multiple issues with formatting and I loose out on a lot of features.

Any suggestions or direction would be appreciated.

**Comment by rose-a** [comment]
Use [this constructor](https://github.com/graphql-dotnet/graphql-client/blob/126f120712d66522c6941e5c41e809a07d8ed814/src/GraphQL.Client/GraphQLHttpClient.cs#L61) and inject your `HttpClient`

**Comment by adolfie450** [comment]
Thank you so very much, it works.  My life just got much easier. :)
