### ISSUE TITLE
Query support type Int!

### ISSUE THREAD

**Issue by kunchit** [graphql-dotnet/graphql-client#50]
This is my query

            var keyRequest = new GraphQLRequest
            {
                Query = @"
                                mutation upload($lot: Int!,$start: Int!,$end: Int!,$x: String!,$y: String!,$issue_date: BigInt!,$key_version: BigInt!) 
                            {
                                uploadSerialNumbers(lot: $lot,start: $start,end: $end,x: $x,y: $y,issue_date: $issue_date,key_version: $key_version) 
                               
                            }",
                OperationName = "upload",
                Variables = new
                {
                    lot = 991,
                    start = 1,
                    end = 10,
                    x = "182f000d767dc7695a7793dfce32",
                    y = "04ef74f2738eec34daf98478afdc",
                    issue_date= 1531101827922,
                    key_version= 1
                }
            };

When I post query to web service . I found error like this 

> "Variable \"$lot\" of type \"Int\" used in position expecting type \"Int!\"."

**Comment by deinok** [comment]
Hmm, can you try to run the mutation without the C# client?

Seems more like a Server-side error than from the client.

If this is not the case, report back and I will be glad to help.

**Comment by kunchit** [comment]
Server-side it OK

this test query

> http://35.240.144.126/graphiql

and you can test with query 

> mutation{
  uploadSerialNumbers(
    lot: 887
    start: 1
    end: 10
    x: "182f000d767dc7695a7793dfce32"
    y: "04ef74f2738eec34daf98478afdc"
    issue_date: 1531101827922
    key_version: 1
  )
}

Thank you for help.

**Comment by deinok** [comment]
Thanks @kunchit , Let the server enabled until I report back, tomorrow I will debug the issue.

**Comment by deinok** [comment]
You have an error in the way you return errors in GraphQL Server.

to have access to the message, you are doing error[0].message.message -> value
The Spec, requires something like error[0].message -> value

Also, notice, that you dont have the GET endpoint enabled, so you need to use POST based methods

**Comment by deinok** [comment]
Code to check:

```csharp
var client=new GraphQL.Client.GraphQLClient("http://35.240.144.126/graphql");
client.DefaultRequestHeaders.Add("auth-user", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YjFhMjQzYjY4NzI3ZjcxZjAzZTRkODUiLCJpYXQiOjE1MzAyNjQ0MDgsImV4cCI6NTUzMDI2NjIwOH0.oe9zPy9mbyx4SMUTPXyJ60AYMxAmsVDo3Cdiqey4RhI");
client.DefaultRequestHeaders.Add("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YjFhMjQzYjY4NzI3ZjcxZjAzZTRkODUiLCJpYXQiOjE1MzAyNjQ0MDgsImV4cCI6NTUzMDI2NjIwOH0.oe9zPy9mbyx4SMUTPXyJ60AYMxAmsVDo3Cdiqey4RhI");
var res =client.PostQueryAsync("mutation{uploadSerialNumbers(lot: 887,start: 1,end: 10,x: \"182f000d767dc7695a7793dfce32\",y: \"04ef74f2738eec34daf98478afdc\",issue_date: 1531101827922,key_version: 1)}").Result;
```

**Comment by kunchit** [comment]
It Success.
Thank you I really appreciate your help.

**Comment by deinok** [comment]
Np, Im glad to help :)
