### ISSUE TITLE
Greater than

### ISSUE THREAD

**Issue by tfierens** [graphql-dotnet/graphql-client#514]
Hi,

More a question than an issue. Sorry but google it and got nowhere with it.

How do I define a variable with greater than?

I've got the following query defined in Apollo Explorer:

```graphql
query Cars($where: CarWhereInput) {
  cars(where: $where) {
    id
  }
}
```

and the following variable:

```json
{
  "where": {
    "lastUpdatedOn": {
      "gt": "2022-01-01"
    }
  }
}
```

but all the example I've found seem to only deal with equal operand and the where statement is embedded in the where part. Is there not a way to define it as part of the variable itself as done in the above snippet?

```csharp
var variables = new { updatedOn = "2022-01-01" };
var request = new GraphQLRequest
{
    Query = @"
        query($updatedOn: String!) {
            users(where: { updatedOn: { gt: $updatedOn } }) {
                name
                email
            }
        }",
    Variables = variables
};
```

Thanks

**Comment by tfierens** [comment]
@rose-a I used what was available in the toolbar but totally fair! Apologies and thanks for the snippet! I will give it a try later but can't believe it would be this simple! Tried so many different combinations and get getting an invalid request error and eventually approached in another way. Declared directly as part of the query itself. I didn't like that approach but had to move on.

**Comment by rose-a** [comment]
@tfierens The "variable" from Apollo Explorer is a JSON object. If your variables object from C# serializes to the same JSON string, then you should be good.

You can write yourself a unit test or check it out in something like [LINQPad](https://www.linqpad.net/) or Jupyter...

**Comment by tfierens** [comment]
@rose-a Sorry for the late reply. Only got to try it now and it worked a charm! Thanks again. :). I'll have to check on how to do this in LINQPad alright.
