### ISSUE TITLE
MissingMethodException Exception while creating a new instance of GraphQLHttpClient

### ISSUE THREAD

**Issue by ahmed-saleh101** [graphql-dotnet/graphql-client#515]
Hi,  

I'm getting the exception below while creating a new instance of GraphQLHttpClient.
I've followed the start guide carefully but don't know what's wrong here, I'd appreciate your support giving a hint 

```csharp
var graphQLClient = new GraphQLHttpClient("https://localhost:7000/graphql", new NewtonsoftJsonSerializer());
```

Error:
``` 
System.MissingMethodException: Method not found: void Newtonsoft.Json.Serialization.DefaultContractResolver.set_IgnoreIsSpecifiedMembers(bool)
at GraphQL.Client.Serializer.Newtonsoft.NewtonsoftJsonSerializer..ctor() in /_/src/GraphQL.Client.Serializer.Newtonsoft/NewtonsoftJsonSerializer.cs:line 20
```

GraphQL.Client v 5.1.1
installed also with 5.1.1;
GraphQL.Client.Serializer.Newtonsoft 
GraphQL.Client.Abstractions
GraphQL.Client.Abstractions.Websock
GraphQL.Client.Serializer.Newtonsoft
GraphQL.Client.Serializer.SystemTextJson
GraphQL.Client.LocalExecution
GraphQL.Primitives

Thanks!

**Comment by sungam3r** [comment]
`IgnoreIsSpecifiedMembers` was added here https://github.com/JamesNK/Newtonsoft.Json/commit/967761c21671b20bd7565f5bf632b05857fec972

Check assembly version of `Newtonsoft.Json` dll in your output folder.

**Comment by ahmed-saleh101** [comment]
Hi,
Newtonsoft.Json in the output folder is version 13.0.2
I've also tried to add GraphQl-Projects and Newtonsoft.Json Project to my solution and refernce them as reference projects, but I ended up to the same problem :D 
Probably that's a problem with Avalonia-wasm, I'd appreciate if someone could share a snippet that shows who to configure another serializer rather than Newtonsoft.Json so I can try other alternative 

Thanks!

**Comment by sungam3r** [comment]
Do you use any AOT features, code trimming?

**Comment by rose-a** [comment]
>  I'd appreciate if someone could share a snippet that shows who to configure another serializer rather than Newtonsoft.Json so I can try other alternative.

You can install the [GraphQL.Client.Serializer.SystemTextJson](https://www.nuget.org/packages/GraphQL.Client.Serializer.SystemTextJson) nuget and inject a `SystemTextJsonSerializer` instead of a `NewtonsoftJsonSerializer`...

**Comment by ahmed-saleh101** [comment]
> Do you use any AOT features, code trimming?

Yes, one of the involved projects (the cross platform project) has this entries 
<TrimmerRootDescriptor Include="Roots.xml" />
Roos.xml:
<linker>
  
  <assembly fullname="CallBasketClientCross" preserve="All" />
  <assembly fullname="Avalonia.Themes.Fluent" preserve="All" />
</linker>

Structure:

Web-Blazor depends on CrossPlatform
CrossPlatform depends on DataAccess
DataAccess consumes GraphQLClient

**Comment by sungam3r** [comment]
If you use AOT then you have to be sure that trimmer does not trim all necessary code. What if you disable trimmer and try to run your app or at least a problem part of it ?

**Comment by ahmed-saleh101** [comment]
> If you use AOT then you have to be sure that trimmer does not trim all necessary code. What if you disable trimmer and try to run your app or at least a problem part of it ?

Actually I've removed the trimming but still doesn't work

I assume this might be because the developers from Avalonia said tha their wrapper for Blazor still in early phases, I'll check it later one more time 

For the moment it works with the SystemTextJsonSerializer.  Thank you @rose-a 

Thank you all and have a nice day!
