### ISSUE TITLE
GraphQLHttpClient

### ISSUE THREAD

**Issue by alex-m-git** [graphql-dotnet/graphql-client#516]
Hello everyone!

I have a small question about `GraphQLHttpClient`.
Is `GraphQLHttpClient `thread safe?

In any examples that I found on the Internet, they always create a new instance for each request.
Perhaps this is not correct and I can reduce the overhead and not create a new instance.
For example, I could register `GraphQLHttpClient` as singleton in DI.

**Comment by rose-a** [comment]
Hi, the intended use of `GraphQLHttpClient` is to keep one instance alive per endpoint (obvious in case you're operating full websocket, but also true for regular requests).

So I recommend you register it as singleton in DI.

**Comment by alex-m-git** [comment]
@rose-a 
Thanks a lot for the fast reply :)
