### ISSUE TITLE
Error with .Net Framework 4.6.2

### ISSUE THREAD

**Issue by ammarnaqvi** [graphql-dotnet/graphql-client#52]
I installed the latest version using NuGet and used it in my .net framework 4.6.2 application but I'm getting the following error when deploying to Azure.
` Could not load file or assembly 'System.Diagnostics.Tracing' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) `.
I'd really appreciate some help figuring this out. If any more information is needed, just ask in the comments.

**Comment by deinok** [comment]
This library don't use System.Diagnostics.Tracing directly.
It use it via System.Net.WebSockets.Client (But this is not published yet).

Can you give me more information about your environment, SO, version of GraphQL.Client, etc...
