### ISSUE TITLE
Deserialize Problem of GraphQLHttpClient.

### ISSUE THREAD

**Issue by temo14** [graphql-dotnet/graphql-client#520]
```csharp
var response = await _client.SendQueryAsync<dynamic>(query);
var json = response.Data.product.ToString();
var product = JsonConvert.DeserializeObject<ProductModel>(json);
```
I have to write code like this to deserilze !
When I pass "ProductModel" _client.SendQueryAsync<ProductModel> like this there is returned null values.

there is my service declaration 

```csharp
builder.Services.AddSingleton(t => new GraphQLHttpClient(new GraphQLHttpClientOptions()
{
    EndPoint = new Uri(builder.Configuration["GraphApiUri"]),
    MediaType = "application/json",
}, new NewtonsoftJsonSerializer()));
```

**Comment by rose-a** [comment]
Well, i don't either know your query string nor your `ProductModel`, but I suspect you don`t have a property named "product" in your product model...

`GraphQLHttpClient.SendQueryAsync<ResponseType>()` deserializes the content of **Data**, it does not know the name of your root field in the GraphQL query (alas, there could be more than one...)

It will work if you use a class like this:

```csharp
public class ProductModelResponse {
    public ProductModel Product { get; set; }
}

var response = await _client.SendQueryAsync<ProductModelResponse>(query);
var product = response.Data.Product;
```

**Comment by temo14** [comment]
Thanks <3
