### ISSUE TITLE
ENUM as variable for query not working

### ISSUE THREAD

**Issue by femesq** [graphql-dotnet/graphql-client#525]
Hi,

I have a situation like this:
```C#
var personAndFilmsRequest = new GraphQLRequest
            {
                Query = @"
                        query RequirementsListForObject($projectId: ID!, $milestoneId: ID!, $myObject: ObjectOptions, $objectId: String!) {
                            me {
                                    project(id: $projectId) {
                                        ....
                                                  requirements(filters: { object: $myObject, milestone: $milestoneId }) {
                                                    id
                                                    title
                                                    asseverated(objectId: $objectId)
                                        ....
                                    }           
                                }  
                            }
                        }",
                OperationName = "RequirementsListForObject",
                Variables = new
                {
                    projectId = projectId,
                    myObject = objectType,
                    milestoneId = milestoneId,
                    objectId = objId
                }
            };
```

It seems `ObjectOptions` is not being encoded correctly, resulting in `null` (which is accepted by the backend, since it's optional), but completely messes the expected result.

Is there anything that must be done for correctly encode `ENUM` variables ?

**Comment by rose-a** [comment]
Please post your `ObjectOptions` GraphQL declaration and your objectType.

I suspect its a JSON serialization issue. You could run your request directly though your serializers [SerializeToString](https://github.com/graphql-dotnet/graphql-client/blob/659b1b65b992ca8434ad0e341576bf66379d76db/src/GraphQL.Client.Abstractions/IGraphQLJsonSerializer.cs#L5) method to check if the serialization of your variables object works as expected (like in a unit test or something)...
