### ISSUE TITLE
Make GetAsync preserve Endpoint query params such as API keys

### ISSUE THREAD

**Issue by mjul** [graphql-dotnet/graphql-client#53]
# Problem
`GetAsync` discards query parameters specified in the service URI  `GraphQLHttpClientOptions.Endpoint`. 

# Motivation
This is a problem if we are working with _e.g._ service endpoints that require an API key. Azure Functions are one such example. Here the API key can be provided through query parameter in the URI or an HTTP header. An example of such an endpoint  URI with key is `https://graphqlapi-dev.azurewebsites.net/api/GraphQLService?code=Xp12xdeP3SrF8H/CSaWk5m9Xyf0E5S4gyEF/ex/2L1wEbV5oAPdLQg==` 

If we send a query to that endpoint `GetAsync` will send a query to  `https://graphqlapi-dev.azurewebsites.net/api/GraphQLService?query=...` without the API key in the `code` parameter.
This means access will be denied, making the request fail.

The expected URI would be `https://graphqlapi-dev.azurewebsites.net/api/GraphQLService?code=Xp12xdeP3SrF8H/CSaWk5m9Xyf0E5S4gyEF/ex/2L1wEbV5oAPdLQg==&query=...`

# Cause
The problem is found in the `GetAsync` method on `GraphQLHttpHandler`:

```csharp
		public async Task<GraphQLResponse> GetAsync(GraphQLRequest request, CancellationToken cancellationToken = default) {
			if (request == null) { throw new ArgumentNullException(nameof(request)); }
			if (request.Query == null) { throw new ArgumentNullException(nameof(request.Query)); }

			// THE PROBLEM IS THE FOLLOWING CODE  
			var queryParamsBuilder = new StringBuilder($"query={request.Query}", 3);
			if (request.OperationName != null) { queryParamsBuilder.Append($"&operationName={request.OperationName}"); }
			if (request.Variables != null) { queryParamsBuilder.Append($"&variables={JsonConvert.SerializeObject(request.Variables)}"); }
			using (var httpResponseMessage = await this.HttpClient.GetAsync($"{this.Options.EndPoint}?{queryParamsBuilder.ToString()}", cancellationToken).ConfigureAwait(false)) {
				return await this.ReadHttpResponseMessageAsync(httpResponseMessage).ConfigureAwait(false);
			}
		}
```

# Context
For comparison, it looks like `PostAsync` already preserves the query parameters in the URI since it uses the externally provided service URI in `GraphQLHttpClientOptions.Endpoint` without modification.

# Proposal
Would you be interested in a fix for `GetAsync` that preserves any query parameters specified in the `Endpoint`?

**Comment by deinok** [comment]
Yes, you are right.
I'm okey with this

**Comment by mjul** [comment]
This issue is related to the now obsolete `GraphQLClient` which is being replaced by `GraphQLHttpClient`.
I assume there will be no more releases of the 1.x code and the old version.
I will add some unit tests to the new client code instead.
