### ISSUE TITLE
Built-in support for APQ (Persisted Queries)

### ISSUE THREAD

**Issue by mikocot** [graphql-dotnet/graphql-client#548]
APQ (Automatic Persisted Queries) are strandard and also a requirement for some GraphQL servers and they are also implemented in the graphql-server since 5.3

https://github.com/graphql-dotnet/graphql-dotnet/pull/3134

It would be cool to be able to use this feature out of box with the .net client
Either building the query with some helper methods first, or with opt-in automatic conversion

https://www.apollographql.com/docs/apollo-server/performance/apq/

**Comment by sungam3r** [comment]
I have implemented this in other in-house GraphQL client but I think it can be easily ported here.

**Comment by mikocot** [comment]
> I have implemented this in other in-house GraphQL client but I think it can be easily ported here.

cool, maybe you could at least drop some example code here so we can discuss the best approach to start?

**Comment by mikocot** [comment]
thanks @sungam3r, looks like things are moving fast now!
