### ISSUE TITLE
GraphQL.Client does not account for daylight savings time

### ISSUE THREAD

**Issue by jclausius-sg** [graphql-dotnet/graphql-client#553]
I have a GraphQL query in which the Daylight Savings Time does not seem to be observed.

Currently, a client sits in Chicago's time zone.  UTC is -6, but because of Daylight Savings Time, UTC is now -5.  The client C# code makes a call with some of the following:

string qry = 
@"query($qryDate: DateTime!) { 
    myQuery(where: { and: [{ theDate: {gte: $qryDate} } { theDate: {lte: $qryDate} }] } )
       {  prop1 prop2 prop 3 }
    }";

DateTime d = DateTime.Now();
var request = new GraphQLRequest {
      Query = qry,
      Variables = new { qryDate = d }
    };
... call to TrySenqQueryAsync(request);

---
What we've noticed is that the generated graphql query sends to the server ends up using a timezone offset of -6, although due to Daylight Savings it should be set to -5.

Thank you for your consideration.

-Jeff Clausius
SourceGear

**Comment by rose-a** [comment]
Try using `DateTimeOffset.Now()` instead of `DateTime.Now()`...

**Comment by jclausius-sg** [comment]
Actually, after talking to some of the developers, we discovered the problem.  Some of the date ranges being used were from February.  And Standard Daylight Time was in effect then.  The code above which includes dates from March 12, 2023 (and thereafter) the offset did reflect -5.  

Thanks for the advice. Closing the bug as invalid.
