### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ryanzjohnson-ms** [graphql-dotnet/graphql-client#56]
Are there any plans for a new release of this?

**Comment by joemcbride** [comment]
I'll let @deinok speak to specifics, though I believe a 2.0 release is still being worked on.  https://github.com/graphql-dotnet/graphql-client/issues/53#issuecomment-413526553

You can use myget to try out early releases not yet on nuget.org.

```
https://www.myget.org/F/graphql-dotnet/api/v3/index.json
```

**Comment by ryanzjohnson-ms** [comment]
Perfect thank you!

**Comment by deinok** [comment]
@ryanzjohnson-ms Due the fact that some people ask me to deploy v2, I think that I will release a preview.
Just be careful with thigs marked as `[Obsolete("EXPERIMENTAL")]`. Mostly things related to subscriptions and websockets.

All the other thing are stable.

**Comment by samitsv** [comment]
@deinok I am trying to use the graphql client library in my project for subscription and wanted to know when will the new nuget of the latest graphql client be released?
