### ISSUE TITLE
Implement ws protocol auto negotiation

### ISSUE THREAD

**Issue by gjedlicska** [graphql-dotnet/graphql-client#568]
Based on the comment [here](https://github.com/graphql-dotnet/graphql-client/pull/539#issue-1662372496), ws protocol auto negotiation is not yet supported.

It would be a much appreciated feature, our desktop side apps, using graphql-client may connect to multiple versions of our server side components. It would ease our server side upgrade path a lot.

**Comment by rose-a** [comment]
see [v6.0.0](https://github.com/graphql-dotnet/graphql-client/releases/tag/v6.0.0)
