### ISSUE TITLE
AppSync Subscription error: 'SubProtocolNotSupportedError'

### ISSUE THREAD

**Issue by mehdi-blanchard** [graphql-dotnet/graphql-client#591]
I am trying to implement Subscriptions with [graphql-client](https://github.com/graphql-dotnet/graphql-client) using both [#372 (comment1)](https://github.com/graphql-dotnet/graphql-client/issues/372#issuecomment-964576257) and [#372 (comment2)](https://github.com/graphql-dotnet/graphql-client/issues/372#issuecomment-990590565), and also referring to this [AppSync Websocket guide](https://docs.aws.amazon.com/appsync/latest/devguide/real-time-websocket-client.html)

I've copied [bjorg](https://github.com/bjorg/GraphQlAppSyncTest/tree/main/MyApp)'s GraphQLHttpClientOptionsEx.cs extension class (just replaced options.PreprocessSubscriptionRequest that doesn't exist to options.PreprocessRequest)
I've also tried with edom18 similar solution just in case.

My queries are working but I keep getting the same error when I call CreateSubscriptionStream:

**{"{\"payload\":{\"errors\":[{\"message\":\"SubProtocolNotSupportedError\",\"errorCode\":400}]},\"type\":\"connection_error\"}"}**

If I call InitializeWebsocketConnection I get the error: 

**"The remote party closed the WebSocket connection without completing the close handshake"**

Here is the Visual Studio repository : https://github.com/mehdi-blanchard/GraphQLAppSyncSubscriptionCSharp

Any help would be much appreciated.

![image](https://github.com/graphql-dotnet/graphql-client/assets/9731893/8343949b-17a4-4dca-bdf8-2c836ee36e3b)

**Comment by rose-a** [comment]
Your server says *Sub protocol not supported*! You should check which websocket transport protocol you server supports and configure your client accordingly.

**Comment by mehdi-blanchard** [comment]
The AppSync [developer guide](https://docs.aws.amazon.com/appsync/latest/devguide/real-time-websocket-client.html) specify that the protocol is "graphql-ws", which is the default for GraphQLHttpClientOptions.WebSocketProtocol  
> With these requirements, a WebSocket client can connect to the URL, which contains the real-time endpoint with the query string, using graphql-ws as the WebSocket protocol.

I have no idea what the sub protocol is. Is it different?

**Comment by rose-a** [comment]
The client tries to auto-negotiate, which AppSync does not seem to support...

You can specify the used protocol by setting `GraphQLHttpClientOptions.WebSocketProtocol` to `WebSocketProtocols.GRAPHQL_WS`

**Comment by mehdi-blanchard** [comment]
I've added the line 
`options.WebSocketProtocol = WebSocketProtocols.GRAPHQL_WS;`
and now `GraphQLHttpClient.InitializeWebsocketConnection()` is successfull which is great.

UnfortunateIy I am now getting a new error "You are not authorized to make this call" when I call `Subscribe(...)`

![image](https://github.com/graphql-dotnet/graphql-client/assets/9731893/e541efb7-715f-4d83-aee3-bb86c3bb2ceb)

**Comment by rose-a** [comment]
Well... seems you're not authorized 😉 

I'm not that familiar with the AppSync API, but I'm sure there is documentation about how to authorize against it.

**Comment by mehdi-blanchard** [comment]
@rose-a Success !! 

I found this other [AppSync entry](https://github.com/graphql-dotnet/graphql-client/issues/379) and it helped solving the issue.

Thanks a lot for your help!
