### ISSUE TITLE
Latest stable version (1.0.3) does not expose IGraphQLClient

### ISSUE THREAD

**Issue by rzachariah** [graphql-dotnet/graphql-client#60]
I'm using version 1.0.3 of graphql-client through nuget.

I can access the `GraphQLClient` type, but not `IGraphQLClient` nor `GraphQLHttpClient`.

I'd like to access the client through an interface, so I can mock it out in unit tests.

Also, the available `GraphQLClient` is described as obsolete in the source.
https://github.com/graphql-dotnet/graphql-client/blob/master/src/GraphQL.Client/Obsolete.GraphQLClient.cs

Will `IGraphQLClient` and `GraphQLHttpClient` be available soon?

Thanks!

**Comment by deinok** [comment]
Yes, today we have released v2.0.0-alpha.1
Its pretty stable, but some featurea marked as Obsolete are an Experiment, like subscriptions.
Also, there is some kind of retrocompatibility marked as obsolete
