### ISSUE TITLE
Subscription support?

### ISSUE THREAD

**Issue by Jaroost** [graphql-dotnet/graphql-client#61]
Is a Subscription support planned in this project?

**Comment by joemcbride** [comment]
The 2.0 prerelease has experimental subscription support.

https://github.com/graphql-dotnet/graphql-client/blob/master/src/GraphQL.Client/Http/GraphQLHttpClient.cs#L116

**Comment by deinok** [comment]
ref: #25
Yes, It is planed for V2, for now, we are using the version over WebSockets that use the . NET server and Apollo Server.
There is a prerelease in Nuget that should work. It is marked as experimental, so there can be changes. nevermind, bugs found in Subscriptions can be reported.

**Comment by Jaroost** [comment]
Nice I will try it. thanks
