### ISSUE TITLE
Subscription disposed but connection remains

### ISSUE THREAD

**Issue by zdenekPolicar** [graphql-dotnet/graphql-client#614]
Hi,

How can i force close connection when calling subscription Dispose method?

Thank you for your work,
Zdenek

**Comment by rose-a** [comment]
Hi, 

To close the websocket connection you need to dispose the whole `GraphQLHttpClient` instance.

Whats your use case?

**Comment by zdenekPolicar** [comment]
Hello,
I have a web application with hundreds of users. For each user I create several subscriptions to graphql server. If the user wants, he can manually unsubscribe some. Despite calling .Dispose(), the connection remains and due to the limit of open connections on the server I want to close it. 
I need to maintain and manage these connections on the server side and not on the client side, so this is how it is handled.

Thank you,
Zdenek

**Comment by rose-a** [comment]
A single instance of `GraphQLHttpClient` only opens and maintains 1 websocket connection, which is used for all subscriptions created on it. So reducing the number of subscriptions to the same server in a web app instance won't reduce the number of websocket connections to the server (still 1 per active instance).

If you have more than one, please make sure there is just one instance of `GraphQLHttpClient` in your app (i.e. registered as singleton in DI), that is how its meant to be used.

**Comment by zdenekPolicar** [comment]
Many thanks, i will try.
