### ISSUE TITLE
Subsribtions over wss

### ISSUE THREAD

**Issue by hrstkatomas** [graphql-dotnet/graphql-client#62]
Hello, I am trying recent release v2.0.0-alpha.1 and its new subsriptions feature.
Subsriptions were not working for me due to my server is listening on "wss://..."

Now I am no sure how to fix this the correct way:
 - Should I change my server to be able to handle this?
 - Should graphql-client determine whenever to use "ws://..." or "wss://..." from  "http://" or "https://" endpoints?

Thanks.

**Comment by deinok** [comment]
Hi, you there is no specification of subscriptions, so im not sure if you "should" be able to change this things.

Idealy there should be a mapping like http:// -> ws:// and https://->wss://
But looking at https://github.com/graphql-dotnet/graphql-client/blob/master/src/GraphQL.Client/Http/GraphQLHttpClient.cs#L124
I see that is always forced to WS. So i'm gona fix this issue as fast as possible.
After this is fixed, we will issue a new alpha with the fix.

Thanks for your feedback, its always apreciated.
