### ISSUE TITLE
Making GraphQLHttpClient easier to test

### ISSUE THREAD

**Issue by VladimirAkopyan** [graphql-dotnet/graphql-client#63]
I am building a GraphQL api and using `Microsoft.AspNetCore.Mvc.Testing` to run a test server. 
Ability to inject a HTTPClient into GraphQLHttpClient.cs would make testing much simpler. 
it already has a constructor that takes an HttpClient, it just needs to be made public. 

```CSHARP
internal GraphQLHttpClient(GraphQLHttpClientOptions options,HttpClient httpClient) {
	if (options == null) { throw new ArgumentNullException(nameof(options)); }
	if (options.EndPoint == null) { throw new ArgumentNullException(nameof(options.EndPoint)); }
	if (options.JsonSerializerSettings == null) { throw new ArgumentNullException(nameof(options.JsonSerializerSettings)); }
	if (options.HttpMessageHandler == null) { throw new ArgumentNullException(nameof(options.HttpMessageHandler)); }
	if (options.MediaType == null) { throw new ArgumentNullException(nameof(options.MediaType)); }

	this.graphQLHttpHandler = new GraphQLHttpHandler(options,httpClient);
}
```
see https://github.com/graphql-dotnet/graphql-dotnet/issues/800 for details

**Comment by deinok** [comment]
Hi, @VladimirAkopyan You should be using the `server.CreateHttpHandler()`
This way, the GraphQLHttpClient uses the internal HttpHandler of the TestServer.

If you want to convert an HttpClient to a GraphQLHttpClient use this: -> https://github.com/graphql-dotnet/graphql-client/blob/master/src/GraphQL.Client/Http/HttpClientExtensions.cs

Reopen this if you need more help related to the GraphQLClient

**Comment by leealso** [comment]
Page not found fellas, how can we mock GraphQLHttpClient like we do with HttpClient

**Comment by rose-a** [comment]
You can try to use `GraphQL.Client.LocalExecution`...

**Comment by wantero** [comment]
You can try to mock your HttpResponseMessage using a Mock<HttpMessageHandler> sending to your HttpClient constructor. Send this HttpClient to your GraphQLHttpClient constructor, which will use the mocked HttpClient.

![image](https://github.com/graphql-dotnet/graphql-client/assets/12854717/3d59663e-c788-4c9e-b5d8-1be408f0203a)
