### ISSUE TITLE
Please consider adding [StringSyntax("GraphQL")] attributes

### ISSUE THREAD

**Issue by lol768** [graphql-dotnet/graphql-client#630]
.NET allows you to use the StringSyntaxAttribute to mark up properties that are being used to hold text that an IDE should consider an "injected language".

E.g. `GraphQLRequest.Query` could be marked as a GraphQL fragment, and tools such as [this VSCode plugin](https://marketplace.visualstudio.com/items?itemName=codearchitects-research.GraphQLTools) and other IDEs (e.g. JetBrains Rider) would be able to syntax highlight queries automatically.

**Comment by rose-a** [comment]
Hi, good proposal, hadn't noticed the existence of the StringSyntaxAttribute yet.

Requires a multiframework build though, as its only available from .NET 7 onwards and the library is currently built for .NET Standard 2.0...

**Comment by lol768** [comment]
That's a good point, my PR doesn't properly deal with that at the moment.

I've got a stub implementation of the attribute to enable it to build for .NET Standard 2.0 (or e.g. net6) but there's probably a bit of additional work to do with the build

**Comment by lol768** [comment]
> Requires a multiframework build though, as its only available from .NET 7 onwards and the library is currently built for .NET Standard 2.0...

Have added multiframework `GraphQL.Primitives` build to the open PR.

**Comment by rose-a** [comment]
added in v6.0.4
