### ISSUE TITLE
Subscription closing?

### ISSUE THREAD

**Issue by Jaroost** [graphql-dotnet/graphql-client#64]
Can we close a opened subscription? 

```
var client = new GraphQLClient("http://localhost:5000/graphql");
var subscription = new GraphQLRequest
            {
                Query = @"
                subscription{
                  addressEvent{
                    type
                    isSigned
                    id
                    description
                    addressNumber
                    cncValues{
                      readValue
                      value
                    }
                  }
                }"
            };
response = await client.SendSubscribeAsync(subscription);
response.OnReceive += Response_OnReceive;
```

When I close the application, the server will continue to send subscription data to the client.

I don't know if it is a client or server issue but when subscription is aborted with, for example GraphQLPlayground, we can see that the client send a special close message to the websocket:

`{"id":"1","type":"stop"}`

**Comment by deinok** [comment]
Yes, It could be a bug.
Due the fact that there is no standard about how handling subscriptions, there is not very much information about this.

For now, the Subscription can be closed Disposing it, that in fact, it just close the WebSocket.
So, in fact is an incompatibility due the lack of standard.

**Comment by Jaroost** [comment]
I will try to use it with https://github.com/graphql-dotnet/server 

It's maybe a bug in my personal  implementation of GraphQL-Dotnet server.

**Comment by deinok** [comment]
Okey, but this project is not related to the server. I mean, this Client idealy should work with any GraphQL Server

**Comment by Jaroost** [comment]
Yes of course I don't have any other server right now but maybe i can see what happens with a public Graphql server.

Will try it tomorow.

**Comment by deinok** [comment]
If your server is opensource, I can debug it for you, but probably you are right the GraphQL closing message is not send
