### ISSUE TITLE
Cannot set content-type header in initial request establishing a GraphQL websocket connection

### ISSUE THREAD

**Issue by Highland9r** [graphql-dotnet/graphql-client#642]

**Comment by Highland9r** [comment]
I'm trying to use this library for GraphQL subscriptions but getting the following error "_Connection closed by the server_".

After more investigating, I find out that the initial request /graphql does not contain content-type header that is seem mandatory for the server I'm connecting to. I believe this is a reason of this error. 
Could you please advice?

Thanks a lot in advance

**Comment by rose-a** [comment]
The `Content-Type` header is irrelevant for a websocket connection (see also [this stackoverflow thread](https://stackoverflow.com/questions/35173261/websocket-protocol-request-header-and-response-header-no-content-type)).

Maybe your server needs some form of authentication?

**Comment by Highland9r** [comment]
Thank you so much on a response provided. Yes, you're right, the issue related to missing authentication:
![image](https://github.com/graphql-dotnet/graphql-client/assets/10052188/4442c46f-0f25-4823-891d-632ff4695c39)

However, I have set it via `ConfigureWebsocketOptions` and also via `HttpClient` as following:
 
![image](https://github.com/graphql-dotnet/graphql-client/assets/10052188/c470cc19-bab2-4d77-af4a-5e03dc0b5ca0)

But still getting this error.

Could you please advice?

Thank you in advance

**Comment by rose-a** [comment]
Are u sure that is the authorization header your server expects? I've seen lots of different authorization variants, especially with GraphQL subscriptions (it's a bit like the wild west there...)

Please doublecheck the docs of your server how authentication/authorization with subscriptions work!

**Comment by Highland9r** [comment]
Yes, the server expects a bearer token.

It seems like an issue is caused by https redirection middleware (authentication header is not preserved on redirects). So, when I changed from ws:// to wss:// it starts to work.

**Comment by Highland9r** [comment]
Yeah, here we go: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs#L53-L54
