### ISSUE TITLE
Subscription Id

### ISSUE THREAD

**Issue by Jaroost** [graphql-dotnet/graphql-client#65]
It would be great if we can specifiy an other id than"1" when we create Subscriptions. 

Currently, the id "1" is forced:

https://github.com/graphql-dotnet/graphql-client/blob/master/src/GraphQL.Client/Http/GraphQLHttpSubscriptionResult.cs#L54

**Comment by deinok** [comment]
Can you give some use cases?

**Comment by Jaroost** [comment]
Just to debug subscriptions in a Graphql-dotnet server. instead of just having: `Subscription: 1 got data`

**Comment by deinok** [comment]
Mmm, I would like to avoid it, giving so much power to the user normally causes more problems

**Comment by Jaroost** [comment]
I understand.
