### ISSUE TITLE
More samples please + Does this library support graphql-sse (server-sent events)?

### ISSUE THREAD

**Issue by jzabroski** [graphql-dotnet/graphql-client#650]
Hi,

I'm struggling to find documentation on how this library does subscriptions.  The documentation I found is pretty vague - https://graphql-dotnet.github.io/docs/getting-started/subscriptions/ says "The [GraphQL Server](https://github.com/graphql-dotnet/server/) project provides a .NET Core server that implements the Apollo GraphQL subscription protocol. See the [GraphQL Server project samples](https://github.com/graphql-dotnet/server/tree/develop/samples)."  There is no GraphQL subprotocol called "the Apollo GraphQL subscription protocol" and there is no hyperlink to what this refers to. I think it is referring to [Multipart HTTP Protocol for GraphQL Subscriptions](https://www.apollographql.com/docs/router/executing-operations/subscription-multipart-protocol/) but I'm not sure. As a beginner, this is pretty daunting, as although GraphQL has a standard for the querying part, the transport layer is a "free-for-all hellscape" among servers and clients.  As best as I can tell, only StrawberryShake 13.6+ supports SSE right now.

There is only one sample right now in the examples folder - https://github.com/graphql-dotnet/graphql-client/blob/master/examples/GraphQL.Client.Example/Program.cs - The only other client sample I found was https://github.com/graphql-dotnet/examples/tree/master/src/ClientNet462 - And neither of these demonstrate subscriptions.

I'm _sure_ I can figure this all out in due time, but examples would certainly accelerate the learning curve.  The fact there is a .NET Framework 4.6.2 legacy example is _awesome_, by the way.

**Comment by rose-a** [comment]
Hi,

This library currently implements subscriptions over websocket transport, supporting the `graphql-transport-ws` protocol and its predecessor, the `graphql-ws` protocol (which are also referred to as "The Apollo GraphQL subscription protocol", since Apollo GraphQL devised it as one of the early actual transport implementations for GraphQL subcriptions).

The implementation in this library is fully compatible with the GraphQL Server project (which is also used for integration-testing this library).

Subscriptions over Server-Sent Events is currently not supported by this library. 

> As a beginner, this is pretty daunting, as although GraphQL has a standard for the querying part, the transport layer is a "free-for-all hellscape" among servers and clients. 

Yep, IMO its pretty odd that some third party projects like Apollo GraphQL set "standards" simply by being the first writing down a spec and creating an implementation.

**Comment by jzabroski** [comment]
Hi @rose-a Thanks for your response!

As GraphQL gets used for more external facing uses, this stuff really helps adoption.

> > As a beginner, this is pretty daunting, as although GraphQL has a standard for the querying part, the transport layer is a "free-for-all hellscape" among servers and clients.
> 
> Yep, IMO its pretty odd that some third party projects like Apollo GraphQL set "standards" simply by being the first writing down a spec and creating an implementation.

I mean, if you look at the [Python gql library readme](https://github.com/graphql-python/gql), it's even more complex - there is the ones you mention, plus "AWS AppSync", and "Phoenix channels". But, as best as I understand, there is no place I can even go to find a _list_ of possible sub-protocols, or an easy way to test what capabilities a GraphQL server has?

> This library currently implements subscriptions over websocket transport, supporting the `graphql-transport-ws` protocol and its predecessor, the `graphql-ws` protocol (which are also referred to as "The Apollo GraphQL subscription protocol", since Apollo GraphQL devised it as one of the early actual transport implementations for GraphQL subcriptions).

That's fine, but the demoes don't really show that - they focus on server-to-backend ideal scenarios where the server already has defined the types.  It seems to me, as a naive user poking around, that if you use graphql-dotnet/graphql-client, you should also use the [TypeScript-based C# code generator](https://the-guild.dev/graphql/codegen/plugins/c-sharp/c-sharp-operations) to scaffold out your types so you're not typing that stuff by hand.  But there's no mention of that here.

**Comment by rose-a** [comment]
I definitely get your point.

Since I personally use this library exclusively for building server-to-backend ideal scenarios (server and client in same solution) I don't have a good view on those issues myself (and I also don't have any experience dealing with the specialities of AWS AppSync and the like).

I'd be really grateful if someone with a proper outside view would write some of their experiences down (PRs welcome😉).

**Comment by jzabroski** [comment]
I'm open to it.  But... I'm still not convinced "The Apollo GraphQL subscription protocol" you mention is the same as 

> [Multipart HTTP Protocol for GraphQL Subscriptions](https://www.apollographql.com/docs/router/executing-operations/subscription-multipart-protocol/)

which is what I found online.  Again, total newbie.  I can believe anything except that gullible was removed from the dictionary :)

I think the part that is still flying over my head is exactly what gets seen when debugging the websocket handshake.  I found Wundergraph's article, Quirks of GraphQL Subscriptions, which says:

![image](https://github.com/graphql-dotnet/graphql-client/assets/447485/51ad804a-f3b1-4761-bd55-6b244a5faeb8)

But I'm a little confused - if every handshake is determined by just this header:

```console
Sec-WebSocket-Protocol: graphql-ws, graphql-transport-ws
```

Why don't people explicitly state what sub-protocol they support, rather than use some human readable but vague text that could be misinterpreted?

**Comment by rose-a** [comment]
> I'm still not convinced "The Apollo GraphQL subscription protocol" you mention is the same as [Multipart HTTP Protocol for GraphQL Subscriptions](https://www.apollographql.com/docs/router/executing-operations/subscription-multipart-protocol/)

It is not, this lib only supports subscriptions via websockets using the `graphql-ws` or `graphql-transport-ws` protocols.

If you are interested in how the websocket protocol internally works, checkout the [spec for graphql-transport-ws](https://github.com/graphql/graphql-over-http/blob/main/rfcs/GraphQLOverWebSocket.md)

Regarding transport specification, GraphQL subscriptions over HTTP seem to still be very much in a "wild west" stage, there is [that github project](https://github.com/graphql/graphql-over-http/tree/main) trying to build a proper spec for GraphQL over HTTP, with the various subscription implementations still in RFC stage.
