### ISSUE TITLE
How to pass a list of "input Type" in variables

### ISSUE THREAD

**Issue by gray-tabs** [graphql-dotnet/graphql-client#659]
I am calling the following mutation

mutation CompleteSharedTask($shareLinkId: String!, $completions: [TaskCompletion!]!, $accessToken: String) {
  	completeSharedTask(shareLinkId: $shareLinkId, completions: $completions, accessToken: $accessToken) 
}

I can get this work in the sandbox I have been provided with by using the following json as the variables

```json
{  "shareLinkId": "hmFreaFwXOW2",
  "accessToken": "cTPBp2rw2re7",
  "completions": [
    {
      "taskId": "live|4r9rc5AJ880uf__.maADsxusMXxB!433.433.14",
      "completionDate": "2024-06-10 10:35:52"
    },
    {
      "taskId": "live|4r9rc5AJ880uf__.mgADsxusMXxB!433.433.11",
      "completionDate": "2024-06-10 10:35:56"
    }
  ]
}
```

In my code I am using the following classes

```csharp
public class CompleteSharedTaskModel
    {
        public string accessToken { get; set; }
        public string shareLinkId { get; set; }
        public List<TaskCompletion> TaskCompletion { get; set; }
    } 

public class TaskCompletion
    {
        public string taskId { get; set; }
        public string completionDate { get; set; }
    }
```

and this code to create the query and make the call

```csharp
var request = new GraphQLRequest()
{
     Query = @"mutation CompleteSharedTask($shareLinkId: String!, $completions: [TaskCompletion!]!, $accessToken: String) {
                                completeSharedTask(shareLinkId: $shareLinkId, completions: $completions, accessToken: $accessToken)
                            }",
                    Variables = new
                    {
                        shareLinkId = completeSharedTask.shareLinkId,
                        accessToken = completeSharedTask.accessToken,
                        completions = new { completeSharedTask.TaskCompletion }
                    }
                };
};
```

![image](https://github.com/user-attachments/assets/4c559088-ad61-4cce-b93d-85d36a4729ec)

The problem is that this generates an extra List layer below "completions" in the request which will then get serialized and sent with this extra layer which then returns and error as it doesn't like the format of "completions"
![image](https://github.com/user-attachments/assets/badaed73-92b8-498e-9ad5-52e952b7e4c1)

Error return is 
Variable "$completions" got invalid value { taskCompletion: [[Object]] }; Field "taskCompletion" is not defined by type "TaskCompletion".

My question is how do I get the list to match the json I am using in the sandbox or is there a way to set the variables in the Request to accept json?

thanks

**Comment by rose-a** [comment]
The extra list layer comes from wrapping `completeSharedTask.TaskCompletion` with `new {}`.

`completeSharedTask.TaskCompletion` already is a `List<TaskCompletion>`, so remove the `new{}` around it

**Comment by gray-tabs** [comment]
Thanks for getting back to me.
I made the change but it is now throwing an exception when making the call.
This is what the request looks like now
![image](https://github.com/user-attachments/assets/fa460cae-91e2-4d41-89ca-32fac794f92a)

and this is the exception.  I am not particularly up to speed with json so any help appreciated.

Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'SFG20TaskUpdateService.CompleteSharedTask' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path 'data.completeSharedTask', line 1, position 31.

**Comment by gray-tabs** [comment]
The issue was caused by my deserialization classes not the call the API so all working now
