### ISSUE TITLE
Deserialization returns an empty GraphQLResponse in case of valid JSON but invalid GraphQLResponse

### ISSUE THREAD

**Issue by mdhalgara** [graphql-dotnet/graphql-client#70]
I've come across a situation where trying to call out to a GraphQL service (hosted internally) and using this library causes it to return an empty GraphQLResponse back to the consumer when the response from the service isn't a type of GraphQLResponse.

After cloning this repo and stepping thru the code, I realized that it isn't checking to see whether the response status code is 200 and then attempt to deserialize the response to GraphQLResponse.  Would it be possible to make this adjustment to check the status code first and then perform appropriate de-serialization technique? 

Here's a rough code changes I made to get this to work for me:

```
public async Task<GraphQLResponse> ReadHttpResponseMessageAsync(HttpResponseMessage httpResponseMessage) {
			using (var stream = await httpResponseMessage.Content.ReadAsStreamAsync().ConfigureAwait(false))
			using (var streamReader = new StreamReader(stream))
			using (var jsonTextReader = new JsonTextReader(streamReader)) {
				var jsonSerializer = new JsonSerializer {
					ContractResolver = this.Options.JsonSerializerSettings.ContractResolver
				};
				if (!httpResponseMessage.IsSuccessStatusCode)
				{
					GraphQLResponse response;
					try
					{
						response = jsonSerializer.Deserialize<GraphQLResponse>(jsonTextReader);
					}
					catch (JsonReaderException)
					{
						throw new GraphQLHttpException(httpResponseMessage);
					}

					if (response == null || response.Data == null)
					{
						throw new GraphQLHttpException(httpResponseMessage);
					}

					return response;
				}

				try
				{
					return jsonSerializer.Deserialize<GraphQLResponse>(jsonTextReader);
				}
				catch (JsonReaderException)
				{
					throw new GraphQLHttpException(httpResponseMessage);
				}
			}
		}

```

**Comment by deinok** [comment]
Hi @mdhalgara 
Can you give me a networking log from wireshark with this issue you have found?
As an example, a valid GraphQL Response doesn't need no be inside a 2XX HTTP response.

**Comment by deinok** [comment]
Okey, I see your point, you are right.
>causes it to return an empty GraphQLResponse back to the consumer when the response from the service isn't a type of GraphQLResponse.
I didn't read well your issue.

**Comment by mdhalgara** [comment]
> Okey, I see your point, you are right.
> 
> > causes it to return an empty GraphQLResponse back to the consumer when the response from the service isn't a type of GraphQLResponse.
> > I didn't read well your issue.

If you want me to I can create a PR and check-in my changes to fix this issue? Thanks!

**Comment by deinok** [comment]
Okey, send a PR and add comment in the code linking to this issue to avoid regresions.
Then I will run some benchmarks to see if I can optimize it
