### ISSUE TITLE
Authorization or Header passing

### ISSUE THREAD

**Issue by Kunjahamed-P** [graphql-dotnet/graphql-client#73]
var graphQLClient = new GraphQLClient("https://swapi.apis.guru/");
var graphQLResponse = await graphQLClient.PostAsync(heroRequest);

where we can pass header details or any authorization details in asp.net core, i am unable to pass any header details.

**Comment by deinok** [comment]
`graphQLClient.DefaultRequestHeaders.Add(yourHeader)`

**Comment by Kunjahamed-P** [comment]
{
getPractitioner (caqhId: "13614162")
  {
    practitionerProfileDetail{
      lastAttestationDate,
    }
  }
}


how we can pass as query
