### ISSUE TITLE
Query With Parameters

### ISSUE THREAD

**Issue by Kunjahamed-P** [graphql-dotnet/graphql-client#74]
{
getSample (Id: "13614162")
  {
    pProfileDetail{
      Firstname,
    }
  }
}

please help to pass above query in Dot net (Console, any Core)

**Comment by deinok** [comment]
This is really abstract, just put that as a string in the client.

**Comment by Kunjahamed-P** [comment]
var getgetSample  = new GraphQLRequest
            {
                Query = @" { getSample (Id: $Id) { ProfileDetail  { lastName } } }",
                OperationName = "getSample ",
                Variables = new
                {
                    Id = "13614162"
                }
            };


can we set like this

**Comment by Kunjahamed-P** [comment]
> 
> 
> This is really abstract, just put that as a string in the client.

var getgetSample = new GraphQLRequest
{
Query = @" { getSample (Id: $Id) { ProfileDetail { lastName } } }",
OperationName = "getSample ",
Variables = new
{
Id = "13614162"
}
};

can we set like this
