### ISSUE TITLE
Integration testing vs own GraphQL server

### ISSUE THREAD

**Issue by rose-a** [graphql-dotnet/graphql-client#76]
I would like to build an integration test for a GraphQL client/server "pair" using the way described in https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1.

For this it would be handy if I could inject a `HttpClient` created by the `WebApplicationFactory` into the `GraphQLHttpClient`.

Would you mind exposing the `internal GraphQLHttpClient(GraphQLHttpClientOptions options, HttpClient httpClient)`? I guess this would provide exactly what I need...

**Comment by muneebaahmad** [comment]
👍

**Comment by rose-a** [comment]
Well, I found its actually already exposed via an extension method 'HttpClient.AsGraphQLClient()'.

Here is an extension method I'm now using with `WebApplicationFactory<TEntryPoint>`:

```c#
public static GraphQLHttpClient CreateGraphQlHttpClient<TEntryPoint>(
    this WebApplicationFactory<TEntryPoint> factory, 
    string schemaPath
) where TEntryPoint: class
{
    var httpClient = factory.CreateClient();
    var uriBuilder = new UriBuilder(httpClient.BaseAddress);
    uriBuilder.Path = schemaPath;
    return httpClient.AsGraphQLClient(uriBuilder.Uri);
}
```
