### ISSUE TITLE
Application crash when CancellationToken.Cancel() on subscription

### ISSUE THREAD

**Issue by dojo90** [graphql-dotnet/graphql-client#78]
I create a `subscription` as follows and give the method a `CancellationToken`.

    .SendSubscribeAsync(request, token).ConfigureAwait(false);

As soon as I trigger this (`CancellationTokenSource.Cancel()`), I get an `UnhandledException` and the program crashes:

![image](https://i.imgur.com/U8db9rn.png)

    AppDomain.CurrentDomain.UnhandledException += (sender, args) => CurrentDomainOnUnhandledException(args);

>    bei System.Threading.CancellationToken.ThrowOperationCanceledException()
   bei System.Net.WebSockets.WebSocketConnectionStream.<ReadAsync>d__21.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei GraphQL.Client.Http.GraphQLHttpSubscriptionResult.<StartAsync>d__12.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   bei System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   bei System.Threading.ThreadPoolWorkQueue.Dispatch()
   bei System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

How did you imagine that you catch these exceptions or how should I do it?

I also noticed that you did not pass the `cancellationToken` on `SendGraphQLSubscriptionRequest()`.

https://github.com/graphql-dotnet/graphql-client/blob/1ae831065732ff44679462ff588377863c7e6353/src/GraphQL.Client/Http/GraphQLHttpSubscriptionResult.cs#L77

**Comment by deinok** [comment]
>I also noticed that you did not pass the cancellationToken on SendGraphQLSubscriptionRequest().
Good catch, it also happenz in https://github.com/graphql-dotnet/graphql-client/blob/master/src/GraphQL.Client/Http/GraphQLHttpSubscriptionResult.cs#L52

Okey, be careful, because subscriptions is a really experimental API, it will have breaking changes on 2.0.0 and currently is untested.

I will create a patch for this, you will just need to clear your project and rebuild. Wait until tomorrow

**Comment by deinok** [comment]
Update to v2.0.0-alpha.3 should be fixed there. If the issue persists, reopen this please
