### ISSUE TITLE
Why does  GraphQLClient change the timezone to local time ?

### ISSUE THREAD

**Issue by Kunjahamed-P** [graphql-dotnet/graphql-client#81]
GraphQLClient  ignoring the specified timezone and converting the DateTimeOffset to the local offset
when i using below query,
			using (var GraphQLClient = new GraphQLClient(HttpClientAPI))
            {
					GraphQLClient.DefaultRequestHeaders.Add(HeaderKey, HeaderValue);
                    var Response = await GraphQLClient.PostAsync(GrapgQLQuery);
				
			}

The obj will contain a property containing a DateTimeOffset but the value will be 2018-09-19T13:50:36.925064+05:30
 i.e. converted to the local timezone  instead of preserving the original timezone .

but actual output is : "2018-10-19T06:12:16.4321713-04:00"   when the same query run from PostMan or GraphQL PlayGround.

Is there a way to get the as expected ?

**Comment by deinok** [comment]
Please, post here GrapgQLQuery and Headers.
It is strange, cause GraphQL.Client does not handle anything related to Timezone

**Comment by Kunjahamed-P** [comment]
This is Output from GrapgQL Client : 

{
    "data": {
        "getPractitioner": [
		{
        "Information": {
          "Id": 13613974
        },
        "ProfileDetail": {
          "lastAttestationDate": "2018-10-19T06:12:16.4321713-04:00"
        }
		}
        ]
    }
}
The Post man Result is : 

{
    "data": {
        "getPractitioner": [
		{
        "Information": {
          "Id": 13613974
        },
        "ProfileDetail": {
          "lastDate": "2018-10-19T15:42:16.4321713+05:30"
        }
		}
        ]
    }
}

The Query and Header details are same in Both

**Comment by deinok** [comment]
Your server, what library is using, also put here the graphql schema. I think tht your backend is making the conversion

**Comment by Kunjahamed-P** [comment]
try with GraphQL.Client 1.0.3 and 2.0.0.0. No backend convertion  bcs same is working in postman

**Comment by deinok** [comment]
You can review the code of the library, it is not handling anything related to time
