### ISSUE TITLE
GraphQLRequest's  Construcotor Does Not Take Arguments

### ISSUE THREAD

**Issue by kmanev073** [graphql-dotnet/graphql-client#89]
Hi guys!

I am trying to run the example code from the readme but it seems that the GraphQLRequest's constructor takes only parameter?

`var heroRequest = new GraphQLRequest(@"
    {
      hero {
        name
      }
    }"
);`

I've installed 1.03 versions of both GraphQL.Client and GraphQL.Common.

This is the code. Basically I can't pass my query because I get a VS error. Should I do this?

`var heroRequest = new GraphQLRequest
{
   Query = @"
    {
      hero {
        name
      }
    }"
}`

Thanks in advance!

**Comment by deinok** [comment]
https://github.com/graphql-dotnet/graphql-client/tree/v1.0.3

We are doing some changes for v2.0.0 that is actualy on master

**Comment by kmanev073** [comment]
Can you give some instructions on how to use the library or I have to wait?

**Comment by deinok** [comment]
Look at the README of v1.0.3, the link above.

**Comment by kmanev073** [comment]
Thanks <3
