### ISSUE TITLE
Retrieving Headers from Response

### ISSUE THREAD

**Issue by ThomasAunvik** [graphql-dotnet/graphql-client#90]
I have been having a problem where i have been trying to get headers from GraphQLResponse. And i have seen that it is possible for example in [HttpRequest#Headers](https://docs.microsoft.com/en-us/dotnet/api/system.web.httprequest.headers?view=netframework-4.7.2), but not in here, like for example i have been trying to get headers from [Anilist](https://anilist.gitbook.io/anilist-apiv2-docs/overview/rate-limiting) so i could stop myself getting rate limited.

Is there a way to get headers from `GraphQLResponse` or `GraphQLHttpClient`?

**Comment by deinok** [comment]
Seems like we need a better way to handle the HttpInternal Middleware

**Comment by rose-a** [comment]
I suppose it would be best to add something like `public Task<GraphQLResponse<TResponse>> SendQueryAsync<TResponse>(GraphQLRequest request, out HttpResponseHeaders headers, CancellationToken cancellationToken = default)` to `GraphQLHttpClient`?

@sungam3r What's your opinion on this?

**Comment by sungam3r** [comment]
A separate method with `HttpResponseHeaders` will not look very good. Where do you add it? `GraphQLHttpClient` ? Clients work with `IGraphQLClient`, I suppose.

I propose to add `bool GraphQLHttpClientOptions.ReturnHeaders { get; set; }` and `Dictionary<string, string> GraphQLResponse<T>.AdditionalProperties` . Naming is negotiable .

**Comment by sungam3r** [comment]
Or something like `GraphQLHttpResponse<T> : GraphQLResponse<T> { Headers }`

**Comment by rose-a** [comment]
> Or something like GraphQLHttpResponse<T> : GraphQLResponse<T> { Headers }

This would certainly be the cleanest way, but it will not work when the websocket is used for sending queries/mutations (obviously, because there are no headers then). I hope this is obvious to the consumers of this library, too... 🤔
