### ISSUE TITLE
HttpMessageHandlers collection

### ISSUE THREAD

**Issue by jhensley707** [graphql-dotnet/graphql-client#95]
You allow us to specify one HttpMessageHandler in GraphQLHttpClientOptions to pass into the HttpClient constructor. This prevents the ability to construct our own client Message pipeline as recommended by using the HttpClientFactory and a collection of delegating clients in the [MS docs](https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/httpclient-message-handlers).
Any chance you could add an additional property to Options so that we can add our delegating handlers?

**Comment by deinok** [comment]
@jhensley707 In preview code for v2.0.0 we have the an extension method to build a GraphQLClient using a HttpClient (that can be generated with the factory).

And about delegating handlers its interesting, I should look at it
